### ISSUE TITLE
歌曲日文显示乱码问题(这问题比较诡异

### ISSUE THREAD

**Issue by arkbriar** [cosven/FeelUOwn#1]
首先，我直接pull你的代码到本地运行，然后，播放一首日文歌曲，不论是播放器下面的还是菜单栏的气泡弹窗中，日文都是乱码，其他地方日文都是ok的。
然后我做了这么一件事

``` diff
diff --git a/src/controllers.py b/src/controllers.py
index a83d434..673d927 100644
--- a/src/controllers.py
+++ b/src/controllers.py
@@ -315,7 +315,7 @@ class MainWidget(QWidget):
         self.current_playlist_widget.add_item_from_model(music_model)
         self.current_playlist_widget.focus_cell_by_mid(music_model['id'])

-        self.trayicon.showMessage(u'正在播放: ', music_model['name'])
+        self.trayicon.showMessage(u'正在播放: ほ', music_model['name'])

         self.state['current_mid'] = music_model['id']
         if self.state['is_login']:
```

我仅仅添加了一个日文字符，它就好了！
我觉得是python要么qt没有加载某个字符库
预计原因是pyqt的锅，有空作者君查查

BTW，shell下抛了一个Error

``` shell
Traceback (most recent call last):
  File "/home/homura/Documents/NetEaseMusic/src/widgets/login_dialog.py", line 189, in on_login_success
    self.nm.finished.disconnect(self.on_nm_finished)
TypeError: disconnect() failed between 'finished' and 'unislot'
```

qt的signal和slot貌似出了什么问题，顺带定位下吧

**Comment by cosven** [comment]
第一个问题
-------------------------------
- 我在Deepin 2014.3测试下，它没有乱码。
- 在Ubuntu 14.04 ,有日语的部分，只有window title 不是乱码，其他部分（歌曲列表部分，通知部分，还是进度条下面的部分）都会乱码，然后我试着用你上面提到的这个方法，好像失败了，它仍然乱码。

第二个问题
------------------------------
我之后会把这个地方的实现思路换一下的。

last but not least, 谢谢帮助与反馈

**Comment by cosven** [comment]
目前发现UBuntu 14.04 中文系统日文不会乱码

**Comment by AkemiHomura** [comment]
...我这边问题已经神奇爆了，我尝试了好几种办法，甚至让'正在播放'调用一个不存在的方法都能不乱码，我这边很可能是个例，等下次有空我再试试

**Comment by AkemiHomura** [comment]
刚找到解决方法，这个问题出现应该是出现字库缺失的问题，不知道qt fallback到了哪个字体上去。之前我描述的也有问题，出现的是小方块而不是$%^&*(这种乱码。
我这边修改了src/themes/default.qss下的QWidget的font
```diff
diff --git a/src/themes/default.qss b/src/themes/default.qss
index 574db11..0b202de 100644
--- a/src/themes/default.qss
+++ b/src/themes/default.qss
@@ -52,6 +52,7 @@ QGroupBox::title {
 /* ****************************** */
 
 QWidget {
+    font: regular "WenQuanYi Micro Hei";
     background-color: #272727;
     color: #CCCCCC;
 }
```
解决了这个问题
这个方法不建议照搬，建议做成一个控制菜单

**Comment by cosven** [comment]
我下载了文泉驿的字体，在英文系统下试了下后面你说的这个方法， 结果还是不行。

**Comment by AkemiHomura** [comment]
linux字体机制比较奇怪，英文系统有空我也尝试下;
我根据arch wiki改过linux字体配置，可能与这个也有关系;
近期我会做下测试然后反馈的

**Comment by AkemiHomura** [comment]
@cosven 我pull了你最近的更新，这个问题不再出现了
最近我被老板驾照暑期课逼疯了...实在没工夫尝试英文系统，不知道英文系统下出现的是小方块还是其他形式的乱码？
另，附[arch wiki 字体回滚设置]
(https://wiki.archlinux.org/index.php/Fonts_%28%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%29#X11.E4.B8.AD.E7.9A.84.E5.AD.97.E4.BD.93.E5.9B.9E.E6.BB.9A.E9.A1.BA.E5.BA.8F)
主要用以解决linux终端中文下沉的问题

**Comment by cosven** [comment]
我最近又在忙活这个软件的异步架构的问题（对异步这些架构设计完全没有经验），所以也没怎么花时间研究这个问题。我暂时想先把它放放

**Comment by Verrickt** [comment]
嘿，你们好，我也遇到了日文显示的问题。
Ubuntu 14.04.4 英文版，安装了中文支持。
所有的日文字符显示为方块。
我去试下1F的方法

**Comment by zxwwsj** [comment]
linuxmint17.3。“思源黑體跟 Noto Sans CJK 是同一個東西（名稱不同而已），Google 叫它 Noto Sans CJK，並以「Noto」來代表「No Tofu（沒有豆腐）」，旨在消滅電腦中無法顯示其他語言文字時的的那些空白方塊（豆腐形狀）。而「Sans」指的是「無襯線」字體，文字的頭尾沒有裝飾用的線條、筆劃粗細較為一致，對應到中文字型則為「黑體字」。 CJK 代表：中日韓（CJK）統一表意文字，表示這個字體裡面包含了中日韓…等語言中稍有微小差異的各種漢字。”然后我添加字体果然好了。
![2016-03-07 20 06 42](https://cloud.githubusercontent.com/assets/17702480/13568982/2e7de278-e4a0-11e5-8599-96bd8d46ff25.png)
