### ISSUE TITLE
求助：2016年２月１日版本出现网络连接超时

### ISSUE THREAD

**Issue by michelfei** [cosven/FeelUOwn#100]
我更新了软件版本，发现只要用邮箱一登录就会提示网络连接超时，但是网路并无大问题。我用的linuxmint64位，之前用的好好的，依赖都有。
因为我自己有在路由器上手动设置dns，这个会有影响吗？但是其它软件都没什么问题。

**Comment by cosven** [comment]
dns 是会有影响的。
#52  #46 
如果 dns 有问题的话，网页版也不能的。你可以试试
