### ISSUE TITLE
Arch Linux AUR 安装 feeluown-git，缺少了 pyaml 的依赖，希望打包加上～～

### ISSUE THREAD

**Issue by BruceZhang1993** [cosven/FeelUOwn#101]

**Comment by LastAvenger** [comment]
这种事情你应该去联系 AUR 的打包者。

**Comment by BruceZhang1993** [comment]
@LastAvenger 诶，不是作者打包的么，因为在README看到所以误认为～～

**Comment by LastAvenger** [comment]
@BruceZhang1993 打包者： https://github.com/cosven/FeelUOwn/pull/44
另外包的问题直接在 AUR 的包下面 comment 就好。
