### ISSUE TITLE
在线歌曲播放速度不正常

### ISSUE THREAD

**Issue by kissunyeason** [cosven/FeelUOwn#105]
有些歌曲前一分钟是自动加速播放，到后面就好了，有些歌曲是自动一直加速，一首歌10多秒就播放完毕了。  Ubuntu 15.10 AMD64

**Comment by luwenhegithub** [comment]
我也遇到了同样的问题

**Comment by LER0ever** [comment]
我也早就碰到过这个问题了，不过貌似我重新装了一下又好了 #31

**Comment by kissunyeason** [comment]
试过了，不管用的，还是网页版吧
Date: Wed, 23 Mar 2016 01:39:36 -0700

**Comment by cosven** [comment]
恩，去用网页版把 。
