### ISSUE TITLE
请问怎么退出登陆

### ISSUE THREAD

**Issue by crabkun** [cosven/FeelUOwn#106]
点击用户头像出现“退出”　，点了之后程序就直接退出了，再打开还是自动登陆那个号

**Comment by cosven** [comment]
你需要把在网页版中把基本信息完善。

**Comment by cosven** [comment]
(我理解错了...)
目前没有退出登陆的功能。如果硬是想登录另外一个帐号，可以删除.FeelUOwn目录，这样下次就需要重新登录。
