### ISSUE TITLE
搜索框无法输入中文

### ISSUE THREAD

**Issue by JoyeeCai** [cosven/FeelUOwn#107]
## 很好用，发现一些bug，希望能够修复。

- 如题，使用搜狗输入法在搜索框中是无法输入中文搜索的，只能通过拷贝粘贴达到效果，不知道其他输入法是否有这种情况。
- unbuntu 中普通用户安装后，FeelUOwn.desktop 中配置的图标打开无法出现声音  
```Exec=python3 /home/anon/Github/FeelUOwn/feeluown/main.py```  
修改成  
```Exec=sudo python3 /home/anon/Github/FeelUOwn/feeluown/main.py```
进行提权后可以正常播放声音，可能是权限问题，我是配置了sudo 免密码的授权

**Comment by cosven** [comment]
中文搜索的问题，安装这个包应该就可以了。`fcitx-frontend-qt5`
权限的问题可能是需要你自己去处理下
