### ISSUE TITLE
启动失败在archlinux

### ISSUE THREAD

**Issue by helinb** [cosven/FeelUOwn#11]
[root@helinbao-pc FeelUOwn]# python3  /opt/FeelUOwn/src/main.py
Traceback (most recent call last):
  File "/opt/FeelUOwn/src/main.py", line 33, in <module>
    w = MainWidget()
  File "/opt/FeelUOwn/src/controllers.py", line 41, in __init__
    self.ui.setup_ui(self)
  File "/opt/FeelUOwn/src/views.py", line 29, in setup_ui
    self.left_widget = LeftScrollArea()
  File "/opt/FeelUOwn/src/left_widget.py", line 23, in __init__
    self.central_widget = LeftWidget()
  File "/opt/FeelUOwn/src/left_widget.py", line 50, in __init__
    self.create_list_widget = PlaylistWidget()
  File "/opt/FeelUOwn/src/widgets/playlist_widget.py", line 19, in __init__
    self.fold_animation = QPropertyAnimation(self, 'maximumHeight')
TypeError: arguments did not match any overloaded call:
  QPropertyAnimation(QObject parent=None): too many arguments
  QPropertyAnimation(QObject, QByteArray, QObject parent=None): argument 2 has unexpected type 'str'

**Comment by wrj898** [comment]
相同的问题

**Comment by cosven** [comment]
我这边暂时没有 ArchLinux的环境，不过我在ubuntu和deepin上都测试了。
目前的解决办法可能需要把动画效果取消。今明两天，我会尽快处理这个问题的

另外，我大致猜测是 pyqt5版本 或者 python3版本问题。

**Comment by light4** [comment]
/src/widgets/playlist_widget.py 中 QByteArray() 参数保持为空就可以启动了。

``` python
self.fold_animation = QPropertyAnimation(self, QByteArray())
self.spread_animation = QPropertyAnimation(self, QByteArray())
```

**Comment by cosven** [comment]
如果把QByteArray设置为空的话，也就没有动画效果了。
看来目前只能这样子了。

**Comment by light4** [comment]
这样可以了：
``` python
self.fold_animation = QPropertyAnimation(self, QByteArray(bytes('maximumHeighttttttttttt', 'ascii')))
self.spread_animation = QPropertyAnimation(self, QByteArray(bytes('maximumHeighttttttttttt', 'ascii')))
```
不过感觉没太大效果啊

**Comment by helinb** [comment]
安装上面所说的改了还是不行

[root@helinbao-pc opt]# python3  FeelUOwn/src/main.py 
Traceback (most recent call last):
  File "FeelUOwn/src/main.py", line 18, in <module>
    from controllers import MainWidget
  File "/opt/FeelUOwn/src/controllers.py", line 19, in <module>
    from widgets.playlist_widget import PlaylistWidget, PlaylistItem
  File "/opt/FeelUOwn/src/widgets/playlist_widget.py", line 21
    self.maximum_height = 500
    ^
IndentationError: unexpected indent

**Comment by light4** [comment]
楼上是 python 格式乱了吧。。你先把 QByteArray() 改成空的吧

**Comment by cosven** [comment]
我暂时把 QByteArray() 改成空的了。
没找到什么好的解决办法。。。

**Comment by helinb** [comment]
可以运行了

**Comment by cosven** [comment]
多谢 light4 修复了这个bug

**Comment by helinb** [comment]
又有新的问题 播放歌曲进度显示：00:00
根本播放不了歌曲而且听不到声音，可以播放mv，并且听到的声音

**Comment by cosven** [comment]
没太懂你的意思？

你是每次播放歌曲都有这个问题，还是偶尔出现这个问题？

**Comment by helinb** [comment]
等待播放的时间长

**Comment by cosven** [comment]
这个一方面是网络的原因，我试过很多网络环境，基本保持有100kb的网速的话，就不怎么会卡。
另一方面的话，因为程序基本单线程，所以操作可能响应比较慢。

这段时间我正在学习改进程序的架构，致力于提高程序的并行，然而还没弄好。。。

> 我自己刚刚又试了下，好像的确要等很久，我之后会仔细研究研究。

另外，我新开一个issue 好了。

**Comment by cosven** [comment]
"\u672A\u627E\u5230\u97F3\u91CF\u63A7\u5236"
在Python中，print("\u672A\u627E\u5230\u97F3\u91CF\u63A7\u5236")即可看到结果

这句话意思是“未找到音量控制”，这是从哪里来的。。我没见到过

**Comment by helinb** [comment]
我用的是alsa管理声音，而alsa调节音量用命令alsamixer

**Comment by harry159821** [comment]
https://www.riverbankcomputing.com/pipermail/pyqt/2015-July/036215.html
只要把 str 的参数转换成 byte 类型即可，例如 'pos' 改成 b'pos'

**Comment by cosven** [comment]
哦，的确可以，谢谢 @harry159821 
变量类型错了。。byte这个类型的确接触不是很多..
