### ISSUE TITLE
本地音乐功能设计 - 讨论

### ISSUE THREAD

**Issue by cosven** [cosven/FeelUOwn#112]
### 设计文档

`思考`：本地音乐和网络音乐的区别实质是**来源**不同。所以从实现的角度来讲，需要重新写一套API。
**好像也不只来源不同，音乐的基本信息也会不一样。本地歌曲的artist只是一个歌手的名字，但是网络歌曲所携带的artist信息的全**

#### 功能预期
1. 默认递归读取 ~/Music 文件，最大递归层数 2-3 层
2. 用户可以通过手动修改配置文件 `~/.FeelUOwn/config.yaml` 来修改默认读取的位置。
3. 在界面的左侧新增一个 **本地歌曲** 的选项
4. 程序每次启动都会重新扫描文件夹中歌曲的变动

###### M
为本地音乐建一个数据 Model，`LocalSongModel`

**由于整个设计的一个假设是：所有的歌曲都会符合 `MusicModel`，所以可能要重构很多东西，比如 player**

基于这种考虑，是不是把 `LocalSongModel` 通过某种方式转换为 `MusicModel` 会比较靠谱...， 如果是这样的话，那就非常麻烦，不过这种可行性比较高。

###### V
在界面左侧添加按钮，类似于普通的歌单按钮
使用 TracksMusicTableWidget 显示

###### C
播放逻辑和播放网络歌曲的逻辑相同
但是图片、基本信息获取可能不一样。

#### 其他

**不确定性**

- 不保存音乐的信息，每次启动时读取一遍。
- 保存音乐的信息在一个 json 文件中，每次启动检查变动。
- 歌曲太多可能导致性能问题？

**已知可能出现的问题**

1. 部分音乐没有专辑图片
2. 部分音乐的 ID3 信息可能乱码
3. 可能部分音乐格式不能支持

**Comment by cosven** [comment]
@wzdnzd

**Comment by cposture** [comment]
能否使用工厂方法模式实现MusicModel类及其子类的实例化，然后动态绑定到一个当前的C上？

**Comment by wzdnzd** [comment]
我想的同cposture想的一样，图片啊专辑啊什么的倒不是很在乎。。

**Comment by DrXie** [comment]
如果以后真的有本地音乐的话，希望能够像Phonograph(Android) 一样，歌手或专辑的图片能够从last.sh 或其他音乐资源平台抓取。
