### ISSUE TITLE
建议稍微完善一下歌词部分

### ISSUE THREAD

**Issue by guopm** [cosven/FeelUOwn#113]
首先感谢辛勤的劳动，让吾等Linux党又一次扬眉吐气了:)
然后是一些细微的吐槽和建议，先上图（用git更新到了1d8de88）
![20160304-20 50 06-992x697](https://cloud.githubusercontent.com/assets/12870754/13527690/e698a9ee-e24b-11e5-9c0e-14c6c78dd601.png)
不知道源代码中对歌词是怎样解析的，有时候歌曲播放伊始就会出现如图的囧况
and能不能放开一下歌词的自定义呢？至少先开放颜色更换也行，红色字有时候不是看的很清楚^_^

系统和DE是Debian sid amd64，xfce（虽然我觉得跟它们关系不大）

**Comment by BruceZhang1993** [comment]
歌词文件开头的歌曲信息可以考虑去掉～ 因为信息已经显示在播放进度条的区域了

PS. 自定义颜色或者给几个配色方案 +1～
