### ISSUE TITLE
升级安装之后无法使用

### ISSUE THREAD

**Issue by llq520** [cosven/FeelUOwn#115]
~/FeelUOwn$ sh app.sh
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from feeluown import config
  File "../feeluown/__init__.py", line 3, in <module>
    from .config import config
  File "../feeluown/config.py", line 5, in <module>
    import yaml
ImportError: No module named 'yaml'

pip3 install -r requirements.txt
bash: pip3: 未找到命令

/FeelUOwn$ sudo apt-get install python3-pip
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python3-pip is already the newest version (8.0.2-7).
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 19 个软件包未被升级。

install.sh运行过i没有报错所有都安装了

升级更新之前的版本使用正常，升级之后完全无法使用

**Comment by cosven** [comment]
你的情况是安装了 `pip3`.
但是运行 pip3 ，却说找不到命令。这种情况是不科学的。

你可以尝试 `pip install -r requirements.txt`

**Comment by llq520** [comment]
昨天试过了sudo apt-get purge  python3-pip  然后重装还是不行

**Comment by cosven** [comment]
都不行的话，那就只能试试 `easy_install3 pyyaml`

**Comment by llq520** [comment]
好的  我稍后试试

**Comment by llq520** [comment]
好的  我稍后试试

**Comment by llq520** [comment]
llq@llq-pc:~$ easy_install3 pyyaml
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-2522.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.5/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

llq@llq-pc:~$ cd FeelUOwn/
llq@llq-pc:~/FeelUOwn$ easy_install3 pyyaml
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-2534.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.5/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by llq520** [comment]
llq@llq-pc:~/FeelUOwn$ sudo easy_install3 pyyaml
Searching for pyyaml
Reading https://pypi.python.org/simple/pyyaml/
Best match: PyYAML 3.11
Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.zip#md5=89cbc92cda979042533b640b76e6e055
Processing PyYAML-3.11.zip
Writing /tmp/easy_install-zk2tkotk/PyYAML-3.11/setup.cfg
Running PyYAML-3.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zk2tkotk/PyYAML-3.11/egg-dist-tmp-q4ewg9x7
build/temp.linux-x86_64-3.5/check_libyaml.c:2:18: fatal error: yaml.h: 没有那个文件或目录
compilation terminated.

libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
zip_safe flag not set; analyzing archive contents...
Moving PyYAML-3.11-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
Adding PyYAML 3.11 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/PyYAML-3.11-py3.5-linux-x86_64.egg
Processing dependencies for pyyaml
Finished processing dependencies for pyyaml

**Comment by cosven** [comment]
额，不好意思，你这种情况属于少数...
```
sudo easy_install3 pip3
sudo pip3 install -r requirements.txt
```

**Comment by llq520** [comment]
~$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Storing debug log for failure in /home/llq/.pip/pip.log

自从这次升了级就没发用了 之前好好的

**Comment by llq520** [comment]
cat /home/llq/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Tue Mar  8 16:22:34 2016
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 274, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1547, in parse_requirements
    session=session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 278, in get_file_content
    raise InstallationError('Could not open requirements file: %s' % str(e))
InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by llq520** [comment]
现在变成这样了

llq@llq-pc:~/FeelUOwn$ sh app.sh 
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from quamash import QEventLoop
ImportError: No module named 'quamash'

**Comment by carrjay** [comment]
[cp]Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-ycab8098/SQLAlchemy/  You are using pip version 8.1.0, however version 8.1.1 is available.  You should consider upgrading via the \'pip install --upgrade pip\' command.[/cp]提示这个pip要更新，可又更新不了！就卡在这步了。目前系统是deepin15.1.1 64位'有解决的办法么，会不会跟我的宽带有关系。我用手机的数据网也试过情况一样

**Comment by cosven** [comment]
@carrjay 
你可以先升级 pip。为啥更新不了呢？出现了什么错误？

**Comment by carrjay** [comment]
就是按照上面的提示命令更新的，一直没进度光标一直闪。愁死我了

**Comment by carrjay** [comment]
我用的是deepin的官方源，以前该有阿里的现在新的系统里没有

**Comment by carrjay** [comment]
找到了，在python官网有我单独下载了
