### ISSUE TITLE
能「上传」音乐吗？

### ISSUE THREAD

**Issue by kashu** [cosven/FeelUOwn#116]
### 能否支持「上传」音乐到网易云音乐？

**Comment by cosven** [comment]
不能的（其实我都不知道还有这个功能）

**Comment by kashu** [comment]
### 开发人员能否考虑增加「上传功能」？
### 谢谢！

**Comment by kashu** [comment]
### 网易云音乐推出「音乐云盘」功能，可以用于存储自己的音乐文件。
### 你只要将自己的 MP3 音乐上传到云盘去，就可以在手机、电脑端随时收听！
