### ISSUE TITLE
不小心把一个叫xcb的东西给卸载了，结果程序运行后都看不到界面

### ISSUE THREAD

**Issue by cposture** [cosven/FeelUOwn#117]
系统：ubuntu 15.04
卸载的组件：xcb什么的
问题：忘了被我卸载的程序叫什么名了，有谁帮我看一下你们系统和xcb的相关的组件都有什么，好让我装回去，谢谢大家了

**Comment by cosven** [comment]
你是所有的程序都看不到界面了，还是只看不到这个软件的界面。

**Comment by cposture** [comment]
一个，和Qt相关的一些程序会看不到界面，比如VLR视频播放器还有FeelUOwn

**Comment by cosven** [comment]
`sudo apt-get install libx11-xcb1` 试试...

**Comment by cposture** [comment]
已经是最新版本了，但还是不行
