### ISSUE TITLE
希望添加歌单内歌曲编号或者歌单内搜索

### ISSUE THREAD

**Issue by LER0ever** [cosven/FeelUOwn#118]
我有好几个超过1000首歌的歌单，基本上定位歌曲是靠大概第几首或者歌单内搜索。希望FeelUOwn也添加个歌单内搜索。

然后就是Issue #77 在Linux下也有了(_可能因为我歌单巨多_)，不过不怎么影响使用。点击是可以点到歌单的，但是点完之后会自动往下跳。

顺便，歌词建议换个颜色，半透明黑+暗红不是很明显，我每次更新完都是手动qss调到#FFD700的 :)

还有歌单的显示好像又不大正常了，不过这个无所谓我可能是少数情况，歌单比较多。。。
![image](https://cloud.githubusercontent.com/assets/10568668/13596192/cb8f96a0-e54b-11e5-9346-75ae853f8365.png)

_最近也在开始做类似的项目[LER0ever/Israfil](https://github.com/LER0ever/Israfil)，欢迎建议和交流 :-)_

**Comment by cosven** [comment]
开发版已经支持 歌单内搜索
