### ISSUE TITLE
在opensuse下面怎么安装

### ISSUE THREAD

**Issue by lee88688** [cosven/FeelUOwn#120]
我的opensuse的版本是leap，我看好多包我这里都搜不到，有没有大包好的rpm直接安装也行的

**Comment by cosven** [comment]
我记得可以先添加 FZUG 源，`sudo dnf install feeluown`。README 中有写的。

如果你想用 rpm 包直接安装的话，你去搜 FZUG 源的网站，那上面也是有的。

**Comment by wp5z** [comment]
suse可以用dnf？

**Comment by lee88688** [comment]
不可以啊，但是可以用rpm包啊
