### ISSUE TITLE
是要停止开发了么？

### ISSUE THREAD

**Issue by wzdnzd** [cosven/FeelUOwn#121]

**Comment by wzdnzd** [comment]
@cosven

**Comment by cosven** [comment]
生死熟虑之后，我还是决定继续写下去。
不过我要改变下思路...

**Comment by wzdnzd** [comment]
赞，可惜我刚学了一点点python，而且还要上课，不然也能帮上点忙啊

**Comment by cosven** [comment]
我最近在想反正要做大改动（基本要重来）
去弄个直播做 Linux 播放器玩玩 ....

**Comment by wzdnzd** [comment]
之前学python，本来都拿你的源码来看了，可惜帮不上忙啊
