### ISSUE TITLE
播放器出现错误：缺少解码器

### ISSUE THREAD

**Issue by zuoxinyu** [cosven/FeelUOwn#125]
Fedora23， 从fzug源安装。之前没有问题，可以正常播放，但是更新到最新版本后出现这个报错。
重装之后依然报错。

[ERROR] [player.py line:226] : 播放器出现错误：缺少解码器
Error: "Not Found"

**Comment by cosven** [comment]
你是不是把 gstreamer 的一些东西给卸掉了..

**Comment by zuoxinyu** [comment]
不清楚，但是Rhythmbox和其它播放器都正常。

**Comment by cosven** [comment]
可以尝试到 <https://github.com/FZUG/repo/issues> 这里反馈下。（最近并没有啥更新的，实际上）

**Comment by zuoxinyu** [comment]
OK。
