### ISSUE TITLE
Fedora 23下报错

### ISSUE THREAD

**Issue by xuhao148** [cosven/FeelUOwn#126]
通过FZUG源安装。
Traceback (most recent call last):
  File "/usr/share/feeluown/main.py", line 9, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /usr/lib64/python3.4/site-packages/PyQt5/QtCore.so: undefined symbol: _ZNK11QMetaObject10Connection18isConnected_helperEv

**Comment by cosven** [comment]
应该是你的 Qt 安装有问题。

<https://ask.fedoraproject.org/en/question/81998/using-python3-qt5-importerror-undefined-symbol/>

所以 你可以考虑 
1. 如果有多个版本 Qt5，卸载一个试试
2. 然后重新安装 PyQt5

**Comment by cosven** [comment]
另外，这个问题和软件并没有关系的，所以你可以考虑在 Fedora 社区问问
