### ISSUE TITLE
启动后可以加载歌曲信息，但是无法正常播放歌曲

### ISSUE THREAD

**Issue by HenryKamg** [cosven/FeelUOwn#128]
在kali linux环境下，网络环境是移动，无代理，可以正常登陆账号和搜索，但是无法加载歌曲和启动vlc

**Comment by HenryKamg** [comment]
请问是因为移动DNS的原因吗？但是ss代理以后还是不能正常播放歌曲

**Comment by cosven** [comment]
很有可能是 DNS 的问题。之前有个盆友也是改了 DNS 之后就可以了

另外，国外的 IP 也是不能正常访问的。

https://github.com/cosven/FeelUOwn/issues/52#issuecomment-152785478

**Comment by ragrok** [comment]
debian8.3 无法登出账号。

**Comment by HenryKamg** [comment]
改了阿里云公共DNS,　走国内IP，还是只能看到歌单，点播放没声音，进度条停在00:00

**Comment by HenryKamg** [comment]
命令行musicbox也是同样的情况，可以登录加载歌单，但是不能播放

**Comment by nicehiro** [comment]
Ubuntu16.04  遇到同样问题，不能播放

**Comment by RaymanBwaaah** [comment]
Linux Mint17.3 同样遇到无法播放（卡在0：00，曲单和封面都正常加载）的问题， 使用的是校园网。
