### ISSUE TITLE
点击切歌时会出现快进现象

### ISSUE THREAD

**Issue by lambor** [cosven/FeelUOwn#129]
如题，会快进10-15s不等，会发出类似录音带倒带的声音。我的系统为ubuntu 15.10。

**Comment by zhixiangjoy** [comment]
同15.10,也遇到这种问题了，老版本的也有这个问题

**Comment by cosven** [comment]
我自己也是 Ubuntu 15.10 但是没有这个问题 ...

**Comment by cosven** [comment]
经过一番调研，目前猜测可能是由于网络原因。

网络掉帧，或者网络不稳定都有可能导致这个问题。

**Comment by cosven** [comment]
暂时来说：可以考虑先下载歌曲，然后再听。

**Comment by cosven** [comment]
今天尝试从改了下播放逻辑，可以试试最新版，看看问题有没有改进 ～

**Comment by lambor** [comment]
好的，我试试
