### ISSUE TITLE
有几首歌不能播放

### ISSUE THREAD

**Issue by jiarenlu** [cosven/FeelUOwn#132]
在播放 `http://music.163.com/#/song?id=30798046` 这首是不能播放
在终端运行 出现下列情况:

`[ERROR] [player.py line:226] : 播放器出现错误：缺少解码器`
`Error: "Not Found"`

gstreamer-plugins*  和 gstreamer1-plugins* 的依赖都已经安装了

**Comment by cosven** [comment]
还真是特例，待我研究研究...

**Comment by LER0ever** [comment]
我去研究了下这首歌，发现用网易现在的API和EncryptID算法算出来的歌曲MP3地址都是404 。。。
**但是低质量的M4A可以访问！http://m1.music.126.net/oSQY_EoaCCUlI_st1-y9Wg==/7864806673850166.m4a**
```
IsrafilCore::Plugin::Netease:: 2016/04/08 12:51:58 ID30798046
IsrafilCore::Plugin::Netease:: 2016/04/08 12:51:58 7773547208742177 :: http://m1.music.126.net/jZbOMQbfXHafi9c3K4StCw==/7773547208742177.mp3
IsrafilCore::Plugin::Netease:: 2016/04/08 12:51:58 7698780418422761 :: http://m2.music.126.net/OLfOdfkSv8yjZF3s5jpGPA==/7698780418422761.mp3
IsrafilCore::Plugin::Netease:: 2016/04/08 12:51:58 7842816441291418 :: http://m1.music.126.net/bKqWTgwn2LxvJKPjP_8DPQ==/7842816441291418.mp3
```
这是HMusic, MMusic, LMusic的MP3地址，显然都没法播放。
**现在貌似已经有很多歌通过旧版API访问不了了。**

**Comment by xrlin** [comment]
我也遇到了这个错误，现在好多日文歌曲都播放不了了。

**Comment by cosven** [comment]
最新版已解决这个问题。
