### ISSUE TITLE
Archlinux+Gnome3 用户栏中没有FeelUown菜单

### ISSUE THREAD

**Issue by hanzeil** [cosven/FeelUOwn#134]
![2016-04-13 10-57-45](https://cloud.githubusercontent.com/assets/4346863/14481542/9a5afd2c-0166-11e6-8547-c3de0be3657b.png)
并没有ScreenShot中的菜单栏

**Comment by cosven** [comment]
你要给 Gnome3 安装一个叫做 什么player 的插件。具体什么名字我也忘记了，你可以去官网上搜一下

**Comment by imzf** [comment]
方法一
安装 [Media player indicator](https://extensions.gnome.org/extension/55/media-player-indicator/)，缺点就是封面总是有延迟，不同步
方法二
更新至 gnome 3.20,不足是没法控制速度时间
![2016-04-10 19-42-11](https://cloud.githubusercontent.com/assets/3401994/14580329/c3f4d566-03fc-11e6-90e8-c96fd6d39e43.png)

**Comment by hanzeil** [comment]
谢谢！
