### ISSUE TITLE
archlinux下，有部分的歌曲无法播放

### ISSUE THREAD

**Issue by zzm317** [cosven/FeelUOwn#136]
之前认为是因为我挂了香港代理，后面发现似乎不是这样。。。。
比如我这边nyan cat，on my sheep这种都听不了
会不会是我解码器安装不全呢？

**Comment by zzm317** [comment]
奇怪的是v家的歌很多能听（<--__<--

**Comment by BruceZhang1993** [comment]
感觉是不是收费的歌 有的播放不了~~

**Comment by zzm317** [comment]
咱是会员，而且手机上实验可听，网页实验可听

**Comment by cosven** [comment]
API 原因，开发版中已经在修复。
