### ISSUE TITLE
点击MV按钮无反应

### ISSUE THREAD

**Issue by abcfy2** [cosven/FeelUOwn#138]
点击MV按钮没反应，终端也没有任何报错。
我记得以前版本点击后会弹出VLC播放器的，最新版本怎么没这功能了？

**Comment by BruceZhang1993** [comment]
我这里必须先点播放歌曲，然后点正在播放上的MV按钮才可以。。。

**Comment by abcfy2** [comment]
我这边情况还不一样，即使播放中点MV一样没反应
