### ISSUE TITLE
部分歌曲不能播放，报错：缺少解码器

### ISSUE THREAD

**Issue by Felamande** [cosven/FeelUOwn#139]
log输出：
[ERROR] [player.py line:235] : 播放器出现错误：缺少解码器
Error: "Not Found"

readme里的包都已经装全
少部分可以，其他大部分歌都无法播放，比如我的歌单从第三首歌开始(http://music.163.com/#/my/m/music/playlist?id=19862624)

**Comment by cosven** [comment]
根据现有API得到的音乐地址，确实有部分是404

我这两天试试其他的方法

**Comment by cosven** [comment]
确实哦，大部分非 中文、英文 歌曲都不能播放了

**Comment by wu-nerd** [comment]
旧API获取的内容部分404了，需要替换成新API：
action: http://music.163.com/weapi/song/enhance/player/url?csrf_token=
data = {
            "ids": sids,
            "br": bit_rate,
            "csrf_token": csrf
}

代码：
https://github.com/wu-nerd/dmusic-plugin-NeteaseCloudMusic/blob/master/neteasecloudmusic/netease_api.py#L218

**Comment by kigawas** [comment]
可以参考CLI版客户端的解决方案：
https://github.com/darknessomi/musicbox/commit/34c9716c2bdb0bb803d4c5936d174e24ba2dd821

**Comment by cosven** [comment]
搜噶，前几天看了加密部分的代码，有几个地方没懂，于是搁下了，今天仔细研究了下，算是勉强懂了。
还做了个笔记...... <https://github.com/cosven/cosven.github.io/issues/30>

在新的开发版（dev分支）中，打算直接使用 新的 API 了。老版，可能就先不更新了。
