### ISSUE TITLE
ubuntu 16.04 64位 安装报错

### ISSUE THREAD

**Issue by ker0491** [cosven/FeelUOwn#141]
The directory '/home/k/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/k/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting quamash==0.5.3 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement quamash==0.5.3 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for quamash==0.5.3 (from -r requirements.txt (line 1))

**Comment by cosven** [comment]
这不是说 **Please check the permissions and owner of that directory** 尝试用 sudo 试试

**Comment by ker0491** [comment]
用的就是 sudo

**Comment by wu-nerd** [comment]
可能是不需要sudo

**Comment by Ruiming** [comment]
单独执行pip3 install quamash
然后从requirements.txt移除quamash
重新运行安装程序就可以了
