### ISSUE TITLE
在deepin在播放音乐正常，但是登录后点击用户头像时，歌单数据重复

### ISSUE THREAD

**Issue by myttyy** [cosven/FeelUOwn#145]
在deepin在播放音乐正常，但是登录后点击用户头像时，歌单数据重复
![20160509164421](https://cloud.githubusercontent.com/assets/19262805/15108001/f62aa432-1605-11e6-9ceb-57e9bb0577de.png)

**Comment by cosven** [comment]
谢啦，今晚修复一下。

突然发现它在 Deepin下的长相 和 它在 Ubuntu 的长相差一点。
- [ ] 本来按钮的背景都是透明的，在 Deepin 下，这些按钮的背景都有了。（上一首，...，随机/循环）
- [ ] table 应该默认不要换行

**Comment by cedarice** [comment]
在ubuntu 16.04中也存在相同问题

**Comment by cosven** [comment]
新版已解决。
