### ISSUE TITLE
小游戏：猜 xiami 签名算法细节

### ISSUE THREAD

**Issue by cosven** [cosven/FeelUOwn#146]
``` json
{
    "api_key": "9ff857b2b2d001d5c17447613452beeb",
    "api_sig": "bfd597648b11281050dbabb03db789d8",
    "call_id": "1462799102.105234",
    "is_pub": "y",
    "key": "taylor swift",
    "limit": 20,
    "method": "Search.summary"
}
```

想尽办法，由上面的 json 得到 api_sig 的值，也就是 bfd597648b11281050dbabb03db789d8
如果破解出来了，那就可以很简单的写个xiami的插件了（虾米现在的音乐资源还不错）

一些参考资料：http://open.taobao.com/doc2/detail.htm?articleId=101617&docType=1&treeId=1

```
http get http://api.xiami.com/api/?api_key=9ff857b2b2d001d5c17447613452beeb\&api_sig\=bfd597648b11281050dbabb03db789d8\&call_id\=1462799102.105234\&is_pub\=y\&key\=taylor%20swift\&limit\=20\&method\=Search.summary
```

**Comment by LER0ever** [comment]
@cosven 建议使用www.xiami.com/web/search...的API加上凯撒方阵加密算歌曲地址，**淘宝开放API亲测特别坑！**

附上我已经写了一点的虾米API：[github.com/LER0ever/Israfil/tree/old-develop/plugins/Xiami](https://github.com/LER0ever/Israfil/tree/old-develop/plugins/Xiami)

刚好我过几天考完试也准备写虾米哈哈

**Comment by hghwng** [comment]
Android 端用的是阿里聚安全的 SDK（SecuritySignature），如果要分析整个 SDK，成本会比较高。
