### ISSUE TITLE
关于部分音乐不能播放的问题

### ISSUE THREAD

**Issue by suzj801** [cosven/FeelUOwn#147]
有些音乐不能播放debug了一下报缺少解码器，事实上是因为播放链接是404。于是我抓包看了一下，这部分请求的接口变为/eapi/song/enhance/player/url。我猜想可能这部分音乐是网盘音乐。
![20160511124342](https://cloud.githubusercontent.com/assets/5162730/15170329/6fa43072-1777-11e6-8ef7-561f61b8360d.png)
摸索着开发真难呀

**Comment by cosven** [comment]
确实，你用的旧版本把，新版本已经使用了新的API、
