### ISSUE TITLE
在ubuntu16.04以及Deepin15.1.1（64位）下安装遇到的问题

### ISSUE THREAD

**Issue by chunws** [cosven/FeelUOwn#149]
执行install.sh后显示以下：

Download and install software dependency.
Download and install python dependency
Generate icon, then you can see app in apps list.
Traceback (most recent call last):
  File "./install.py", line 51, in <module>
    generate_icon()
  File "./install.py", line 44, in generate_icon
    os.remove(f_path)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/applications/FeelUOwn.desktop'
小白这方面基础较差，希望得到指导。

**Comment by cosven** [comment]
这是程序的  BUG。刚修复了这个问题。

你重新执行 update.sh 把。

**Comment by chunws** [comment]
出现了新的内容
Download and install software dependency.
Download and install python dependency
Generate icon, then you can see app in apps list.
Traceback (most recent call last):
  File "./install.py", line 52, in <module>
    generate_icon()
  File "./install.py", line 46, in generate_icon
    with open(f_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/applications/FeelUOwn.desktop'

在执行install.sh之前，我也按照readme.md中的方法执行了命令，在执行
sudo pip3 install -r requirements.txt  
后，显示如下内容
Requirement already satisfied (use --upgrade to upgrade): quamash==0.5.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
和这个有关吗，如果有关，请问该怎么操作？谢谢。

**Comment by chunws** [comment]
退回v8.0a后可在Deepin15.1.1_64位版本运行，执行update.sh升至9.0后无法运行。
目前来看，对于新手用户，8.0a版本还是不错的。不能播放日语个很是遗憾，但是请
继续努力。

**Comment by cosven** [comment]
我觉得你的系统比较奇怪。

你确定在 Ubuntu 16.04 和 Deepin 上都不能安装么。
我在 15.04 的新系统上安装没有问题。

我看你上面的命令执行基本都没有问题。
只是最后生成桌面图标失败了。

我又更新了安装部分的代码，如果你有兴趣，可以继续尝试下。

**Comment by cposture** [comment]
刚刚执行 update.sh 后运行有问题，但是重新拷贝一下 升级后的desktop文件就好了。
`~/software/FeelUOwn$ sudo cp feeluown.desktop ~/.local/share/applications/`

**Comment by chunws** [comment]
今天又试了试。
在Deepin15.1.1中安装可完美运行。

在刚装上的中文版的ubuntu16.04 里看来，执行后
要补充依赖库pycrypto，不然会出现	ker0491 这个
用户出现的问题。
