### ISSUE TITLE
请问是不是不能输入中文搜歌？

### ISSUE THREAD

**Issue by why19961220** [cosven/FeelUOwn#152]
而且也没有旧版的私人FM、歌曲推荐等功能...

**Comment by BruceZhang1993** [comment]
尝试安装对应输入法的qt5模块吧

**Comment by myttyy** [comment]
新版的功能未完善，这些功能都会加上的，中文搜索应该是没问题的，注意安装完整：sudo apt-get install fcitx-frontend-qt5 -y  # 输入中文需要
![20160515112946](https://cloud.githubusercontent.com/assets/19262805/15271875/b459d502-1a90-11e6-8994-42c82fdaac62.png)

**Comment by Fangzzzjjj** [comment]
v8.0a 同样和搜狗输入法不兼容 ,请问怎么解决?

**Comment by cosven** [comment]
`sudo apt-get install fcitx-frontend-qt5 -y`

**Comment by CamosiWANG** [comment]
fcitx-frontend-qt5 对应的arch linux 下的包叫什么，一直没找到。
