### ISSUE TITLE
已知 bug 和修复情况，以及短期开发进展

### ISSUE THREAD

**Issue by cosven** [cosven/FeelUOwn#156]
#### 重要且紧急
- [x] 显示当前播放列表的歌曲 
- [ ] deb 打包。`不会`
- [x] 增加歌词界面
- [ ] 鼓励爱好者开发插件，提交 PR `永远重要`
- [x] 连续快速切换歌曲造成程序卡顿 
- [ ] 配置模块 
- [ ] 歌曲评论 `当前任务 🔵`
- [x] 开发 feeluown-core

#### 重要不紧急
- [x] 添加红心歌曲。`neteasemusic`
- [x] 综合虾米的音乐资源
- [ ] 新建歌单，从歌单增删歌曲 `neteasemusic` 
- [ ] 支持本地歌曲
- [x] 增加相似歌曲，今日推荐，红心电台
- [x] 作为一个包的形式加入 pypi 源
- [x] 下载功能
- [x] 远程控制
- [x] 对已经下载的歌曲进行一些标记
- [ ] 批量删除、添加、下载 #204 
#### 紧急不重要
- [ ] 用户登录之后，点击登录图标会再次重复登录
- [ ] 保存上次程序运行的状态。比如：主题、播放顺序等。
#### 不重要不紧急
- [ ] `MessageLabel` 的 show_message 方法不能在非主线程情况下被调用
- [ ] 最小化到系统托盘

**Comment by myttyy** [comment]
大赞，建议加上桌面歌词（颜色/字体大小可换，可以参考深度音乐），并且现在的程序没有退出提示（ps:反正我是经常按错的）

**Comment by cosven** [comment]
歌词，不妨尝试一下 [osd-lyrics](https://github.com/tigersoldier/osd-lyrics)
我在 Ubuntu 15.10 可以正常使用这个东西

**Comment by cosven** [comment]
折腾一下午
`相信 osd-lyrics  -> 怀疑 -> 怒看源代码 -> 怒修改代码 -> 放弃 -> 无意中发现自身问题 -> 发现osd-lyrics没有bug`
@myttyy 
osdlyrics 这个是可以用的，你需要下载 [feeluown-mpris2-plugin](https://github.com/cosven/feeluown-mpris2-plugin) 这个插件的最新版，之前的版本有一个bug，导致osdlyrics不能正确识别。

**Comment by myttyy** [comment]
哈哈哈

**Comment by GreatBigWhiteWorld** [comment]
安装那个歌词前想请问一下，那个是显示网易的歌词还是在歌词网站搜索歌词啊？

**Comment by jiayu-daemon** [comment]
给力

**Comment by dissipator** [comment]
http://m8.music.126.net
不能解析

**Comment by zhFuECL** [comment]
作者好可爱哈哈哈哈哈哈。那个deb打包

**Comment by Aexus** [comment]
网易挺良心的，出了linux的云音乐客户端

**Comment by cosven** [comment]
- [x] 对已经下载的歌曲进行一些标记
![screen shot 2016-07-09 at 00 00 55](https://cloud.githubusercontent.com/assets/4962134/16693564/49eec332-4568-11e6-87e5-4a3da40c76dc.png)

**Comment by cosven** [comment]
- [x] 加入了 虾米 的搜索 API，当网易云音乐歌曲不能播放时，自动尝试从虾米搜索该歌曲。

**Comment by cosven** [comment]
- [x] 发送播放次数信息给网易云音乐服务器
 <https://github.com/cosven/FeelUOwn/commit/cd47a16859f2229dd9a526580f0bfe58c62b5a2a>

**Comment by Problem233** [comment]
作者已经找到网易云音乐新建歌单，从歌单增删歌曲的api了吗？还是还没找到这个api所以搁置？如果已经找到了的话能不能分享一下？ ❤️

**Comment by scylhy** [comment]
作者你好，提个建议，希望能够做一个在顶部菜单栏添加一个滚动歌词的indicator。
１、平常使用会发现，顶部菜单中间会有一大部分的空白空间，这部分可以做个滚动歌词。
２、一般的屏幕歌词，会占用桌面空间，影响其他程序的使用。
已经向网易云提出建议，不知道会不会理会我呢。最近有时间
![2](https://cloud.githubusercontent.com/assets/12492939/22682101/e76116fc-ed4b-11e6-9b8f-a0e41678e8fc.png)
自己做一下这方面的工作。作者加油！

**Comment by IsoaSFlus** [comment]
@scylhy 不是所有de都有那一栏的。。。kde就没有

**Comment by cosven** [comment]
@scylhy 
这个 indicator 只在部分系统中存在，不过这个功能要实现了的话，还是挺实用的。欢迎 PR ~，可以写个插件啥的...

**Comment by scylhy** [comment]
get


来自 魅族 MX4 Pro

-------- 原始邮件 --------
发件人：cosven <notifications@github.com>
时间：周六 2月11日 05:31
收件人：cosven/FeelUOwn <FeelUOwn@noreply.github.com>
抄送：scylhy <scylhy@163.com>,Mention <mention@noreply.github.com>
主题：Re: [cosven/FeelUOwn] 已知 bug 和修复情况，以及短期开发进展 (#156)

**Comment by cosven** [comment]
为了写一个 feeluown-core 的东西，最近在造一个 **反序列化** 的轮子，不知道大家有木有兴趣参与。

<https://github.com/cosven/april>

**Comment by cosven** [comment]
现在项目进展都会在 Projects 记录
