### ISSUE TITLE
4K分辨率的情况下，所有程序本身UI字体及左侧歌单列表字体显示过小

### ISSUE THREAD

**Issue by ihacklog** [cosven/FeelUOwn#159]
4K分辨率的情况下，所有程序本身UI字体及左侧歌单列表字体显示过小
中间的主体部分列表正常。
![111](https://cloud.githubusercontent.com/assets/1055166/15273850/590652e6-1a6a-11e6-9c54-f34fe08f3389.jpg)

**Comment by cosven** [comment]
在高分屏下，你需要设置 Qt 程序的字体啥的也放大两倍。具体可以搜索 ArchLinux hidpi 的文档

解决办法：
在 `/etc/profile.d` 目录下创建一个可执行 xxx.sh 文件，把下面内容加入其中。
`export QT_DEVICE_PIXEL_RATIO=2`
然后重新注销登陆即可。

**Comment by ihacklog** [comment]
我的配置是
```
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=1
export QT_STYLE_OVERRIDE=GTK+
```
如果加上你说的：
`export QT_DEVICE_PIXEL_RATIO=2`
效果是这样的：
![222](https://cloud.githubusercontent.com/assets/1055166/15274437/eb63fb28-1a76-11e6-9549-f600c19d63ce.jpg)

**Comment by cosven** [comment]
我使用 Ubuntu 15.10，gnome 桌面，用 mac retina 屏幕又试了下，没有问题。
1. 我先设置 gnome windows scaling 为2（这个让窗口及其一些组件放大）
2. 然后再设置 gsettings set org.gnome.desktop.interface scaling-factor 2（这个会让字体也放大）
但是上面两个设置对 qt 程序貌似没有影响。

于是，我再 export QT_DEVICE_PIXEL_RATIO=2 ， qt 程序就能正确运行了。

你自己的那三个配置是用来干什么的，我不知道它们有没有影响

**Comment by ihacklog** [comment]
我的环境是ArchLinux, 用的gnome 3
1. 我跟你的设置一样
2.我跟你的设置一样
3. 我按你回复的设置了，并且去掉了我上面设置的3个环境变量。结果跟我的上一个最近的回复一样不正常。
4. 另外说下：
```
arning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use: 
    QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors. 
    QT_SCREEN_SCALE_FACTORS to set per-screen factors. 
    QT_SCALE_FACTOR to set the application global scale factor.
```

**Comment by ihacklog** [comment]
如果

**Comment by cosven** [comment]
是不是图片没有传上来？

**Comment by ihacklog** [comment]
传上来了。

**Comment by cosven** [comment]
这个看起来已经正常了吧。
- 只是 歌曲名 分成两行看起来不舒服。
- 另外，当前播放列表的一个字符太小，这个字符稍后我会换掉。

**Comment by ihacklog** [comment]
这个不正常。注意 ，我特意截取了左边的chromium 字体作为对比。左边的是正常的。而播放器的，是大了两倍的。

**Comment by ihacklog** [comment]
@cosven 非常感谢。下载了最近的更新后，现在字体正常了。
```bash
commit b590ffe8e6b8d26ccb1f5139fa06c416e53aca22
Author: Cosven <yinshaowen241@gmail.com>
Date:   Wed May 25 14:17:17 2016 +0800

    add: neteaesmusic linux version
```
更新到这个commit之后就OK啦

留下截图。（注意，现在对比 chromium的字体和 FeelUOwn 界面的字体，已经一致啦。
![2016-05-26](https://cloud.githubusercontent.com/assets/1055166/15579644/2b273236-232b-11e6-8f21-409ea82cf4e5.jpg)
