### ISSUE TITLE
崩溃情况较多

### ISSUE THREAD

**Issue by light4** [cosven/FeelUOwn#16]
估计目前没有经过完整的测试，崩溃情况较多，先解决下稳定性问题吧。

**Comment by cosven** [comment]
恩 ，的确，一些网络操作，之前本来谢了一个函数来处理错误情况的，然后发现那个写的有问题，然后就删掉了。然后当网络出现问题的时候，就会出错。不过我以为出错不会让程序崩溃，所以就先搁置了问题。。。

**Comment by cosven** [comment]
我想在用 `asyncio` 这个库对程序重构的时候，把 网络部分 完善下。

**Comment by cosven** [comment]
这两天对程序进行一定的优化
在性能和稳定性上应该都有提高。
