### ISSUE TITLE
Ubuntu 16.04 不能播放，显示 DECODE FAILED

### ISSUE THREAD

**Issue by cedarice** [cosven/FeelUOwn#160]
安装最新版，在播放的时候，左下角出现DECODE FAILED错误，不能播放音乐。
系统是Ubuntu 16.04
![2016-05-17 08-23-10](https://cloud.githubusercontent.com/assets/12607063/15307752/d5beb626-1c08-11e6-9fce-dc5ca82e932d.png)

**Comment by cosven** [comment]
是每首歌都不能播放么
应该依赖没有安装完整把？

**Comment by cosven** [comment]
另外还有可能是你的网络有问题。
比如说：你的网络需要验证。

**Comment by cedarice** [comment]
网络是正常的，在安装依赖的时候有gstreamer0.10-plugins-bad这个安装不了，提示没有可安装候选

**Comment by cosven** [comment]
没有相似的安装包么? 你用的是 Ubuntu 16.04 么，这个系统我还没试过，所以一些细节我也不太确定

**Comment by cosven** [comment]
比如 gstreamer0.10-plugins-bad:amd64 这样的。
或者你试试 gsteamer 开头的包有哪些
```
sudo apt-cache search gstreamer
sudo apt-cache search gstreamer0.10
```

**Comment by cedarice** [comment]
我用的ubuntu 16.04，现在已经没有gstreamer0.10-plugins-bad包了。
安装时的提示信息如下：
没有可用的软件包 gstreamer0.10-plugins-bad，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到
然而下列软件包会取代它：
  gstreamer0.10-plugins-ugly gstreamer0.10-plugins-good:i386
  gstreamer0.10-plugins-base:i386 gstreamer0.10-plugins-good
  gstreamer0.10-plugins-base

运行sudo apt-cache search gstreamer0.10，结果如下
gstreamer0.10-alsa - GStreamer plugin for ALSA
gstreamer0.10-doc - GStreamer core documentation and manuals
gstreamer0.10-gconf - GStreamer plugin for getting the sink/source information from GConf
gstreamer0.10-gnomevfs - GStreamer plugin for GnomeVFS
gstreamer0.10-plugins-base - GStreamer plugins from the "base" set
gstreamer0.10-plugins-base-apps - GStreamer helper programs from the "base" set
gstreamer0.10-plugins-base-dbg - GStreamer plugins from the "base" set
gstreamer0.10-plugins-base-doc - GStreamer documentation for plugins from the "base" set
gstreamer0.10-plugins-good - GStreamer plugins from the "good" set
gstreamer0.10-plugins-good-dbg - GStreamer plugins from the "good" set
gstreamer0.10-plugins-good-doc - GStreamer documentation for plugins from the "good" set
gstreamer0.10-pulseaudio - GStreamer plugin for PulseAudio
gstreamer0.10-tools - Tools for use with GStreamer
gstreamer0.10-x - GStreamer plugins for X11 and Pango
libgstreamer0.10-0 - Core GStreamer libraries and elements
libgstreamer0.10-0-dbg - Core GStreamer libraries and elements
libgstreamer0.10-dev - GStreamer core development files
gstreamer0.10-nice - ICE library (GStreamer 0.10 plugin)
gstreamer0.10-qapt - transitional dummy package
libreoffice - office productivity suite (metapackage)
gstreamer0.10-plugins-ugly - GStreamer plugins from the "ugly" set

**Comment by cosven** [comment]
要不你试试 安装1.0的试试
`sudo apt-get install gstreamer0.10-plugins-good gstreamer0.10-plugins-bad gstreamer0.10-plugins-ugly -y   # 系统依赖
`
把这些 0.10 换成 1.0

另外，你的Qt版本是多少？ `qmake -v`

**Comment by cosven** [comment]
我下午有时间 装个 16.04 试试，不然没办法 给个肯定的答案...

**Comment by cedarice** [comment]
刚刚解决了，将install.py中的几个gstreamer版本改为1.0即可
![image](https://cloud.githubusercontent.com/assets/12607063/15309806/ab917082-1c1c-11e6-9924-2ce3635112ae.png)

**Comment by cosven** [comment]
赞 :+1:

**Comment by cedarice** [comment]
看来对于ubuntu16.04，需要gstreamer1.0版本的
