### ISSUE TITLE
开发版播放部分歌曲还是出现直接崩溃的情况，原因不明

### ISSUE THREAD

**Issue by BruceZhang1993** [cosven/FeelUOwn#161]
[INFO] [api.py line:59] : method=POST url=http://music.163.com/weapi/song/enhance/player/url
↓↓↓LOG↓↓↓↓
[INFO] [connectionpool.py line:213] : Starting new HTTP connection (1): music.163.com
[DEBUG] [connectionpool.py line:395] : "POST /weapi/song/enhance/player/url HTTP/1.1" 200 None
[DEBUG] [player.py line:153] : start to play song: 404184381, 道听涂说, http://m8.music.126.net/20160517204955/71bdcbf4e88f7b31b73379efc1d32bef/ymusic/decd/faf3/6284/f811996858e6645c5c1f7220846033ad.mp3
[INFO] [connectionpool.py line:213] : Starting new HTTP connection (1): p4.music.126.net
[DEBUG] [connectionpool.py line:395] : "GET /3mhPIDxBJMxYo5yokzLOdQ==/1415071466724659.jpg HTTP/1.1" 200 994040
[DEBUG] [ui.py line:663] : current player media state 2
The X11 connection broke (error 4). Did the X11 server die?

**Comment by cosven** [comment]
我知道 播放 薛之谦 的 演员 这首歌会崩溃，其他暂时还没碰到....
之前貌似也遇到一次这个问题，但是出现的很少，我暂时也没去管他...
之后可能花点精力研究下。

**Comment by BruceZhang1993** [comment]
@cosven 好的，既然都是中文歌，也许从字符编码上考虑了

**Comment by BruceZhang1993** [comment]
@cosven 稍稍 debug 了一下， 这些歌曲的专辑图片比其他歌曲要大，达到 2000x2000 以上

应该是专辑图片的问题了～

**Comment by cosven** [comment]
恩，非常有可能。
如果不加载图片的话，就不会崩溃。

**Comment by BruceZhang1993** [comment]
最新的 commits 似乎已解决～ Well done

**Comment by cosven** [comment]
381452eb4d1072abf38d28465049f4cca9e79276

恩，这个 commit 使用比较的不那么优雅的方法， 貌似暂时解决了这个问题。
