### ISSUE TITLE
小白安装问题

### ISSUE THREAD

**Issue by zhang19960118** [cosven/FeelUOwn#164]
You should install these packages by yourself, as your linux may not a debian distribution

0 :  python3-pyqt5
1 :  python3-pyqt5.qtmultimedia
2 :  libqt5multimedia5-plugins
3 :  fcitx-frontend-qt5
4 :  gstreamer0.10-plugins-good
5 :  gstreamer0.10-plugins-bad
6 :  gstreamer0.10-plugins-ugly

package name may be different among different systems

**Comment by cosven** [comment]
就是手动安装一下这些包。
因为你的系统不是 Debian 系。

你是啥系统？

**Comment by zhang19960118** [comment]
在此打扰你了 我是linux mint 17.3

**Comment by zhang19960118** [comment]
我是python 2.7请问是不是要先升到python 3

**Comment by zhang19960118** [comment]
我现在是git clone下来 make run运行的0.0

**Comment by cosven** [comment]
如果只有 python2 的话，肯定需要升级的。
另外，如果是 linuxmint 的话，直接 `sudo apt-get install ` 那些包就可以了。
比如：
```
sudo apt-get install python3-pyqt5  python3-pyqt5.qtmultimedia ...
```

**Comment by zhang19960118** [comment]
好的

**Comment by zhang19960118** [comment]
感谢楼主的开源奉献精神！！！！

**Comment by laijianjia** [comment]
hi cosven,
there are same problems with me in the fedora system, i try the command **apt-get** but it fails, here is the system msg, would you help me solve it?

> [root@localhost laijianjia]# apt-get install python3-pyqt5
> Reading Package Lists... Done
> Building Dependency Tree... Done
> E: Couldn't find package python3-pyqt5
