### ISSUE TITLE
pip3 install feeluown 报错

### ISSUE THREAD

**Issue by zhang19960118** [cosven/FeelUOwn#166]
Requirement already satisfied (use --upgrade to upgrade): feeluown in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): quamash>=0.5.5 in /usr/local/lib/python3.4/dist-packages (from feeluown)
Cleaning up...

**Comment by cosven** [comment]
这是正常情况啊，不能运行么

**Comment by cosven** [comment]
要升级的话，用　`pip3 install feeluown --upgrade`

**Comment by zhang19960118** [comment]
懂了 我以为是报错了 原来是正常的  已经正常安装了 谢谢作者！！！
