### ISSUE TITLE
新版本几点看法

### ISSUE THREAD

**Issue by wangxian0718** [cosven/FeelUOwn#167]
纯属自己用完新版本之后的看法，由于本人是用archlinux，所以不知道其他linux系统是不是这种情况。
感觉新版本界面UI很好看，支持主题切换，很想我们linux下的风格，这个很喜欢，但是设置完之后重新打开之后主题又恢复到之前的，这点有点不方便，还有登录问题，每次进入都要点击登录这也有点不太习惯。不过这次整体感觉比较好，我说的都是小问题，不影响使用，就是有点不方便，希望可以改进下。希望越做越好，看好作者哦。

**Comment by BruceZhang1993** [comment]
@wangxian0718 暂时可在 feeluown/consts.py 文件中修改默认主题～

**Comment by wangxian0718** [comment]
好的，谢谢！

**Comment by cosven** [comment]
恩，确实许多细节需要完善。不过登陆框之用到一次，所以就没管他了。
保存上一次程序运行时候的主题，用于下次启动，这个功能已经在 TODO 列表中了，之后会去完成。
我就先关闭这个 ISSUE 了，如果有需要，可以 reopen.
