### ISSUE TITLE
feeluown-install-dev：未找到命令

### ISSUE THREAD

**Issue by adminzhou** [cosven/FeelUOwn#170]
这是什么原因。有没有详细安装的说明呢

**Comment by cosven** [comment]
重新进入一下命令行？

**Comment by adminzhou** [comment]
不行的。我就是按照你的安装步奏来的

**Comment by adminzhou** [comment]
我先是下载了ZIP包。然后提取，然后用命令行进行安装。可是不行

**Comment by cosven** [comment]
你是用 ·pip3 install feeluown· 这样安装的么？

**Comment by adminzhou** [comment]
我下载了整个代码呀。然后sudo apt-get install python3-pip ——》[sudo] qy 的密码： 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python3-pip 已经是最新版 (8.1.1-2)。
下列软件包是自动安装的并且现在不需要了：
  lib32ncurses5 lib32tinfo5 lib32z1 libatk1.0-0:i386 libcairo2:i386
  libdatrie1:i386 libgdk-pixbuf2.0-0:i386 libgraphite2-3:i386 libgtk2.0-0:i386
  libharfbuzz0b:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386
  libpangoft2-1.0-0:i386 libpixman-1-0:i386 libthai0:i386 libxcb-render0:i386
  libxcb-shm0:i386 xserver-xorg-legacy
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 6 个软件包未被升级。
qy@qy-CN15S:~/FeelUOwn-master/feeluown$ 

——》pip3 install feeluown   
 qy@qy-CN15S:~/FeelUOwn-master/feeluown$ pip3 install feeluown
Collecting feeluown
Collecting quamash>=0.5.5 (from feeluown)
  Using cached Quamash-0.5.5-py3-none-any.whl
Collecting pycrypto (from feeluown)
Installing collected packages: quamash, pycrypto, feeluown
Successfully installed feeluown-1.0.3.3 pycrypto-2.6.1 quamash-0.5.5
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
————》feeluown-install-dev 
qy@qy-CN15S:~/FeelUOwn-master/feeluown$ feeluown-install-dev 
feeluown-install-dev：未找到命令

**Comment by adminzhou** [comment]
我的系统是 ubuntu 16.04 LTS

**Comment by adminzhou** [comment]
你好 ，你还在妈

**Comment by adminzhou** [comment]
你好 ，你还在吗

**Comment by cosven** [comment]
`sudo pip3 install feeluown` 试试。

不行的话说明你的系统环境变量或许有点问题。检查你的 $PATH 设置

如果都没问题：请运行 `ls /usr/local/bin/` ，把输出贴上来。

**Comment by adminzhou** [comment]
qy@qy-CN15S:~$ ls /usr/local/bin/
keyring  pip  pip2  pip2.7
qy@qy-CN15S:~$

**Comment by adminzhou** [comment]
`qy@qy-CN15S:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/qy/jdk1.7.0_79/bin
`

**Comment by adminzhou** [comment]
`sudo pip3 install feeluown`这个命令出现如下的

The directory '/home/qy/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/qy/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): feeluown in ./.local/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): quamash>=0.5.5 in ./.local/lib/python3.5/site-packages (from feeluown)
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by cosven** [comment]
现在能找到命令了么？

如果不能话：我也只能提供一个 hack 的方法。

`python3 /usr/local/lib/python3.4/dist-packages/feeluown/install.py`

**Comment by adminzhou** [comment]
`python3: can't open file '/usr/local/lib/python3.5/dist-packages/feeluown/install.py': [Errno 2] No such file or directory
`

**Comment by adminzhou** [comment]
我已经经历绝望了

**Comment by adminzhou** [comment]
`qy@qy-CN15S:/usr/local/lib/python3.5/dist-packages$ ls
keyring  keyring-9.0.dist-info
qy@qy-CN15S:/usr/local/lib/python3.5/dist-packages$ 
`

**Comment by cosven** [comment]
是 3.4 ， 不是 3.5
遇到这种奇怪的问题，确实比较烦...

**Comment by rickyfw** [comment]
遇到了同样的问题 ubuntu 16.04 lts

**Comment by cosven** [comment]
好，今天我装个虚拟机测试一下。

**Comment by cosven** [comment]
```
sudo -H pip3 install feeluown
```
就可以了 ，刚装的虚拟机测试的。

**Comment by cosven** [comment]
748d65fbfbfe26fc0a50f2745240a5115db3a17e
