### ISSUE TITLE
能否提供一个详细的依赖列表？

### ISSUE THREAD

**Issue by wenLiangcan** [cosven/FeelUOwn#171]
我维护着一个 Arch Linux 的 package，目前通过 `setup.py`，`feeluown/install.py` 推测有哪些依赖，如果作者能提供一个完整的依赖列表（比如在 README 里写一下？）会方便很多。

另外还发现，在 `feeluown/request.py` 和 `feeluown/neteasemusic/api.py` 是使用了 `Requests` 的，可是在前述的两个文件里都没有记录。

**Comment by cosven** [comment]
恩，好，我等下就更新一下。

**Comment by cosven** [comment]
<https://github.com/cosven/FeelUOwn#所有的依赖>

相比于之前的 `feeluown-git` 版本：应该就增加了一个 `pycrypto` 的python库。

**Comment by cosven** [comment]
requests 这个库是我自己忘记了，然后大家用的时候也没发现，然后它就被遗漏了。

**Comment by wenLiangcan** [comment]
非常感谢。
