### ISSUE TITLE
最小化到系统托盘

### ISSUE THREAD

**Issue by wenLiangcan** [cosven/FeelUOwn#172]
不知能否实现这个功能？

**Comment by cosven** [comment]
之后会考虑开发，近期个人时间较紧，基本不会添加什么功能。
我把它加入 以后的开发列表  #156 

另外，针对系统托盘这个功能：以前有过调研，很多新的 Linux 发行版支持 Indicator，而 Qt 的 QSystemTrayIcon 和 Indicator 不是完全兼容。所以这个功能做起来可能也要花点功夫。
