### ISSUE TITLE
"上一首"或"下一首"功能的逻辑问题

### ISSUE THREAD

**Issue by hwding** [cosven/FeelUOwn#173]
在播放歌单里的歌时, 点击"上一首"或"下一首"会在底部打印"O: preparing to play [SongName]"  
但是这个[SongName]只会在打开程序后**播放过**的播放列表徘徊, 并不能进入**未播放过**的新曲目  
而且正常播放的时候也是如此, 不能自动播放下一首**未播放过**的新曲目
不知道是我的配置问题还是其他  
OS: openSuSE

**Comment by BruceZhang1993** [comment]
目前好像播放的逻辑是只把一个曲目加入播放列表 而不是整个歌单吧

**Comment by hwding** [comment]
就是说, 如果要遍历整个歌单的话, 需要**全部**点一遍?  
这样的逻辑是否存在问题?  
@BruceZhang1993

**Comment by cosven** [comment]
不是有个 播放全部么？@hwding

**Comment by hwding** [comment]
是指"全部循环"吗?

**Comment by cosven** [comment]
搜索框的左边不是有个 小的三角形 么，播放当前歌单全部歌曲。
（其实我没大看懂 具体在讨论什么问题）

**Comment by hwding** [comment]
看见了, 抱歉我没注意...
