### ISSUE TITLE
顶部信息显示不全的问题

### ISSUE THREAD

**Issue by hwding** [cosven/FeelUOwn#174]
![screenshot from 2016-05-22 12-57-35](https://cloud.githubusercontent.com/assets/15152879/15452353/bf906178-201e-11e6-9c7f-cf1072e0484b.png)
歌曲时长的最后一位貌似始终无法显示, 更改窗口大小也一样.

**Comment by hwding** [comment]
@cosven 作者大大救我...

**Comment by cosven** [comment]
额，系统差别。。
我在 master 分支上已经改了，不过要等下次版本更新才会push到pypi上。

**Comment by hwding** [comment]
感谢！另外希望左边列表能够resize
