### ISSUE TITLE
ImportError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [cosven/FeelUOwn#175]
Traceback (most recent call last):
  File "/usr/bin/feeluown", line 7, in <module>
    from feeluown.__main__ import main
  File "/usr/lib/python3.5/site-packages/feeluown/__main__.py", line 9, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named 'PyQt5'

安装完运行出错啊。opensuse Tumbleweed系统.PyQt5是在python-qt5-utils 这个包里。

python-qt5-utils - Common files for PyQt5 for python2 and python3

/usr/share/sip/PyQt5
/usr/share/sip/PyQt5/Qt
/usr/share/sip/PyQt5/Qt/Qtmod.sip
/usr/share/sip/PyQt5/QtBluetooth
/usr/share/sip/PyQt5/QtBluetooth/QtBluetoothmod.sip
/usr/share/sip/PyQt5/QtBluetooth/qbluetooth.sip
/usr/share/sip/PyQt5/QtBluetooth/qbluetoothaddress.sip
/usr/share/sip/PyQt5/QtBluetooth/qbluetoothdevicediscoveryagent.sip
......

**Comment by cosven** [comment]
首先：看你这个错误信息，可以知道问题是 python3.5 找不到 PyQt5.

所以我感觉有两种可能：
1. Pyqt5 安装失败了，或者安装不正确
2. pyqt5 安装到其他的python版本了，比如说：python3.4

**Comment by BruceZhang1993** [comment]
应该装 python3-qt5 包的吧～

**Comment by GreatBigWhiteWorld** [comment]
感谢楼上，是应该装你说的那个包。我是搜索pyqt5结果suse推荐给我了另一个包。

最近linux系统坏了几次，我好久没用feeluown了，发现现在更帅啦！

另外想悄悄的问下，为什么有的官网听不了显示下架的你的播放器能听？！

**Comment by GreatBigWhiteWorld** [comment]
我发现了一个秘密，不知道作者知道不。就是说已经被下架的曲子，如果在你自建的歌单中，就还可以播放。但如果是你搜索一首（也就是不在你的歌单里的），你点击后程序会崩溃退出。崩溃信息：
Traceback (most recent call last):
  File "./feeluown/plugins/neteasemusic/nem.py", line 157, in play_song
    self._app.player.play(song)
  File "/usr/lib/python3.5/site-packages/feeluown/player.py", line 172, in play
    self._play(music_model)
  File "/usr/lib/python3.5/site-packages/feeluown/player.py", line 158, in _play
    % music_model.title)
ValueError: unsupported format character '?' (0x4e0d) at index 2
Aborted (core dumped)

**Comment by BruceZhang1993** [comment]
@GreatBigWhiteWorld 同发现了，不知神马问题

**Comment by GreatBigWhiteWorld** [comment]
@BruceZhang1993 我觉得这不叫问题，而是机遇。。

**Comment by GreatBigWhiteWorld** [comment]
另外，不知道作者能不能加上这两个依赖描述：gcc，python-dev。我两次安装都谷歌了一阵子错误代码发现缺少这俩个包的。

**Comment by cosven** [comment]
我觉得这两个包应该是 其它包的依赖把？
对于那个 _秘密_ 的问题，我发现了 bug 的地方... 我漏写了一个字符
48a203792943333f7691ede689cd602ffd074caf

**Comment by cosven** [comment]
不过，的确，你把那些下架的歌曲加入自己的歌单之后，就能播放了。（这个之前我还注意到 惊讶脸）

**Comment by GreatBigWhiteWorld** [comment]
哦哦。。。才知道可以拖动。okok。好了问题解决赶紧关闭啦！
