### ISSUE TITLE
Ubuntu GNOME 14.04 LTS　显示登陆成功后没有歌单出现

### ISSUE THREAD

**Issue by ShawnLinLoveLife** [cosven/FeelUOwn#177]

**Comment by cosven** [comment]
再次点击一下试试？

**Comment by ShawnLinLoveLife** [comment]
[INFO] [nem save_user_pw 100] : save username and password to /home/shawn/.FeelUOwn/data/nem_user_pw.json
Traceback (most recent call last):
  File "./feeluown/plugins/neteasemusic/nem.py", line 133, in login
    self.user = NUserModel.create(data)
  File "./feeluown/plugins/neteasemusic/model.py", line 350, in create
    img = user_data['profile']['avatarUrl']
KeyError: 'profile'

**Comment by cosven** [comment]
你需要在这里完善一下基本信息: http://music.163.com/#/user/update

**Comment by cosven** [comment]
然后再登陆 就可以了。

**Comment by ShawnLinLoveLife** [comment]
谢谢！可以登陆了！好棒的应用！

**Comment by fozoto** [comment]
我认为是权限问题导致的,我加上sudo就有歌单,
这样启动无歌单:
qingyan@fozoto:~$ feeluown &
这样启动有歌单:
qingyan@fozoto:~$ sudo feeluown &

最后发现权限的问题
解决办法:
qingyan@fozoto:~$ sudo chmod 777 -R ./.FeelUOwn/
