### ISSUE TITLE
求API

### ISSUE THREAD

**Issue by Hadesonly** [cosven/FeelUOwn#178]
求可用的网易云音乐API

**Comment by cosven** [comment]
读 <https://github.com/cosven/FeelUOwn/blob/master/feeluown/plugins/neteasemusic/api.py> 这个文件的代码？

**Comment by AnyListen** [comment]
@cosven 现在的API已经不能播放下架和付费歌曲了，有解决方案么

**Comment by cosven** [comment]
现在的 API 不能拿到付费歌曲的 url，但是能拿到不需要付费的其他所有歌曲的url。
原来的 API 拿不到大部分 日语/俄语等 歌曲的 url，但是能拿到所有其他歌曲的url。

所以解决方案就是： 两个 API 一起用。

**Comment by AnyListen** [comment]
@cosven 例如这个曲子 http://music.163.com/#/song?id=5261103
新API是404 旧的API的mp3Url: null,

**Comment by cosven** [comment]
你需要把这首歌加入自己的某个歌单中，然后再请求，就不会是 null 了。@anyListen

**Comment by AnyListen** [comment]
@cosven 泰勒的曲子呢 同样的方案么

**Comment by cosven** [comment]
对，同样的。（这种东西最好低调 , 此处应有 奸笑 + 小心 emoji）

**Comment by AnyListen** [comment]
@cosven 先已不能将下架歌曲添加到收藏

**Comment by cosven** [comment]
你用的官方的软件么，官方的不能直接收藏。也就是说，不能直接点红心。
要右键...然后选个列表。

**Comment by AnyListen** [comment]
Windows 上无法实现 一会儿我用API试试

**Comment by cosven** [comment]
因为 红心 用的是一个单独的api，但是加入某个歌单用的是另外一个 api。

在 feeluown 中有所体现，<https://github.com/cosven/FeelUOwn/issues/175#issuecomment-220961431>。windows版本的我没用过，不是很确定。

**Comment by cosven** [comment]
我很好奇，你要用 API 干啥？

**Comment by AnyListen** [comment]
我准备实现一下动态添加歌单 解析完毕在删掉

**Comment by AnyListen** [comment]
新旧API我都已经实现了，只是想获取下架歌曲和收费歌曲的方案。前一段时间看了一些 Unblock 163 的方案，他们那种是反向代理，不可行，多谢你

**Comment by cosven** [comment]
所以你现在 在做 一个新的客户端么？
另外，我觉得 _解析完毕再删除，比较hack_，那样的话，还不如先添加到某个歌单，再删除（不过还是比较 hack）。感觉还是给用户一个提示比较好（个人想法）。

**Comment by AnyListen** [comment]
不是，我有一个自己写的Windows客户端：音乐间谍，集成了国内全部的音乐厂家，在服务器端动态解析地址的

**Comment by cosven** [comment]
搜噶，赞。
这么说 你有虾米 QQ 的API么？
我之前看过它们两个，它们的一些数据资源貌似需要解析网页，没有直接的接口？

**Comment by AnyListen** [comment]
虾米的：http://www.xiami.com/song/playlist/id/" + ids + "/type/" + type + "/cat/json
你监控一下网页版的网络请求就有了，现在虾米的320K都已经开放了

**Comment by AnyListen** [comment]
QQ的目前可以用最简单的拼接地址的方法获取到下载地址
"http://stream.qqmusic.tc.qq.com/A000" + mid + ".ape";
"http://stream.qqmusic.tc.qq.com/F000" + mid + ".flac";
"http://stream.qqmusic.tc.qq.com/" + (Convert.ToInt32(song.SongId) + 40000000) + ".ogg"
"http://stream.qqmusic.tc.qq.com/" + (Convert.ToInt32(song.SongId) + 30000000) + ".ogg"
"http://stream.qqmusic.tc.qq.com/" + (Convert.ToInt32(song.SongId) + 50000000) + ".ogg"

**Comment by AnyListen** [comment]
@cosven 非常感谢提供的 BUGS，已完美解决问题 Thank U

**Comment by cosven** [comment]
我可以`躺着`要 虾米和QQ API的源代码么....
（因为之后想加上虾米和QQ的插件...）

**Comment by AnyListen** [comment]
@cosven 提供给你两个搜索API，歌曲的地址我上面已经写好了你自己整合一下就行，完全的源代码包含的东西比较多，不好开放
虾米搜索API：
`"http://www.xiami.com/app/xiating/search-song2?key=" + key + "&uid=0&callback=xiami&page=" + page;`
QQ搜索API：
`"http://soso.music.qq.com/fcgi-bin/search_cp?aggr=0&catZhida=0&lossless=1&sem=1&w="+key+"&n="+size+"&t=0&p="+page+ "&remoteplace=sizer.yqqlist.song&g_tk=5381&loginUin=0&hostUin=0&format=jsonp&inCharset=GB2312&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0"`

**Comment by cosven** [comment]
好的，多谢啦

**Comment by AnyListen** [comment]
@cosven 对了，你可以参考一个最近新出的插件，[https://github.com/listen1/listen1_chrome_extension](url)

**Comment by cosven** [comment]
恩，之后有时间去学习学习

**Comment by LER0ever** [comment]
@cosven FeelUOwn要有虾米和QQ的插件了？期待啊。
我也来分享一下我的研究成果，希望可以帮到大神，高三狗表示研究了协议没时间开发 :(
两个虾米搜索API：
```
XiamiSongSearchURLOld = "http://www.xiami.com/web/search-songs?spm=0.0.0.0.pAhr1p&key=%s"
XiamiSongSearchURL = "http://www.xiami.com/web/search-songs?key=%s&limit=50&page=0"
```
然后虾米歌曲详情API: (不过好像是xml格式)
```
http://www.xiami.com/song/playlist/id/%d/object_name/default/object_id/0
```
楼上没有说清楚QQ的mid和sid怎么获取，我来补充一下，QQ的API里有个神奇的FString，F[2] = sid; F[20] = mid (就说到这儿吧...逃)
QQ歌词和曲图API:
```
http://music.qq.com/miniportal/static/lyric/<0>/<1>.xml
http://i.gtimg.cn/music/photo/mid_album_300/%d/%d/%d.jpg
```
@AnyListen 惊现**音乐间谍**开发者？久仰，求教酷狗API啊，我在做类似的项目[LER0ever/Israfil](https://github.com/LER0ever/Israfil)

**Comment by AnyListen** [comment]
@LER0ever 我上面写的搜索API已经包含了各种参数的，你可以看看绝对好用

`酷狗的搜索："http://ioscdn.kugou.com/api/v3/search/song?keyword="+key+"&page="+page+ "&pagesize=" + size + "&showtype=10&plat=2&version=7910&tag=1&correct=1&privilege=1&sver=5";`

`酷狗的地址解析：var url = "http://trackercdn.kugou.com/i/?key=" + FormsAuthentication.HashPasswordForStoringInConfigFile((id + "kgcloud"), "MD5") + "&cmd=4&acceptMp3=1&hash=" + id + "&pid=1";`

**Comment by LER0ever** [comment]
@AnyListen 谢谢！学习了
