### ISSUE TITLE
网易官方出了一个客户端 netease-cloud-music

### ISSUE THREAD

**Issue by catroll** [cosven/FeelUOwn#179]
Ubuntu 和国产深度 Deepin 的用户可以直接安装使用

**Comment by chunws** [comment]
现在有内存溢出bug，不如这个好用

**Comment by wzdnzd** [comment]
我用的fedora没有内存溢出，但占内存倒是真的，100多M，现在还在用feeluown。。。轻量

**Comment by chunws** [comment]
在官方反馈的地方看到有的用户在Deepin下1分钟就100%了，目前推了个修复补丁，要手动打，深度商店昨天看好像也暂时下架了。

**Comment by cosven** [comment]
我之前已经在 README 中说明了。
所以这个 ISSUE 是不是 -. - closed 掉。
