### ISSUE TITLE
建议大家之后多用英文交流 ～

### ISSUE THREAD

**Issue by cosven** [cosven/FeelUOwn#181]
使用英文交流的好处也有，短处也有。
尽管用英文有时一下子很难把问题表述清楚，但是我建议大家可以尝试。
我自己也会努力使用英文，在 commit 和 issue 中。

Use English in a project is recommended. However, some people argue that we are not very good at talking in English or we cant express our opinions clearly. We should have a try ～.

**Comment by BruceZhang1993** [comment]
why not ~ even we cannot express ourselves that clearly, but it is not really hard to guess your real opinon~~ excited !!!

**Comment by kipade** [comment]
will you take lyrc in consider?

**Comment by cosven** [comment]
Linux 上可以使用 OSD-lyrics ~
@kipade

**Comment by BruceZhang1993** [comment]
osd lyrics is really lack of online resources.
if it support xiami or netease source, it will be wonderful.

**Comment by cosven** [comment]
今时不同往日，中英文差别其实不大 ~
