### ISSUE TITLE
error msg after the command feeluown-install-dev

### ISSUE THREAD

**Issue by laijianjia** [cosven/FeelUOwn#182]
hi cosven,
my system is feodra23(64bit), i follow the steps to install but there still some problems happen, here are the error msg.

> [root@localhost laijianjia]# feeluown-install-dev
> You should install these packages by yourself, as your linux may not a debian distribution
> 
> 0 :  python3-pyqt5
> 1 :  python3-pyqt5.qtmultimedia
> 2 :  libqt5multimedia5-plugins
> 3 :  fcitx-frontend-qt5
> 4 :  gstreamer0.10-plugins-good
> 5 :  gstreamer0.10-plugins-bad
> 6 :  gstreamer0.10-plugins-ugly
> 
> package name may be different among different systems

even though i find the same issue and command apt-get install , it seems not work, would you help me solve it please?

> [root@localhost laijianjia]# apt-get install python3-pyqt5
> Reading Package Lists... Done
> Building Dependency Tree... Done
> E: Couldn't find package python3-pyqt5

**Comment by BruceZhang1993** [comment]
there's a dnf package pyqt5 for fedora.. try this or compile python3 pyqt5 from source code @laijianjia

**Comment by cosven** [comment]
maybe you should use **dnf** instead of apt-get on fedora. 

try: `dnf install python3-qt5` to install pyqt5 package.

**Comment by laijianjia** [comment]
thanks, it works
