### ISSUE TITLE
libEGL warning: DRI2: failed to authenticate 

### ISSUE THREAD

**Issue by Eyre5300** [cosven/FeelUOwn#184]

**Comment by cosven** [comment]
I don't understand what do you mean.
Where did you get this message?
Can you give some more detail?

**Comment by Eyre5300** [comment]
When you run the command "feeluown" in the terminal, before the  FeelUOwn's window popping out, the terminal will get this sentence as return.

**Comment by cosven** [comment]
Are you using Raspberry Pi?
I think this issue should be discussed in Raspberry Pi community. Maybe question like this: "Pyqt5 application not working in Raspberry Pi ?"
I also find some answers that similar to yours. <https://pi3d.github.io/html/FAQ.html#glx-dri2-not-supported-or-failed-to-authenticate>
