### ISSUE TITLE
Lyrics can not be displayed although the related plugin has been installed.

### ISSUE THREAD

**Issue by xiespringsun** [cosven/FeelUOwn#187]
I use FeelUOwn on Ubuntu kylin 14.04 LTS. 
Everything works well except that the lyrics can not be displayed,
although I have installed the lyrics-plugin feeluown-mpris2-plugin.
Who knows what's wrong?

**Comment by BruceZhang1993** [comment]
@xiespringsun 
install feeluown-mpris2-plugin and osdlyrics
run `feeluown -d` and see if mpris plugin has been loaded.
