### ISSUE TITLE
A part of api is invalide,is 403 forbidden,how i can resolve it?

### ISSUE THREAD

**Issue by huweigoodboy** [cosven/FeelUOwn#188]
Like music.163.com/api/radio/get,I had used the postman to test the api,but a part of api can't be access.
Is every api of shoudn't be encode with aes?

**Comment by cosven** [comment]
you should set cookies.

 I use osx neteasemusicdict(appver="1.2.1", os="osx") api. First, I set cookies `dict(appver="1.2.1", os="osx")`,
look for more details in [api.py](https://github.com/cosven/FeelUOwn/blob/master/feeluown/plugins/neteasemusic/api.py).

**Comment by huweigoodboy** [comment]
It's well done,thank u very much.
