### ISSUE TITLE
Is there anyway to change download location?

### ISSUE THREAD

**Issue by RedL0tus** [cosven/FeelUOwn#190]
The default download location is in `~/.FeelUOwn`. It's a little bit inconvenient.

So could you plz add a setting for changing download location.

**Comment by MingcongBai** [comment]
Or by using `xdg-user-dir` to set it automatically to the Music directory or something (by default of course).

**Comment by cosven** [comment]
Temporary, you cant custimize the download location.
However, if you just want to add these music to ~/Music dir, you can add a soft link to ~/Music.

For example, `ln -s ~/.FeelUOwn ~/Music/`, then other players can detect these songs.

**Comment by MingcongBai** [comment]
Right... Looking forward to a better solution then.

**Comment by cosven** [comment]
3.0 中会添加配置模块（哎，没想到时隔 3 年，这个问题还是存在 =。=）
