### ISSUE TITLE
How to set the default theme.

### ISSUE THREAD

**Issue by RedL0tus** [cosven/FeelUOwn#191]
For example, I want to use papirus as default theme, how can I do that.

Now I need to change it everytime before playing music.

(我已对我那糟心的英语语法绝望)

**Comment by MingcongBai** [comment]
Quite hard to tell what graphical toolkit it's actually using...

**Comment by BruceZhang1993** [comment]
@RedL0tus https://github.com/cosven/FeelUOwn/blob/master/feeluown/consts.py#L10

Just edit this line for now

**Comment by cosven** [comment]
新版本目前只有一个主题
