### ISSUE TITLE
Some  suggestions about the download function.

### ISSUE THREAD

**Issue by chunws** [cosven/FeelUOwn#193]
1.  I think we should have a list of those songs I have downloaded.
     Because I have  a lot of lists in my account,so I may could not find which song I had downloaded  easily.
2. Maybe let us decide the location of the songs on the computer in order to sort those songs.
    Or we can download songs directly to the music folder. 
    There are many solutions.And we need find one.

**Comment by cosven** [comment]
Recently, I will try to do something on issue 1. Show a tag or highlight for those songs which have been downloaded.

About issue 2, if you want to download songs to ~/Music folder. Here is a solution to do similar thing, add a soft link to ~/Music folder, like `ln -s ~/.FeelUOwn/songs ~/Music/`.
Also, I'm working on the setting module, we will be able to set the download path by a config file.

Thanks for your suggestions. ~

**Comment by cosven** [comment]
Show a tag or highlight for those songs which have been downloaded.
<https://github.com/cosven/FeelUOwn/commit/26c1f26ab138c163c805bd416433b7d5c7fd181e>
