### ISSUE TITLE
The picUrl is always null.

### ISSUE THREAD

**Issue by huweigoodboy** [cosven/FeelUOwn#196]
The interface api/search/get response null.Like this  

 {
        "id": 212233,
        "name": "千千阙歌",
        "artists": [
          {
            "id": 7225,
            "name": "陈慧娴",
            "picUrl": null,
            "alias": [],
            "albumSize": 0,
            "picId": 0,
            "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
            "img1v1": 0,
            "trans": null
          }
        ],
        "album": {
          "id": 21506,
          "name": "千千阙歌",
          "artist": {
            "id": 0,
            "name": "",
            "picUrl": null,
            "alias": [],
            "albumSize": 0,
            "picId": 0,
            "img1v1Url": "http://p3.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
            "img1v1": 0,
            "trans": null
          },
          "publishTime": 788889600000,
          "size": 16,
          "copyrightId": 5003,
          "status": 1,
          "picId": 125344325579601
        },
        "duration": 299106,
        "copyrightId": 7003,
        "status": 1,
        "alias": [],
        "rtype": 0,
        "ftype": 0,
        "mvid": 5308821,
        "fee": 0,
        "rUrl": null
      }

**Comment by cosven** [comment]
because the song information this iterface get is brief info.
If you want more details, get song detials.

**Comment by huweigoodboy** [comment]
Thank u,I has resolve it by a interface  api/search/pc which has more information.
