### ISSUE TITLE
GStreamer; Unable to pause

### ISSUE THREAD

**Issue by cnobelw** [cosven/FeelUOwn#197]
GStreamer; Unable to pause - "http://m8.music.126.net/20160723183003/aee1731012f3ccf26493fa585f88b5ec/ymusic/04da/3f2e/7d58/023d4da936e6c1555aecdb699fcfb5c1.mp3"
[DEBUG] [ui update_media_state 699] : current player media state 2
[DEBUG] [ui update_media_state 699] : current player media state 8
[ERROR] [player on_error_occured 240] : 网络出现错误：不能正确解析资源
Error: "“http”未实现 URI 处理器。"
Anyone has this question? I need help, thank you!

**Comment by cosven** [comment]
其他功能正常么？
如果其他功能都不正常，那就应该是 gstreamer 库安装不完整？

**Comment by shockwavemoto** [comment]
> GStreamer; Unable to pause - "http://m8.music.126.net/20160723183003/aee1731012f3ccf26493fa585f88b5ec/ymusic/04da/3f2e/7d58/023d4da936e6c1555aecdb699fcfb5c1.mp3"
[DEBUG] [ui update_media_state 699] : current player media state 2
[DEBUG] [ui update_media_state 699] : current player media state 8
[ERROR] [player on_error_occured 240] : 网络出现错误：不能正确解析资源
Error: "“http”未实现 URI 处理器。"
Anyone has this question? I need help, thank you!

did you try updating the gstreamer plugin. Which system are you working on?

**Comment by cosven** [comment]
I used to testing it on ubuntu 14.04 ~ ubuntu 16.04.
Have you installed all the gstreamer depencies ~
