### ISSUE TITLE
How to remove the FeelUOwn?

### ISSUE THREAD

**Issue by DrXie** [cosven/FeelUOwn#198]
i think the newest version is not stable, but i don't know how to remove it

**Comment by cosven** [comment]
Do you mean uninstall or downgrade ?
If you want uninstall, you can find a solution in these issues.
if you want to downgrade, you can use pip to install the specific version.

**Comment by DrXie** [comment]
@cosven thanks a lot. i already solved this issue, now i using v0.8a, and i hope next release will be more stable.

**Comment by DrXie** [comment]
by the way, could you tell me how to download music? i can't find anything in /.FeelUOwn/Music. is that just play the song and will be download or click some button？

**Comment by cosven** [comment]
only the latest several version can download song.
If you are using v0.8 , you may not download songs.
As a whole, I recommend the latest version, which will be more stable ~
