### ISSUE TITLE
建议做本地cache

### ISSUE THREAD

**Issue by ArkBriar** [cosven/FeelUOwn#2]
如题，现状是每次登陆后大约有10s在加载曲目绘制ui(主要是我这种歌单一大堆的人，图片太多肯定有这问题
建议如下：
1. 退出时本地保存数据结构
2. 开启时读取本地cache，快速绘制
3. 异步网络通信
4. 通信完成后更新数据结构，我觉得这里可以直接舍弃原来的数据，而不是在原来的数据上修改

因为大部分人同时只会关注一个页面，所以我认为感官上数据更新带来的差别感不会太明显

**Comment by cosven** [comment]
恩， 之后打算对音乐文件 和 音乐的列表都进行缓存。
不过在音乐文件的缓存方面，目前还没有想到 **好的实现的思路**

近期可能没有足够的时间来进行这些工作，之后肯定是要做这些工作的。
另外，如果你有兴趣，我们可以一起合作来进行一些开发 ~ 
也欢迎各种反馈，建议 或者直接提交 PR ~

**Comment by AkemiHomura** [comment]
谢邀！
不过我并不精通python，合作开发可能会拖你后腿;
暑假计划开发维护一个c++版本(主要也是因为linux平台下没有客户端临时起意)，所以近期关注的比较多;
我会帮助作者君测试反馈各种问题的，还请多多指教

**Comment by cosven** [comment]
C++ 版本指的是？也是网易云音乐这个么。

**Comment by AkemiHomura** [comment]
对，我是在调研api的时候找到你这个项目的，当时计划就是用qt开发一个简易云音乐
然而最近一直忙就一直没开始动工，所以趁暑假有时间赶紧动起来
这两天也是忙于老板那边的事，不过一周内应该就会开始搭框架了

**Comment by cosven** [comment]
Soga, 其实我有一个想法就是：关于“网易云音乐”这个品台已经有几个类似的"For Linux"项目了，我觉得可以考虑下虾米和QQ音乐（个人感觉）

**Comment by AkemiHomura** [comment]
嗯，我感觉很不错，因为网易上面有时候资源也不全，正好做成用户端的资源整合;
随便查了下，虾米的api阿里倒是开放了不少
[虾米(]http://open.taobao.com/api/api_cat_detail.htm?spm=0.0.0.0.9IfYaC&cat_id=20625&category_id=102)
qq音乐可能不太好搞，因为腾讯对开源的态度在我眼里不是太好，而据我所知qplay的api也仅开放给被认证的机构，强行解析api倒是没什么问题，就怕惹上麻烦

**Comment by htfy96** [comment]
同意，有2000+歌曲在同一歌单里导致每次启动都有接近30秒的时间假死

**Comment by cosven** [comment]
2000+..... 确实是会卡死，恩，今天已经找到缓存的解决办法了，接下来两个星期应该会主攻这件事。

**Comment by cosven** [comment]
做了下歌单的缓存 ，目前刷新策略还没完善，不过可以通过手动刷新（右键歌单，刷新）。

https://github.com/cosven/FeelUOwn/commit/3e515325e60599d8d4ccdf2b74ea71482461c4a4
