### ISSUE TITLE
有没有和我的情况一样,不能登录,不能输入中文 

### ISSUE THREAD

**Issue by oahzuw** [cosven/FeelUOwn#20]
不能登录,不能输入中文 ,不过可以用拼音搜歌听,已经很不错了, ubuntu14.04 输入法fcitx

**Comment by cosven** [comment]
不能登录么？
它有提示什么信息么？比如说密码错误之类的

**Comment by oahzuw** [comment]
密码输错会有提示密码错误,  密码对的情况什么也没有

**Comment by cosven** [comment]
理论上来讲，密码对了的话，登陆框就会消失。
然后主界面会加载你的歌单。

你也可以更新试试，这两天有比较大的更新，在稳定性和性能都有一定的提高

**Comment by oahzuw** [comment]
好的 等你更新吧,现在可以用拼音搜索歌曲,现在就这样听的

**Comment by cosven** [comment]
昨天已经更新了，不知道登陆问题解决了没。

输入法的问题，我之后再去研究研究，目测跟 Qt这个库、和系统有关。

**Comment by AkemiHomura** [comment]
14.04.03 fcitx已经跟进到最新版了，aptitude install fcitx-front-qt5，你搜索一下，名字我手打的不一定对，是fcitc qt5的plugin，这里顺便说一下，低于这个版本的或者其他发行版没有跟进fcitx最新版的只能自行编译了

**Comment by cosven** [comment]
f

**Comment by ArkBriar** [comment]
...我之前说的有误！ ！因为我自己的项目今天编译的时候搞了一下这个fcitx问题
qt5.4以后要重现编译fcitx-qt5，因为qt5.4+对之前版本并没有二进制兼容！而官方源的fcitx-qt5再qt5.4之后的版本用会导致内存越界
如果pyqt5用的是qt5.4以上的接口，请一定注意！！

**Comment by cosven** [comment]
貌似看目前大部分 pyqt5 的版本都是基于qt5.3 或者以下的
