### ISSUE TITLE
How to download MV?

### ISSUE THREAD

**Issue by DrXie** [cosven/FeelUOwn#202]
I have using this project for a long time, and I know there was a 'MV' button here in the old version, if you click it, you can watch the MV in the VLC, you can also download it.
But in the latest version, I can't find it.
Is the API ineffective? or just I did not find it?

**Comment by cosven** [comment]
In the lastest version, I have not add this feature into project.

**Comment by cosven** [comment]
最新版又加上了 =。=
竟然是 2016 年的 issue，好久了
