### ISSUE TITLE
The project does not support debian 7?

### ISSUE THREAD

**Issue by redapple0204** [cosven/FeelUOwn#203]
python3-qt5 the dependencies can not be installed, there is no source

**Comment by cosven** [comment]
I have not test it on debian 7.
I think the package  name may be different. Maybe `python3-pyqt5`

**Comment by redapple0204** [comment]
@cosven I searched on other packages py3-qt5, python3-qt5, etc., are not in the source where possible debian7 do not really support.

**Comment by cosven** [comment]
try `sudo apt-cache search qt5` ?

**Comment by redapple0204** [comment]
@cosven  This is out of my search results

> [sudo] password for redapple: 
libqt5concurrent5 - Qt 5 concurrent module
libqt5core5a - Qt 5 core module
libqt5dbus5 - Qt 5 D-Bus module
libqt5gui5 - Qt 5 GUI module
libqt5network5 - Qt 5 network module
libqt5opengl5 - Qt 5 OpenGL module
libqt5opengl5-dev - Qt 5 OpenGL library development files
libqt5printsupport5 - Qt 5 print support module
libqt5sql5 - Qt 5 SQL module
libqt5sql5-mysql - Qt 5 MySQL database driver
libqt5sql5-odbc - Qt 5 ODBC database driver
libqt5sql5-psql - Qt 5 PostgreSQL database driver
libqt5sql5-sqlite - Qt 5 SQLite 3 database driver
libqt5sql5-tds - Qt 5 FreeTDS database driver
libqt5test5 - Qt 5 test module
libqt5widgets5 - Qt 5 widgets module
libqt5xml5 - Qt 5 XML module
qt5-default - Qt 5 development defaults package
qt5-qmake - Qt 5 qmake Makefile generator tool
qtchooser - Wrapper to select between Qt development binary versions
libqt5bluetooth5 - Qt Connectivity Bluetooth module
libqt5nfc5 - Qt Connectivity NFC module
libqt5qml5 - Qt 5 QML module
libqt5quick5 - Qt 5 Quick library
libqt5quickparticles5 - Qt 5 Quick particules module
libqt5quicktest5 - Qt 5 Quick Test library
libqt5quickwidgets5 - Qt 5 Quick Widgets library
qt5-doc - Qt 5 API Documentation
qt5-doc-html - Qt 5 API documentation (HTML format)
qt5-image-formats-plugins - Qt 5 Image Formats module
libqt5positioning5 - Qt Positioning module
libqt5positioning5-plugins - Qt Positioning module - position plugins
libqt5multimedia5 - Qt 5 Multimedia module
libqt5multimedia5-plugins - Qt 5 Multimedia module plugins
libqt5multimediaquick-p5 - Qt 5 Multimedia Quick module
libqt5multimediawidgets5 - Qt 5 Multimedia Widgets module
qtmultimedia5-examples - Examples for Qt 5 Multimedia module
libqt5declarative5 - Qt Quick 1 module for Qt 5
libqt5script5 - Qt 5 script module
libqt5scripttools5 - Qt 5 script tools module
libqt5sensors5 - Qt Sensors module
libqt5sensors5-dev - Qt 5 Sensors development files
libqt5serialport5 - Qt 5 serial port support
libqt5serialport5-dev - Qt 5 serial port development files
libqt5svg5 - Qt 5 SVG module
libqt5svg5-dev - Qt 5 SVG module development files
libqt5svg5-private-dev - Qt 5 SVG module private development files
libqt5clucene5 - Qt 5 CLucene module
libqt5designer5 - Qt 5 designer module
libqt5designercomponents5 - Qt 5 Designer components module
libqt5help5 - Qt 5 help module
qdbus-qt5 - Qt 5 D-Bus tool
libqt5webkit5 - Web content engine library for Qt
libqt5webkit5-dbg - Web content engine library for Qt - debugging symbols
libqt5webkit5-dev - Web content engine library for Qt - development files
libqt5websockets5 - Qt 5 Web Sockets module
libqt5websockets5-dev - Qt 5 Web Sockets module - development files
libqt5x11extras5 - Qt 5 X11 extras
libqt5x11extras5-dev - Qt 5 X11 extras development files
libqt5xmlpatterns5 - Qt 5 XML patterns module
libqt5xmlpatterns5-dev - Qt 5 XML patterns development files
libqt5xmlpatterns5-private-dev - Qt 5 XML patterns private development files
libmgl-qt5 - library for scientific graphs. (Qt runtime library)

**Comment by BruceZhang1993** [comment]
seems no pyqt5 in sourcelist. try (sudo) pip3 install PyQt5 ?

**Comment by redapple0204** [comment]
@BruceZhang1993 
No, it can't be installed.
 > Could not find a version that satisfies the requirement PyQt5 (from versions: )
No matching distribution found for PyQt5

**Comment by BruceZhang1993** [comment]
@redapple0204 https://pypi.python.org/pypi/PyQt5/5.7   you can download wheel package here if you use debian x86_64 .

**Comment by BruceZhang1993** [comment]
@redapple0204 https://packages.debian.org/jessie/python3-pyqt5 this debian package may works.

**Comment by redapple0204** [comment]
@BruceZhang1993 I try to download debian8 that package, but this is no way to install, it relies not satisfied

**Comment by cosven** [comment]
It seems that the only way left is to download the pyqt5 source code and compile it by yourself ... Sad.

**Comment by redapple0204** [comment]
@cosven Well... It seems like this, thank you.
