### ISSUE TITLE
有关播放列表的问题

### ISSUE THREAD

**Issue by chunws** [cosven/FeelUOwn#204]
- 如果当前播放列表有歌曲或从歌单开始播放，再进行私人FM或相似歌曲操作，会在当前播放列表下，刚刚播放的歌曲之下插入歌曲而不是清空之后重新插入新项目的播放列表。最新版本还是这样的。
- 当前播放列表无法批量删除。
- 播放串歌：播放一个歌单中的一首歌，然后在当前歌单里吧这首歌从列表里删除，再删这首歌下边的几首歌曲，然后再打开播放另一个歌单，随便放几秒，再播放第一次的歌单，在当前列表里播放第一个歌单之前播放的歌曲，会跳播到之前在当前列表里删除的歌曲之下的第一首歌。
- 单个歌曲的封面信息做背景挺好的啊=.=。不过你做的随你喜欢了。

**Comment by BruceZhang1993** [comment]
第一条我也发现了，主要是放FM的时候比较麻烦，以为是feture呢。。 第三条，厉害啊这特么都能测试出来。。。。 第二条，批量的功能基本都没做吧，比如批量下载，添加播放列表之类的

**Comment by cosven** [comment]
- 第一个是特意设计成这样的。感觉并没有什么坏处
- 第二个算是未来的 feature
- 第四个，之前由于技术问题把那个功能瞎掉了....不过貌似现在已经解决了当时考虑的技术问题。我想在增加配置模块之后，会把这个功能捡回来。
- 至于第三个，我还得研究下....

**Comment by chunws** [comment]
OK。那我就关掉了。
