### ISSUE TITLE
How to get a leaderboard (e.g., Top Lists)

### ISSUE THREAD

**Issue by redapple0204** [cosven/FeelUOwn#212]

**Comment by cosven** [comment]
I don't know what you mean exactly.
Netease Cloud Music API or something else?

**Comment by redapple0204** [comment]
@cosven 就是说请问网易云音乐客户端里面的“热歌榜”之类的在本程序里在哪里可以找到呢？

**Comment by cosven** [comment]
目前项目还没有“热歌榜”之类的 API...
有兴趣可以去网页版抓一下吧，然后分析一把。
另外，我记得一个叫做 netease-musicbox 的代码里面可能有这个 API

**Comment by redapple0204** [comment]
@cosven 确实，他那个命令行已经得到了api
不过我还不是很喜欢用命令行，总觉得不是很好用...

**Comment by BruceZhang1993** [comment]
you can favorite netease top list, and it will show on your favorite songlist list.    just a workaround.

**Comment by cosven** [comment]
算是需求 mark 一下，估计短时间个人没有时间来实现
