### ISSUE TITLE
不能登录

### ISSUE THREAD

**Issue by Ronnoc** [cosven/FeelUOwn#215]
点登录的按键之后就会报错
无法登录成功
(gst-plugin-scanner:20956): GLib-CRITICAL **: g_strv_length: assertion 'str_array != NULL' failed
Traceback (most recent call last):
  File "./feeluown/plugins/neteasemusic/nem.py", line 128, in login
    message = data['message']
TypeError: 'NoneType' object is not subscriptable
126的邮箱 和 手机号 都不能登录
登录后的data是
{'msg': 'invalid request uri', 'code': 404}

**Comment by cosven** [comment]
谢谢反馈了，我自己一直用的缓存。所以没发现这个登录问题...唔
