### ISSUE TITLE
Cannot play, decode failed

### ISSUE THREAD

**Issue by trifirew** [cosven/FeelUOwn#218]
When I tried to play an online song, it said `DECODE FAILED` on the screen.  
Terminal message:
```
Warning: "No decoder available for type 'audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true'."
Error: "Your GStreamer installation is missing a plug-in."
```
I'm using Arch Linux and I've already installed 
```
gst-libav 1.12.0-1
gst-plugins-bad 1.12.0-1
gst-plugins-base 1.12.0-1
gst-plugins-base-libs 1.12.0-1
gst-plugins-good 1.12.0-1
gst-plugins-ugly 1.12.0-1
gstreamer 1.12.0-1
```
It still didn't work.
Thanks! 谢谢！

**Comment by cosven** [comment]
there is a package named `feeluown-git` on arch linux repository.

transfer gate: <https://aur.archlinux.org/packages/feeluown-git/>

**Comment by trifirew** [comment]
@cosven Yes, it was installed from AUR, and all dependencies were installed. However, it doesn't work.

**Comment by cosven** [comment]
Recently, gstreamer has upgraded to 1.12, I suppose that the version is too high for pyqt5-multimedia module to work.
Currently, I use ubuntu as test environment, I can not reproduce the problem in ubuntu. Can you ask help from the package owner?

Note: I'm working on a player engine based on `mpg123` with python, it do not rely on gstreamer. I hope that the new player engine can bring a new experience on feeluown.

**Comment by cosven** [comment]
newest commit (dev branch) make feeluown use `mpv` as player backend, this problem will not cause any trouble.
