### ISSUE TITLE
Description area need a scroll bar to handle song lists with long descriptions

### ISSUE THREAD

**Issue by KireinaHoro** [cosven/FeelUOwn#223]
As the descriptions become too long to be fitted in the given area, it's necessary to add a scroll bar. Here's a screenshot demonstrating the situation.

![2017-07-13-012301_1208x201_scrot](https://user-images.githubusercontent.com/7804730/28132817-87d6dc72-6770-11e7-8432-996d6256c7a6.png)

**Comment by KireinaHoro** [comment]
And the formatting needs improving as well, especially correct spacing and returns.

**Comment by cosven** [comment]
you can press `space` to have a better view.

**Comment by cosven** [comment]
Fixed.
