### ISSUE TITLE
Volume control should be either separate from system volume or read current volume

### ISSUE THREAD

**Issue by KireinaHoro** [cosven/FeelUOwn#224]
The current behavior is that the volume control is at the rightmost at the beginning regardless of current system volume, thus dragging it will result in a sudden change (often sudden raise) in volume, which is indeed a very annoying experience.

Either splitting the volume control out (as many music players do) or locking the slider with the system settings from the very beginning will well solve this issue.

**Comment by KireinaHoro** [comment]
When using the gstreamer backend back in 1.0.5.3 the behavior is desirable.

**Comment by cosven** [comment]
on osx, the behaviro seems different.

`current volume = system volume x (feeluown volume / 100)`
as a result, even if feeluown volume is at the rightmost, the player volume should be `system volume x 1.0`

**Comment by KireinaHoro** [comment]
Actually Gentoo is no different from other Linux distros in this case.

**Comment by cosven** [comment]
I have a test in ubuntu 17.04. The volume works in expected behavior.
`volume = system volume * (slider volume / 100)`
Can you check your fuocore version or libmpv version?

**Comment by KireinaHoro** [comment]
`=dev-python/fuocore-0.0.5_alpha5`
`=media-video/mpv-0.18.0-r1[libmpv]`

**Comment by cosven** [comment]
use mpv 0.18.1 may solve this problem
as [mpv doc](https://wiki.gentoo.org/wiki/Mpv#Volume_in_0.18.1) states:

> Since version 0.18.1 the software volume control is always enabled. This means that volume controls don't change the system volume, e.g. per-application volume with PulseAudio.

**Comment by KireinaHoro** [comment]
i see. i'll update my ebuild.
