### ISSUE TITLE
这个播放器确实不错

### ISSUE THREAD

**Issue by sunxfancy** [cosven/FeelUOwn#23]
试用了一下，感觉的确挺好的，我挺喜欢这种功能简单，轻快易用的播放器。
不过确实有几个建议，希望能不断改进越做越好。
其一是托盘图标，不知为何跑到了Ubuntu托盘的最左边，直接挡住了其他程序的关闭按钮，我不知道是只有我这里是这样，还是设计时就是这样。
其二就是缺少个设置页面，由于我电脑平面分辨率是1920*1080的，整体字看起来非常小，如果有个界面设置，就比较好了。
另外我想知道这个项目文档生成是不是出问题了，我执行generateSphinxDoc.sh后，生成的文档中貌似没有什么有用的信息，如果要开源做下去的话，文档资料可能是非常关键的。

**Comment by sunxfancy** [comment]
呼。。。。刚刚改了n的样式文件，终于将字体调整大了点。
我想，最好找个方法，将各类样式文件综合的一起。
不过我很奇怪，既然引入了重量级的webkit，为何不是整个页面都用web渲染呢？
貌似左边的歌单和上面的一些效果是用qt做的吧，然后我发现样式既有css，又有qss。。。

**Comment by cosven** [comment]
恩，这些大大小小的问题都的确存在。
托盘图标的问题，之前很多人反映过了。是qt在Ubuntu的表现问题。 issue #5

关于文档，最近没有去维护（反正就是由于各种问题,,，比如程序的结构一直在完善，一直在改，我也是摸索着前进,然后---） (555) 总的来说，我想等程序架构稳定可行之后，再跟进文档

然后为什么不都用webkit的话，webkit是之后引入的。之前主要是为了求快，所以用它渲染一些内容。
(不过其实我觉得一部分用webkit，另外的用Qt，也挺好的呀。)

关于样式的话。哎，说来，这又是一个大的功能模块啊，打算是要做一个主题模块的，以后颜色可以统一改，字体也可以统一改，也就是对qss 和 css 进行一定的预编译之类的。然后时间真是不够用。我也是边学边写，所以进度超慢。。

语言组织的好乱。。

**Comment by sunxfancy** [comment]
关于主题的设置，其实css控制的完全可以只用js进行换肤，只要动态替换需要的css就可以了。
而qt的换肤可能比较烦，得用python代码控制qss。
之所以说完全用webkit的话会好一些，就是因为其换肤很好做，更好样式和增加背景图片非常方便，但如何是qt和webkit混合的话，就会造成整体渲染分为两部分，控制要分别控制。增加背景图片就更难了，没准还得将图片切开神马的。
所以，从项目长远角度看，建议其一就是尝试整体均用webkit渲染，可能换肤和页面渲染都能有统一的效果。
其二，可以尝试通过插件引入更多页面功能，例如在线搜索，本地音乐搜索，都可以统一的做到插件中，目前插件化我只看到了python代码的插件，而如何能增加html5的插件，增加新页面，那么功能会非常的灵活，而且也很好管理。
两点不成熟的意见，仅供参考，有时间时，我也会稍稍看下代码，研究下具体的实现。
