### ISSUE TITLE
When scanning local music,I want to scan the subdirectory.

### ISSUE THREAD

**Issue by Zangwill** [cosven/FeelUOwn#239]
电脑里的音乐被分门别类地整理在`/home/$USER/音乐`里面的几个文件夹，所以希望扫描目录时能扫描一下子目录。

**Comment by cosven** [comment]
目前是有扫描子目录（深度为 2）的，不过写的是 `~/Music` 目录，而你的是中文名字，没有被识别到。
我之后会修一下这个问题。

目前一个临时解决方案是：给音乐目录创建一个软链： `ln -s ~/音乐 ~/Music`
