### ISSUE TITLE
托盘提示的信息的背景是花色，看不清提示内容

### ISSUE THREAD

**Issue by Millyn** [cosven/FeelUOwn#24]
你好 遇到了一些问题
输入./install.sh后提示
```
---------------------------
脚本适用于Debian系的Linux
---------------------------
准备安装相关python依赖
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
./install.sh: line 107: syntax error: unexpected end of file
```
关于Python3的依赖都安装好了,直接运行`app.sh`可打开软件界面
听歌和登入都没有问题.但右下角气泡消息底色是花的,反正很不舒服的底色.

最后也无法生成桌面图标,也搜索不到FeelUOwn.

**Comment by cosven** [comment]
哦， 刚才有位好心人貌似已经修复了这个问题。
气泡的颜色，我去看看，我还以为是我系统抽风了。。。

**Comment by Millyn** [comment]
花色的bug如图片.安装问题确实已经解决,正常安装成功.

[图片链接](http://img.vim-cn.com/f7/2feba3458c33fb511ca5982f0bed11d3dda479.png)

谢谢开发者.

**Comment by cosven** [comment]
我暂时还不知道这个背景变成灰色该怎样解决...
看来要求助其他人了 - -

**Comment by cosven** [comment]
最新版本已经自定义了通知控件。问题不存在了。
