### ISSUE TITLE
No 'Play All' button 

### ISSUE THREAD

**Issue by Zangwill** [cosven/FeelUOwn#241]
没有“描述”，也没有“播放全部”和“展开描述”按钮：
![截图](https://img.vim-cn.com/cf/99832046652fea1126f6d2f82079ccdd0ed630.png)

**Comment by cosven** [comment]
可以安装最新版 2.1a2，`pip3 install 'feeluown>=2.1a2' --upgrade` 。

更新命令：`pip3 install 'feeluown>=2.1a2' --upgrade` 

ps: pip3 默认会安装稳定版本，你的版本应该是 2.0，就没有这两个按钮。
