### ISSUE TITLE
RuntimeWarning: coroutine 'BaseSelectorEventLoop.sock_sendall' was never awaited

### ISSUE THREAD

**Issue by peng051410** [cosven/FeelUOwn#242]
当执行feeluown -nw后，使用nc命令进行连接时，报这个错误，再执行search命令也是这个错误，请问要怎么破？
![image](https://user-images.githubusercontent.com/5512326/46903693-0f1dc800-cf0b-11e8-9cbc-08c1503bd643.png)

**Comment by cosven** [comment]
是个 bug，最新版 (2.1.1) 已经修复了 
https://github.com/cosven/FeelUOwn/commit/a02a6e4f44a92c981fba089799de2a3c44ce52dd

`pip3 install "feeluown>=2.1.1" --upgrade --user`

**Comment by cosven** [comment]
谢谢反馈 ~
