### ISSUE TITLE
无界面方式，搜索到的歌play提示Invalid song

### ISSUE THREAD

**Issue by peng051410** [cosven/FeelUOwn#243]
![image](https://user-images.githubusercontent.com/5512326/46916152-42cf1f80-cfe9-11e8-87d7-f2a34e04a887.png)
nc 连接控制界面如下：
![image](https://user-images.githubusercontent.com/5512326/46916164-74e08180-cfe9-11e8-8521-4e6b7bdeda95.png)

**Comment by cosven** [comment]
应该是有的歌曲要收费或者确实没有资源可以播放。

之后改进的一个方法是在显示之前过滤一下这种没用的歌曲，或者给一个标记。

**Comment by cosven** [comment]
简单调研了一下对于网易云音乐，刚怎样进行有效性判断，目前的情况是这样子
1. 目前 feeluown 使用的歌曲详情 API 和搜索 API 中均没有字段标记了歌曲有效性（可能是因为接口比较老了）
2. 一个 [网易云音乐 node 项目](https://github.com/Binaryify/NeteaseCloudMusicApi) 判断歌曲有效性的方法是获取一下这首歌曲的 url，存在 url 即有效，否则就无效。
3. 网易云音乐网页端目前改成了服务端渲染，没办法确定它是怎样判断的

------------

目前想到的解决办法：
1. 类似 node 项目一样，请求一下歌曲 url（记忆中这个接口支持批量）
2. 不使用现在的 API，使用爬虫的方式

-----------

另外，还有种思路：当一首歌在 A 平台上没有资源的时候，自动 fallback 到 B/C/D 平台

**Comment by cosven** [comment]
最新版 `feeluown>=3.0a5` 支持自动 fallback
