### ISSUE TITLE
找到的歌play不了，显示Invalid song

### ISSUE THREAD

**Issue by peng051410** [cosven/FeelUOwn#244]
![image](https://user-images.githubusercontent.com/5512326/46916152-42cf1f80-cfe9-11e8-87d7-f2a34e04a887.png)
nc 连接控制界面如下：
![image](https://user-images.githubusercontent.com/5512326/46916164-74e08180-cfe9-11e8-8521-4e6b7bdeda95.png)

**Comment by cosven** [comment]
这个和 #243 是同一种情况，先 close 了。
