### ISSUE TITLE
网易云歌单里来自云盘的歌曲不显示

### ISSUE THREAD

**Issue by maz-1** [cosven/FeelUOwn#248]
RT，自己上传到云盘的歌曲添加到歌单，feeluown里无法显示

**Comment by cosven** [comment]
我今天排查看看 ~

**Comment by maz-1** [comment]
> 
> 
> 这些歌在网页上面能显示么？
> 我今天排查看看 ~

网页上可以显示

**Comment by cosven** [comment]
我用 windows 传了一个首本地的歌曲到网盘，然后将这首歌收藏在歌单中，接着在 feeluown 中是可以看到这首歌的（不过可能需要重启一下，因为现在 feeluown 无脑缓存了歌单里面的歌曲列表，当列表发生变化时，feeluown 可能不能及时检测到，缓存策略之后会进行改进）。

**Comment by cosven** [comment]
我暂时把这个 issue 标记为 invalid，你如果之后发现还有问题，我们可以继续讨论哈 ~

**Comment by maz-1** [comment]
应该是云盘里没有上架过的歌曲会这样
https://pan.baidu.com/s/1tzAqEdKU2oUDplwAt-XOXg
https://music.163.com/#/my/m/music/playlist?id=161907351
登录以后网页上看得见
![scr](https://user-images.githubusercontent.com/5277060/48014114-ecc14800-e160-11e8-8495-64275592b5c8.jpg)

**Comment by cosven** [comment]
收到，我晚上回去试试

**Comment by cyliuu** [comment]
网易云没识别出的云盘歌曲网页端识别出来了也是没法播放，客户端可以，终极解决方案应该是更换最新的API。。

**Comment by cosven** [comment]
> 网易云没识别出的云盘歌曲网页端识别出来了也是没法播放，客户端可以，终极解决方案应该是更换最新的API。。

嗯，是的，要切换一下播放列表详情接口的 API 版本。

目前调研的情况是：网页端能识别出来，点击播放会提示播放失败。但其实是能获取到 url 的，如果我本地用  mpv 来播放这个 url，是可以播放的。

所以，要想支持这个功能，需要做一件事情。使用新版本 API：目前看只需要更新 “播放列表详情” 这一个接口即可。

**Comment by cosven** [comment]
这个在最新版中 `>=3.0a5` 应该已经支持了 ～

**Comment by maz-1** [comment]
thx
