### ISSUE TITLE
黑色主题系统白色字在简介描述处看不见了

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [cosven/FeelUOwn#249]
中间上方的描述等几个部分都看不见字，白色字白色背景？
哪个地方有设置主题的？

**Comment by cosven** [comment]
目前还只写了一个主题，还没有地方可以切换主题。
你可以截张图吗？我看看如何调整一下颜色调整 ~

**Comment by GreatBigWhiteWorld** [comment]
老实说我可能是因为设置了非国内的dns，网页版根本听不了，然后试试feeluown开始还能听，后来很奇怪是断断续续的也没法听于是卸载了，没法截屏了。你试试linux系统kde的黑色主题，应该很明显。
顺道问问不知道是不是还是只能国内用才能听，系统用个香港的dns服务器好像就不行了？

**Comment by cosven** [comment]
部分地区的 IP 应该是有限制的。

你运行命令的时候可以这样 `NO_PROXY="music.163.com" command`，这样大部分情况可以绕过系统代理。

**Comment by GreatBigWhiteWorld** [comment]
所以我好奇你在软件那边能否提供一个解决方案，目前国外的朋友还是用不了吧？我记得之前这个软件能听下架的曲子。。。
我就是不知道应该绑那些地址到hosts

**Comment by cosven** [comment]
这个可以 ~ 我新建个 issue 记一下这个需求

**Comment by specter119** [comment]
我来搬回已经歪掉的楼。

![screenshot_20190120_164220](https://user-images.githubusercontent.com/8768524/51437003-67b2ed00-1cd2-11e9-9fb7-4a41f157a73b.png)

arch kde5 暗色微风 不过不止 FeelUOwn 有问题，用qt的我看到的有这个问题的还有 mendeley 。

**Comment by cosven** [comment]
@specter119  恩，感觉需要加个暗色主题，现在 macOS KDE GNOME 都是支持 Dark 和 Light 两种模式。

我之后有空会考虑加一个。也欢迎提交 Pull Request，只需要修改这个文件修改即可：https://github.com/cosven/FeelUOwn/blob/master/feeluown/mac.qss

**Comment by cosven** [comment]
现在已经支持 light 和 dark 两种主题 ~

在 `~/.fuorc` 中配置 `config.THEME = 'dark'` 即可使用暗色主题

**Comment by hengstchon** [comment]
> 所以我好奇你在软件那边能否提供一个解决方案，目前国外的朋友还是用不了吧？我记得之前这个软件能听下架的曲子。。。
> 我就是不知道应该绑哪些地址到hosts

海外用户亲测可以使用，但是目前都只能听 QQ 音乐里的歌。

**Comment by cosven** [comment]
> > 所以我好奇你在软件那边能否提供一个解决方案，目前国外的朋友还是用不了吧？我记得之前这个软件能听下架的曲子。。。
> > 我就是不知道应该绑哪些地址到hosts
> 
> 海外用户亲测可以使用，但是目前都只能听 QQ 音乐里的歌。

当时可能还不支持 QQ 音乐...

如果要用网易云的话，可以尝试这样绑 host（我也没测试过）。虾米的话，我暂时还没了解过。

```
103.18.208.222 m8.music.126.net
```

我目前知道的是这样：网易云有多个 cdn 域名，类似 `m*.music.126.net`，所以只绑这一个的话，可能还不够，但应该可以听一部分（我猜的）。
