### ISSUE TITLE
开发计划、或一些临时想法、或一些美好愿景

### ISSUE THREAD

**Issue by cosven** [cosven/FeelUOwn#25]
### 对项目基础的认识
音乐播放是根基，酷炫美观是追求的目标，性能不会是考虑的重点

### 近期目标
1. 重构View模块，让代码更容易被读懂
2. 重构web模块，套用更成熟的框架

1. 自定义跨平台通知控件，现有QT5的通知在许多linux平台表现不理想。
2. 加强搜索功能。比如说: 搜索 “李克勤 富士山下”

#### 过度目标
1. 增加设置模块
2. 给插件开发增加示例 和 修订一些开发标准

### 已经完成的东西
- 已经有了一个比较基础的音乐播放功能，也有了一定的稳定性
- 使用asyncio对程序进行并发支持
- 在主要的显示区域使用webkit模块，增强界面显示、方便其他功能开发
- 。。。

### 想到的一些特性
1. 给音乐加 **标签**

**Comment by cosven** [comment]
今天看着Github的Issue的label。我想到了音乐的分类问题。
对于音乐的分类，现有的音乐播放器给用户的权限一般都是让用户新建分类，然后用户把相应的歌曲塞入这个分类当中。

但实际上，这是有局限性的。每首音乐的独特的地方或者吸引你的地方不止一个，比如说听到`secret base` 我不仅想把它加入`日语`的分类，还想把它加入 `插曲`的分类，还想给它加入`感人`的分类。在我个人的使用经验当中，我会尽量让一首歌有它自己最适合的分类，这个决定常常会让我纠结很久。

所以，问题来了，我们何不让音乐具有label。
用过豆瓣的童鞋或许知道，豆瓣会让用户对一部电影或者音乐加标签，而不是分类。

在我看来，加标签有几个好处
- 标签更随意，听音乐的时候，我们往往想放松自己，我们都想拍拍脑袋就能搞定事情。
- 对于分类，我们（最少我个人）会感觉比较头疼，会有选择困难症。另外，从交互设计的角度考虑，分类这件事情增加了用户的操作成本。

或许这个特性可以在某个版本中加入。


好吧，问题来了。我觉得

**Comment by v-yadli** [comment]
@cosven Label +1

**Comment by AkemiHomura** [comment]
”playlist“:{"tags":[]...}，playlist的detail里面有一点点tag，初期的话我感觉可以利用一下，而不用让用户一开始从零标注( 毕竟我们暂时并没有什么手段交换各自的label

**Comment by BruceZhang1993** [comment]
可以借助豆瓣或者其他的Music API，暂时参考里面的Tags进行标注，进一步允许用户添加Tag，已经根据Tag分类等等
