### ISSUE TITLE
音质 可以 自主选择吗？

### ISSUE THREAD

**Issue by OliverOrchid** [cosven/FeelUOwn#251]

**Comment by cosven** [comment]
目前还不支持选择音质。

从**理论上**来说，虾米音乐是可以选择音质的（API 已知）；网易云音乐不能选择高品质音乐（未抓取到 API），QQ 音乐暂未研究。由于目前时间精力有限，暂时还为支持选择音质的功能，理论上实现起来应该比较简单，大概一天时间可以完成吧。

**Comment by OliverOrchid** [comment]
嗯嗯了解了，辛苦啦??

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cosven** [comment]
> > 目前还不支持选择音质。
> > 从**理论上**来说，虾米音乐是可以选择音质的（API 已知）；网易云音乐不能选择高品质音乐（未抓取到 API），QQ 音乐暂未研究。由于目前时间精力有限，暂时还未支持选择音质的功能，有几个比较重要的功能正在开发中，这个功能会往后排，理论上该功能实现起来也不复杂。
> > 如果有兴趣，欢迎 PR ~ 我可以提供一些力所能及的辅助。
> 
> 网易云的网页版没有高品质音乐的API 客户端API+付费音乐包（是否一定需要暂未验证）可能才会有，QQ音乐的有API，我之前的那版其实已经加强了QQ音乐除登陆外的功能。

这样子，之前我把虾米音乐相关的逻辑整理之后，感觉音乐资源已经挺多的了，然后就暂时没继续整理 QQ 音乐相关的逻辑。
我最近会把下载和 QQ 音乐的逻辑再整理整理。什么时候把相关功能整理完，什么时候就关闭这个  [feeluown-core PR 22](https://github.com/cosven/feeluown-core/pull/22)

**Comment by cosven** [comment]
目前已经实现，可以在配置文件中配置音质选择策略 `AUDIO_SELECT_POLICY` ，配置文档：https://feeluown.readthedocs.io/en/latest/fuorc.html。

相关设计文档：https://github.com/cosven/FeelUOwn/issues/274
