### ISSUE TITLE
Music is played twice in parallel on Mac OS Mojave

### ISSUE THREAD

**Issue by maz-1** [cosven/FeelUOwn#252]
Whether I play music by double click playlist item or click "play all" , music is played twice in parallel, and click pause button will only stop one thread, another thread is still playing. And due to the unstoppable player thread, the process will only exit with force close.

macbook-pro:~ ling$ feeluown
[INFO] [__init__ logger_config 78] : Release mode.
[INFO] [player initialize 424] : Player initialize finished.
[INFO] [__init__ <module> 42] : Using Qt Implementation: PyQt5
[INFO] [pubsub run 112] : Fuo pubsub server running  at 0.0.0.0:23334
[INFO] [player initialize 424] : Player initialize finished.
/usr/local/lib/python3.7/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[INFO] [__init__ enable 20] : Register provider: <fuocore.local.provider.LocalProvider object at 0x1175daef0>
[INFO] [__init__ enable 31] : Associate <fuocore.local.provider.LocalProvider object at 0x1175daef0> with 本地音乐
29
[INFO] [plugin scan 43] : detect plugin: 本地音乐.
48
[INFO] [plugin scan 43] : detect plugin: 网易云音乐.
67
[INFO] [plugin scan 43] : detect plugin: QQ 音乐.
86
[INFO] [plugin scan 43] : detect plugin: 虾米音乐.
[INFO] [__init__ enable 14] : load mac hotkey plugin
[INFO] [plugin scan 43] : detect plugin: mac 全局快捷键.
[INFO] [mac run_event_loop 56] : try to load mac hotkey event loop
[INFO] [cliapp run_server 79] : Fuo daemon run in 0.0.0.0:23333
[INFO] [player _on_song_changed 527] : Try to play song: fuo://netease/songs/22638595
[INFO] [player _on_song_changed 527] : Try to play song: fuo://netease/songs/22638595
[INFO] [player _on_duration_changed 516] : Player receive duration changed signal
[INFO] [player _on_duration_changed 516] : Player receive duration changed signal
[INFO] [version check_release 22] : 正在检测更新...
[INFO] [version check_release 41] : 当前已经是最新版本
[INFO] [player stop 491] : stop player...
[INFO] [__main__ main 149] : Event loop stopped.
^CTerminated: 15

**Comment by maz-1** [comment]
每次都会
版本：feeluown 2.1.1, fuocore 2.2a2
Debug日志：https://gist.github.com/maz-1/b155930f15948089519902dcf2d3d443

**Comment by cosven** [comment]
可以先升级一下版本，我发现这个老的版本确实会有问题
`pip3 install 'feeluown>=2.2a1'`

我之后继续再排查一下这个问题，看看原因是什么。

**Comment by maz-1** [comment]
新版本好了

**Comment by cosven** [comment]
新旧版，将播放器初始化了两次，这两个播放器都绑定到了同一个播放列表上，所以就有了这个问题。

其中有两个问题：
- [ ] 不同播放器不应该共用一个播放列表
- [x] 不应该初始化两个播放器

新版本修复了第二个问题，第一个问题我之后也优化一下。
