### ISSUE TITLE
ArchLinux 歌词无法一直置顶显示

### ISSUE THREAD

**Issue by light4** [cosven/FeelUOwn#26]
[歌词 67 行](https://github.com/cosven/FeelUOwn/blob/master/src/widgets/lyric_widget.py#L67)

**Comment by cosven** [comment]
你是什么系统，我在deepin 和 mac 上试过，都是可以的。

**Comment by light4** [comment]
Archlinux

**Comment by cosven** [comment]
仔细想想，这应该和你的桌面环境有关系

**Comment by cosven** [comment]
近期的更新有对歌词窗口进行改动，不知道现在这个问题有木有解决。你可以试着更新一下。
