### ISSUE TITLE
请问能支持windows吗?

### ISSUE THREAD

**Issue by gameboyring** [cosven/FeelUOwn#269]
想要一个可以在windows下调用的播放器

**Comment by cosven** [comment]
之前有朋友测试过一个旧版本，在 windows 下是可以工作的（所以最新版本理论上也是可以在 windows 工作的）。

但是在 windows 上用的话，安装相对会比较麻烦，目前也没有包可以直接安装。我自己没有 windows 机器，所以没办法给出具体的安装教程或者方法。如果 LZ 愿意花时间折腾下，我可以随时提供我能提供的帮助 ～

**Comment by gameboyring** [comment]
非常感谢热心的老大
win7,已经安装好包和pyqt5,启动报错
![image](https://user-images.githubusercontent.com/42858485/57172750-d4ec2780-6e56-11e9-9303-78408f16ddcd.png)

**Comment by cosven** [comment]
主要思路是：你还要想办法安装一个*动态链接库* `mpv.dll`，让程序能够访问到。

一个具体的办法：之前朋友的办法是自己下载一个 mpv.dll；然后修改 windows 的 PATH 变量，把 mpv.dll 所在目录加入到这个变量当中（相当与 Linux 的 LD_LIBRARY_PATH 环境变量）。mpv 官网有资料链接 https://mpv.io/installation/

ps: 你也可以加入 [Telegram 群](https://t.me/joinchat/H7k12hG5HYtsnOWpUDNMVw) 来沟通 _这个问题_

**Comment by PhotonQuantum** [comment]
可以参考 https://github.com/jaseg/python-mpv/issues/60#issuecomment-352719773 这里的解决方法

**Comment by cosven** [comment]
经过 IM 工具沟通后，按照上述思路，问题已经解决，先 close 了。
