### ISSUE TITLE
支持移动端的一些设想

### ISSUE THREAD

**Issue by cosven** [cosven/FeelUOwn#273]
- 作者：@cosven 
- 创建时间：2019-05-19
- 最近更新：
  - _2019-05-21_
  - _2019-05-22_ - 补充 web 相关功能的实现细节
- 最新状态：
  - _2019-05-22_ - 不通过
    - 该功能和现有的架构不是很搭边，开发工作量比较高

## 简介与动机

目前 feeluown 能播放多平台的音乐资源，但它目前只能工作在 PC 端。在移动端，我们仍然需要使用多个 App  才能获取多平台的音乐资源。

另外，feeluown 提供了 **收藏集** 功能，但却只能在 PC 端使用，没有办法同步到移动端使用，这使得该功能的体验非常的差。

我觉得如果 feeluown 能支持移动端，那么移动端听音乐会变得更加方便，用户可以更好的使用 feeluown。

## 方案描述

**让 feeluown 充当服务端，提供若干 HTTP API 以及展示页面。用户可以在手机上通过浏览器访问 feeluown 提供的资源，并在浏览器上浏览或播放相关资源。**

在这个方案下，feeluown 用户只需要在手机上安装一个浏览器，并在 PC 端运行 feeluown 服务即可。如果用户没有办法保证自己的 PC 一直处于开机状态，可以考虑在手机端运行 feeluown 服务。举个例子，对于 iOS 用户来说，他们可以安装 Pythonista 应用，然后在里面运行 feeluown 服务（这可能需要 feeluown 做一些改进，后面会提到更多细节）。

### 一些疑问

1. 上面提到“用户可以安装 Pythonista 应用，然后在里面运行 feeluown 服务”，在这个情况下，用户是不是就不需要网页客户端了？
 
    仍然需要。否则用户没有办法操控 feeluown。
 
2. 接第一个问题，那我们基于 Pythonista 给 feeluown 开发一个 GUI 程序，用户就有办法操控 feeluown 了？

    听起来可行，但是仍需调研。直觉上，这种方案成本较高。个人简单的试用了 Pythonista，它虽然声称自己是一个 “A Full Python IDE for iOS”，但它存在一些 bug（比如 [ctypes.macholib 问题][pythonista-ctypes]），pip/git 等工具也不是开箱既用，基于 Pythonista 进行开发是比较难受的（要在移动端编程）。
    
    另外，Pythonista 目前只工作在 iOS 上，安卓用户无法使用。

- [ ] iOS 可以同时运行两个应用吗？比如在 Pythonista 运行 feeluown 服务，然后同时在 web 端播放音乐？

## 方案细节分析

> 开发一个网页客户端，让 feeluown 充当服务端，提供若干 HTTP API 以及展示页面。

这个需要后续开发。我们需要让 feeluown 能提供 web 服务，比如让用户通过 http://localhost:23335 来访问控制播放器。

> 并在 PC 端运行 feeluown 服务即可

我们认为用户可以将 feeluown 服务运行在自己的 PC 上，或者部署在一台服务器上。

> 如果用户没有办法保证自己的 PC 一直处于开机状态，可以考虑在手机端运行 feeluown 服务

在手机端运行 feeluown 服务可能会遇到一些问题。feeluown 目前的播放引擎是 MPV，使用 ctypes 来调用 libmpv 提供的接口。经个人测试，这个思路在 Pythonista 上是不太可行的，一方面 Pythonista 的 ctypes 模块有一些 bug；另一方面，目前 iOS 平台没有现成的 libmpv。

所以如果要让 feeluown 能够在移动端运行，我们需要对 feeluown 做一些修改，比如让 feeluown 启动时可以不加载 MPV 播放器。

总的来说，这个方案有两个 TODO

- [ ] 给 feeluown 添加 web 相关功能（可以以插件的方式？）
- [ ] 让 feeluown 支持一种模式：启动时只加载 Library 和 web 相关模块，而不加在播放器等模块

### 实现细节：给 feeluown 添加 web 相关功能
开发一个名为 `feeluown-http` 的插件，该插件可以启动一个 web server：提供一个单页应用（[SPA][spa]）；实现若干 REST 接口。

用户在手机端的使用流程

1. 在手机上或者 PC 上运行 feeluown
2. 打开手机浏览器，访问链接： `http://localhost:23335`
  这时候，用户应该可以看到一个页面，这个页面内容和 feeluown GUI 界面内容基本相似。
  包括：音乐库；我的收藏集；歌单列表；搜索等
3. 选取一首歌曲进行播放。这个操作在后台会触发两个动作：
    1. 浏览器发送请求给 feeluown 后端，拿到歌曲（或者说 MV）的播放链接
    2. 浏览器播放歌曲

### 实现细节：让 feeluown 支持一种新模式
我们假设该模式名称为 `library` 模式。该模式和现有的 CLI/GUI 模式完全不同，在该模式下，feeluown 不再是一个播放器，它不能播放音乐或者 MV，它仅仅是一个资源服务，提供 HTTP/TCP 等接口，让客户端从这里获取资源并播放。

> 注：给 feeluown 加一种模式，无疑会让原有的 feeluown 的架构变得更加复杂。所以这种模式的具体实现方式需要仔细研究。我们甚至可以考虑不依赖 feeluown，只依赖 fuocore 来实现这样一个模式。

[pythonista]: http://omz-software.com/pythonista/
[pythonista-ctypes]: https://github.com/omz/Pythonista-Issues/issues/311
[spa]: https://zh.wikipedia.org/wiki/%E5%8D%95%E9%A1%B5%E5%BA%94%E7%94%A8

**Comment by cyliuu** [comment]
这种方案是否支持跨语言调用？如果支持的话Jsbox可能更合适，主要原因在于：1.目前也有一些音乐类软件基于Jsbox开发；2.社区相对比较活跃，作者也比较积极；3.印象中TestFlight版本支持后台播放音乐。

**Comment by cosven** [comment]
> 是否支持跨语言调用

这是指哪个部分？目前思路没有涉及语言之间的调用。

之前描述的比较简单，上面提到的 web 功能，我补充了一些细节。

**Comment by cyliuu** [comment]
> 你可以看看是否和之前理解的是一样的？
应该就是手机通过访问网页或者请求网址获得一些数据，然后可以通过web（或者其他语言c++, js, python等重新绘制界面吧），我一开始把Pythonista看成必备应用了。移动端主要起到remote的功能，需要与PC，移动端(Pythonista)或网络服务器配合使用。

**Comment by cosven** [comment]
> > 你可以看看是否和之前理解的是一样的？
> 
> 应该就是手机通过访问网页或者请求网址获得一些数据，然后可以通过web（或者其他语言c++, js, python等重新绘制界面吧），我一开始把Pythonista看成必备应用了。移动端主要起到remote的功能，需要与PC，移动端(Pythonista)或网络服务器配合使用。

恩恩，是这样的，我想表达的意思也是这样。

在这种情况下的话，应该就不存在跨语言调用把。或者说，各语言是通过 HTTP 协议或者其他通信协议来交换数据。

**Comment by cosven** [comment]
补充一下个人的想法：
从理论上来讲，Server-Browser 架构的这个方案是可行的。不过我感觉它可能带来两个问题：
1. 如果基于现有的 FeelUOwn 架构来实现的话，可能会让 FeelUOwn 变得很复杂，支持的功能和模式都很多。所以，我觉得要实现的话，可以单独新建一个 repo，搞得时候可以复用一部分 FeelUOwn 的逻辑，这或许可以反推着，让 FeelUOwn 各模块之间关系更加清楚。
2. 实现出来之后，用户使用的时候，可能有点折腾，毕竟每次使用的时候，都需要保持有一台服务器（电脑）开着
