### ISSUE TITLE
支持多品质音乐

### ISSUE THREAD

**Issue by cosven** [cosven/FeelUOwn#274]
- 作者：@cosven 
- 创建时间：2019-05-27
- 最近更新：
- 最新状态：
  - *2019-5-28* - 该设计存在很多问题，详见[评论](https://github.com/cosven/FeelUOwn/issues/274#issuecomment-496577266)
  - *2019-06-11* - 改进上面提到的问题，详见[评论](https://github.com/cosven/FeelUOwn/issues/274#issuecomment-500860768) 
  - *2019-06-11* - 已经实现后端。相关 MR：
    - https://github.com/cosven/FeelUOwn/pull/275 @cosven 
    - https://github.com/feeluown/feeluown-xiami/pull/1 @cyliuu @cosven 

## 简介与背景

一首歌或者一个视频可能会有多个品质，一般来说，我们可以**根据比特率([bitrate])来确认歌曲和视频的品质**。在各大视频网站，我们经常可以看到它们把视频被分为流畅、低清、高清、蓝光等；在各大音频网站，音频也会按照品质被分等级，比如 QQ 音乐，它把歌曲分为：标准、HQ 高品质、SQ 无损品质；网易云音乐把它们分为：标准、较高、极高、无损品质。用户在使用这些软件的时候，一般不需要关心自己听的是什么品质，因为播放器一般都会提供一个选项：自动。

据个人非正式的调研所知（部分为个人主观猜测），以前，**对视音频划分品质的一个最重要的目的**就是让用户在不同的网络状况下都能够观看视频。比如在网速慢的时候，我们可以选择看流畅或者低清的视频以确认视频不会卡顿；在使用移动网络的时候，我们可能也希望使用低品质资源以节省流量。现在，各产商对视音频划分品质有另外一个目的：收费，常见的方法就是用户可以使用相对低品质的视音频，但对于高品质的视音频，用户需要付费，比如要求用户开通 VIP。

FeelUOwn 的使用场景多为 PC 端，我们目前也没有品质的概念。在代码实现的时候，有的资源提供方是尽可能使用高品质资源，而有的是随机选用一个品质。站在用户角度，理想情况下：**我们应该提供能力，让用户自己来选择视音频品质**。

## 方案概述

用户使用视音频资源，在 FeelUOwn 内部，实际经历了这样一个过程：
1. 从资源提供方**获取并存储**资源信息
2. 将资源信息**展示**给用户，比如通过 GUI 或者 API
3. 用户**选择**资源，让 FeelUOwn 进行播放

要让 FeelUOwn 支持多品质音乐，我们也就是要改进增强这几个过程。

我们通过 `provider` 来获取歌曲信息，将歌曲信息保存在 `SongModel` 中，歌曲品质信息也是一样，我们也应该记录并保存它。这里， **我们给 `SongModel` 新增一个属性 `media` 来保存音乐的品质信息，media 是 `Media` 类的实例**。（注：Media 类早已存在于 fuocore.models 中，在这个方案里，我们不考虑之前的 Media 类，因为我们可能需要对 Media 类进行一些设计上的大改动）。

### Media 类设计

> **2019-06-11 UPDATE** 经过思考与实践，我们较大修改了 Media 类，所以下面部分文字描述和最终实现差别较大。

各个厂商对品质的定义都不相同，在背景中我们已经有提到；对于视频和音频，品质定义方法也不一样，视频虽然也可以根据比特率来评判品质，但通常来说，我们是根据视频分辨率来判断。

在 FeelUOwn 中，我们把视音频品质统一划分成 4 类，资源提供方应该参考这个标准来实现：

|   名字  |       质量               |                解释          |
|----------|-------------------------|--------------------------------|
| sq       | 无损（最好）       | 视频的蓝光、2k、4k，音频的无损（wav、320kbps 的 mp3）；无上限  |
| hd       |  高清 （第二好） | 720p/1080p 的视频，200 kbps 左右的音频 |
| md      | 标清                      | 480p 的视频，100kbps 左右的音频 |
| ld       |   流畅（最差）       | 无下限                                            |

代码实现
```python
class Media:
    class Q(IntEnum):  # Quality
        sq = 16
        hd = 8
        sd = 4
        ld = 2
```

#### 接口 1：查询 media 支持哪些质量
使用场景：在界面上**展示**一首歌有哪些品质

```python
class Media:
    def list_q(self):
        return (Q.sq, Q.sd, ...)
```

#### 接口 2：根据质量获取资源链接
使用场景，用户**选择**一首歌，或者 FeelUOwn 自动选择一首歌：
  1. 确切知道歌曲的某品质资源存在，获取 url
  2. 获取尽可能高质量的链接
  3. 获取尽可能低质量的链接
  3. 获取 hd 或者 hd 以上的链接，如果都没有，返回 sd 或者 ld

```python
class Media:
    class S(IntEnum):
        updown = 0
        downup = 1

    def get_url(self, q):
        return 'https://...'

    def select_url(self, q, s=S.updown):
        """select a url by quality and fallback strategy

        :param q: quality
        :param s: fallback strategy
        """
```

### Media 类的设想

在上面的设计中，Media 类就是歌曲 url 的封装。但目前我们没有保存 Media 的元信息：比如一个媒体文件的比特率是多少，它的格式是什么等。

之后，根据实际需求，我们**可能**会添加类似这样的接口：

```python
class Media:
    def get_meta(self, q):
        return XxxObject(**{'bitrate': '', 'format': '', 'url': '', 'q': ''})
```

也可能会单独添加一个新的类 `File`

[bitrate]: https://zh.wikipedia.org/zh-hans/%E6%AF%94%E7%89%B9%E7%8E%87

**Comment by cyliuu** [comment]
> 在 FeelUOwn 中，我们把视音频品质统一划分成 4 类，资源提供方应该参考这个标准来实现

关于音质的划分，网易云客户端将其分为无损音质(flac)、极高(320k)、较高(192k)和标准(128k)，QQ音乐客户端分为SQ无损品质(flac)、HQ高品质(320k)和标准品质(128k)，虾米客户端分为无损品质SQ(wav)、高品质HQ(320k或192k)、标准品质(128k)
具体地，一首歌128k为3M左右，320k为8M左右，sq一般在20～30M左右。

**Comment by cosven** [comment]
第一版设计存在的问题：

**Comment by cosven** [comment]
该功能已经实现。相关 MR：https://github.com/cosven/FeelUOwn/pull/275

上面提议中写的 Media 类的设计有一些问题，准确的文档如下：
