### ISSUE TITLE
能指定本地文件保存路径吗？

### ISSUE THREAD

**Issue by aesean** [cosven/FeelUOwn#28]
能制定本地音乐保存的位置吗？我有之前下载好的，好多音乐，不知道能不能关联起来．
另外mini之后如何还原啊？手残点了下mini发现还原不回去了．

**Comment by cosven** [comment]
暂时还不能检测本地音乐。

mini模式按 esc 可以回到正常模式（我的锅）

**Comment by aesean** [comment]
总体用起来还是很不错的，支持！
