### ISSUE TITLE
安装是否可绕过sudo权限？

### ISSUE THREAD

**Issue by lindajune** [cosven/FeelUOwn#29]
首先多谢开发～～～赞！
但是，上班地方的电脑没有root和sudo权限，是否可以像dropbox或者firefox之类，直接在自己的home路径启用，而不要root或sodu呢？

多谢！

**Comment by cosven** [comment]
恩，**使用** 软件的时候是不需要 root 权限的。

但是软件本身需要依赖一些库，**安装** 这些库的时候可能是需要root权限的。

**Comment by lindajune** [comment]
多谢回复～这样只能联系下管理员了。
