### ISSUE TITLE
Ubuntu15.04x64上无法登录

### ISSUE THREAD

**Issue by dhqdqk** [cosven/FeelUOwn#3]
无法登录，输入账号和密码后，返回IP高频，并要求填写验证码，有时验证码不能显示；然后重登录再无反应。
![_025](https://cloud.githubusercontent.com/assets/11811250/8467566/8514c80e-2092-11e5-98c5-cca3d6bd229c.png)

**Comment by cosven** [comment]
IP高频的提示说明可能是：账号密码登陆失败次数过多导致。
重复登录再无反应，多次失败后，我记得需要过一段时间再登陆才行。

**Comment by cosven** [comment]
如果还有错误。
你可以查看软件（FeelUOwn）目录下，有个cache文件夹，里面有个error.log，你可以把这个文件的内容贴出来看看。

**Comment by cosven** [comment]
今天又进行了一些优化，经过一些测试，暂时没发现什么问题。
这个issue我先关掉了，如果有问题，可以重新打开。
