### ISSUE TITLE
测试发现login api挂掉了

### ISSUE THREAD

**Issue by ArkBriar** [cosven/FeelUOwn#30]
如题，
我这边C++项目已经开始，已经码完api module，现在测试发现login api挂掉了，不知道你那边怎么样？

最近发现的新[login api](https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%99%BB%E5%BD%95API%E5%88%86%E6%9E%90)，正准备测试

**Comment by cosven** [comment]
我用的mac 版的API， 我刚才试了下，还是可以用的。要注意的就是 **cookie的字段**

你给的这个链接的API我记得是网页版的吧，貌似也是可行的。

**Comment by AkemiHomura** [comment]
发现了，cookie字段一定要有os=osx，唉，坑了我半天，网页版的api刚测试也出了问题，算了，假装自己是osx吧....

**Comment by cosven** [comment]
假装自己是osx吧 😄
