### ISSUE TITLE
kubuntu 15.04诸多问题

### ISSUE THREAD

**Issue by LER0ever** [cosven/FeelUOwn#31]
# 如图：
* 不显示状态栏图标。。于是，没有办法从mini模式切换到正常模式。。
* 收藏的歌单，不知道是不是因为太多，行间距特别小，都没法看
* 还有就是播放的时候会莫名其妙直接跳到十几秒那儿开始放(第一次放也是，发誓这不是断点续播)
![fuo](https://cloud.githubusercontent.com/assets/10568668/9783073/8bbba74e-57d4-11e5-8868-bbebaf0b383c.png)

**Comment by cosven** [comment]
对于第一个问题：从 mini 模式切换到 正常模式其实是按 ESC 键，本来我是要加一个提示的，后面一直没有去实现这个提示功能。

第二个问题的话，我之后再去测试一下（应该可以在近段时间解决）

第三个问题的话，是不是有时候会出现这种情况，这个问题可能需要稍微研究下。

最后还是欢迎继续反馈问题，我会尽快的修复这些问题的。

**Comment by LER0ever** [comment]
第三个问题刚打开播放器的时候放的第一首歌不会这样，但单曲放第二遍就会莫名快进几十秒

**Comment by cosven** [comment]
第一个和第二个问题理论上应该解决了。你可以更新一下试试

第三个我不是很确定，但是我在Linux上测试的时候都没问题。
