### ISSUE TITLE
一些bug和建议

### ISSUE THREAD

**Issue by uutoto** [cosven/FeelUOwn#33]
感谢作者的努力！ 
我也希望能找出时间，尽快加入开发队伍。
以下是最近使用中遇到的一些问题，和一些建议，
希望能在后面版本得到解决：
（运行环境是ubuntu kylin 15.04）

1.有些歌曲封面还不能完全填充这个图片框
 ![image](https://cloud.githubusercontent.com/assets/8338920/10009674/3e4fe464-6113-11e5-82f8-6bb44c9518ae.png)

2.头像没有缩放显示
![image](https://cloud.githubusercontent.com/assets/8338920/10009712/8689d9b0-6113-11e5-9d41-ebb8244360fa.png) 

3.建议加入随机播放、单曲洗脑循环、评论、快捷键切换歌曲、驻留托盘 等功能。

^_^

**Comment by cosven** [comment]
好呀好呀，先欢迎

###### 关于这个填充图片框的问题

可能是这个专辑图片本身就上下有白边。<https://github.com/cosven/FeelUOwn/blob/master/src/controllers.py#L243>

###### 头像的话， 这边大小貌似写错了。。。之后去改一下
<https://github.com/cosven/FeelUOwn/blob/master/src/controllers.py#L237>

###### 关于加入的这些功能
1. 随机播放、单曲洗脑循环 这两个有了
2. 快捷键切换歌曲 （也支持，就是用笔记本自带的那个切换歌曲的键盘）。可能是没有给说明的原因，大家都不知道...
3. 驻留托盘的话，由于Ubuntu14.04 上面会出现图标跑到左上角的问题,所以就抛弃了。<https://github.com/cosven/FeelUOwn/issues/5>

评论的功能的确是要加入的，不过在加入评论的功能之前，还有这一个任务

1. 改善代码的结构。因为我自己在添加新功能时，发现不是特别方便，代码结构有点混乱。目前的改善代码结构，我主要想把 controller.py 的Controller类拆分小的模块。

**Comment by uutoto** [comment]
哈哈，找到啦，随机播放原来在右下角。。真考眼力。
