### ISSUE TITLE
KDE环境下，没有使用phonon来作为媒体播放器

### ISSUE THREAD

**Issue by ufbycd** [cosven/FeelUOwn#34]
KDE的多媒体播放是由phonon掌控的，其后端不止gstreamer一种。我就是用VLC作为其后端的，发现还要安装gstreamer才能用。
KDE下用phonon的话，跟系统的集成会好很多。

**Comment by cosven** [comment]
这个貌似是Qt5的选择。

Qt5的multimedia这个包依赖于一些后端解码器，我看在linux上，它貌似都需要依赖gstreamer。

**Comment by ArkBriar** [comment]
+ qt5 已经将phonon剥离出主项目了，现在qt整合成一个新的类QMediaPlayer，其后端使用的是gstreamer
+ 我不知道plasma5使用的qt有没有整合phonon，但现在Qt官方确实不支持phonon
