### ISSUE TITLE
搜索框在海外不工作

### ISSUE THREAD

**Issue by sometimesnaive** [cosven/FeelUOwn#38]
如题...依赖应该都安装了的,音乐播放,账号,界面都没问题,就是搜索框没反应.

**Comment by cosven** [comment]
我这边ubuntu（非fedora）试了下，是没有问题的。

你可不可以试着在命令行下通过`app.sh`来运行程序，接着使用搜索框，然后把命令行输出的东西粘贴上来看看，这样便于找到问题，各个不同的系统环境或许存在差别。

**Comment by sometimesnaive** [comment]
发现问题是api..
搜索用的是'http://music.163.com/api/search/get/web'.我是美帝ip,这里会返回失败.但是如果用回'http://music.163.com/api/search/get/就没事.'

**Comment by sometimesnaive** [comment]
@cosven 能否增加api的选项呢,或者直接不用web的api?

**Comment by cosven** [comment]
不好意思，之前忘记改了... @sometimesnaive 

你更新一下吧，刚才把它改过来了.

**Comment by sometimesnaive** [comment]
改api后解决.
