### ISSUE TITLE
怎么调用其它播放器播放mv了？

### ISSUE THREAD

**Issue by helinb** [cosven/FeelUOwn#39]

**Comment by helinb** [comment]
已经解决了，用vlc播放MV总是花屏，还且设置相关的缓存，照样花屏，换了用smplayer调用，并设置相关的缓存并没有出现花屏

**Comment by cosven** [comment]
可能不同系统、不同显卡（硬件）之间差别比较大。

我只在ubuntu 和 deepin上测试了下，感觉vlc表现都不错，然后就决定使用它了。另外一个方面的考虑就是有的播放器并不能很好地从命令行启动。
