### ISSUE TITLE
桌面歌词

### ISSUE THREAD

**Issue by ClarkZhang** [cosven/FeelUOwn#4]
我装好后好像播放器不自带桌面歌词，以前一直用的 OSD Lyrics 也无法调用。 有办法加入桌面歌词吗，或者怎么让osd lyrics 支持呢

**Comment by cosven** [comment]
桌面歌词的功能会在以后考虑加入 ~ 

具体是配合一些歌词软件还是另起炉灶，还要去具体的研究研究

**Comment by cosven** [comment]
已经添加了歌词的功能，但是在交互和中英文歌词匹配上还有待改进。
