### ISSUE TITLE
网易云音乐API问题

### ISSUE THREAD

**Issue by LER0ever** [cosven/FeelUOwn#42]
我又来了。。
这次应该是网易云的API问题，因为darknessomi大大的musicbox也有同样的问题
“创建的歌单”+“收藏的歌单”只能显示100条。。我表示我创建了56个，收藏了125个。
上图，左边是MusicBox有标号的到100没了，右边FeelUOwn到同样的歌单也没了
不过总体来讲FeelUOwn是非常好的第三方客户端，Issue修复也非常快！
![image](https://cloud.githubusercontent.com/assets/10568668/10447305/00d457ba-71b6-11e5-875b-fbd7a7d7a251.png)

于是我想听后面的歌的时候只能苦逼的在手机上把歌单重排序提到前面。。。

**Comment by cosven** [comment]
0.0 竟然收藏了125个歌单 
回家看看什么情况 ...

**Comment by cosven** [comment]
找到问题了，的确是是API限制了。
改到200了...

顺便问一句，如果你有56个歌单，你打开这个软件会不会很卡呀 》_《

**Comment by LER0ever** [comment]
会的。。打开以后有10秒CD。。10秒内动窗体就会跳成无响应

**Comment by cosven** [comment]
恩， 理论上也应该这样。

我写代码的时候，YY了一下大部分用户的情况：自己创建的歌单会比较少，然后收藏歌单稍微多一点。所以程序一开始就会缓存 `56` 个歌单的基本信息... 所以，我猜也是会卡死...

之后，我再加个判断...

**Comment by LER0ever** [comment]
恩，现在正常了，虽然说一百八十几个歌单又像以前一样间距很小缩在一块儿了。。不过我自己调吧

**Comment by cosven** [comment]
这样子.... 最近在计划用HTML把界面重写一下，在界面模块抛弃QT，到时候或许会好点....

**Comment by LER0ever** [comment]
嗯，我个人也比较倾向HTML做UI，Qt库毕竟太大了

**Comment by ArkBriar** [comment]
Σ(っ °Д °;)っ歌单居然上100了！！我那边的UI也要考虑下..

**Comment by LangJay** [comment]
分享一下API好吗？

**Comment by cosven** [comment]
API 可以随便自取哦（很大一部分我也是从 netease-musicbox 那个项目拿过来的。）
