### ISSUE TITLE
最小化到系统托盘

### ISSUE THREAD

**Issue by ClarkZhang** [cosven/FeelUOwn#43]
我在Opensuse和Mint Cinnamon下都没成功最小化到系统托盘, 这款软件支持吗

**Comment by cosven** [comment]
现在实际上不支持 系统托盘了...

**Comment by ClarkZhang** [comment]
那能做到mini后任务栏自动隐藏吗

**Comment by cosven** [comment]
那就没办法在显示出来了....

之后可能考虑给除Ubuntu以外的系统加上 系统托盘

**Comment by cosven** [comment]
mini 后任务栏不是自动隐藏么 ?

**Comment by ClarkZhang** [comment]
在我的Opensuse KDE & Mint Cinnamon上没有啊
