### ISSUE TITLE
歌词窗口大小问题。。。

### ISSUE THREAD

**Issue by sbwtw** [cosven/FeelUOwn#45]
![20151020202916](https://cloud.githubusercontent.com/assets/3384652/10630576/12e013e0-780a-11e5-84ad-829e2cfa3d5a.png)
一旦变大就没办法再变小了

**Comment by ruizhipeng** [comment]
建议添加歌词窗口管理，或者恢复之前歌词占用一个窗口的设定

**Comment by BruceZhang1993** [comment]
播放部分音乐的时候，歌词会自动变大，且不会恢复

**Comment by cosven** [comment]
暂时把窗口大小限定死
