### ISSUE TITLE
国外用户(IP)不能正常播放

### ISSUE THREAD

**Issue by jyanchen** [cosven/FeelUOwn#46]
歌曲的播放进度，一直是00:00，换了几首个都是这样，感觉好象是连不上网（事实可以正常上网）
系统： linux mint 17

**Comment by cosven** [comment]
```sh
sudo apt-get install gstreamer0.10-plugins-good gstreamer0.10-plugins-bad gstreamer0.10-plugins-ugly
sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav
```

这些依赖安装了么？如果安装了还不能播放的话，就只能麻烦你从命令行运行这个程序。

具体的操作方法是：找到feeluown目录，运行app.sh文件。如果有错误的话，就会有相应的错误信息在控制台输出。
```sh
cd feeluwon
./app.sh
```

**Comment by GreatBigWhiteWorld** [comment]
楼主也是在国外么？还是有翻墙软件？

**Comment by zhaodelong** [comment]
我也在国外，明天测试下国内代理，难不成是网易封的。我知道网易因为版权问题封了网页的，windows 客户端一直可以。这两天FeelUOwn 不能用了，我还以为是我装Jupyter的问题。折腾了好几天了

**Comment by GreatBigWhiteWorld** [comment]
我在国内，网页版还是不能播放。

**Comment by cosven** [comment]
#52  那边有解决办法
