### ISSUE TITLE
sudo apt-get install python3-xlib not working

### ISSUE THREAD

**Issue by zhaodelong** [cosven/FeelUOwn#47]
root@lamer:~# apt-get install python3-xlib
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-xlib

找不到 xlib，是不是指
pip3 install python3-xlib ？

**Comment by cosven** [comment]
`apt-get install python3-xlib` 这个没错的。
你的系统的版本是不是比较老？

**Comment by fatali-fataliyev** [comment]
cosven's method not working on my terminal.  return this message : `Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-xlib `

**Comment by cosven** [comment]
> cosven's method not working on my terminal. return this message : `Reading package lists... Done Building dependency tree Reading state information... Done E: Unable to locate package python3-xlib `

What's your Linux distribution?

FeelUOwn does not depend on python3-xlib anymore.

**Comment by fatali-fataliyev** [comment]
> > cosven's method not working on my terminal. return this message : `Reading package lists... Done Building dependency tree Reading state information... Done E: Unable to locate package python3-xlib `
> 
> What's your Linux distribution?
> 
> I think FeelUOwn does not depend on python3-xlib anymore.

Ubuntu 18.04.6 LTS
