### ISSUE TITLE
在archlinux 登陆账号之后直接奔溃

### ISSUE THREAD

**Issue by helinb** [cosven/FeelUOwn#48]
[INFO] [__init__.py line:41] : Using Qt Implementation: PyQt5
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[INFO] [__init__.py line:19] : NetEase Plugin init
[INFO] [connectionpool.py line:207] : Starting new HTTP connection (1): music.163.com
[INFO] [api.py line:79] : Save cookies successfully
[INFO] [connectionpool.py line:207] : Starting new HTTP connection (1): music.163.com
Traceback (most recent call last):
  File "/usr/share/feeluown-git/src/widgets/login_dialog.py", line 145, in __login
    data = self.ne.login(username, password, phone_login)
  File "/usr/share/feeluown-git/src/plugin/NetEaseMusic/normalize.py", line 114, in login
    data = self.access_data_user(data)
  File "/usr/share/feeluown-git/src/plugin/NetEaseMusic/normalize.py", line 356, in access_data_user
    user_data['avatar'] = user_data['profile']['avatarUrl']
KeyError: 'profile'
/usr/bin/FeelUOwn: 行 6:  5150 已放弃               (核心已转储)python /usr/share/feeluown-git/src/main.py

**Comment by cosven** [comment]
你这个帐号是不是新创建的帐号，如果是的话，可能需要先在网页版设置一些基本的信息。

**Comment by helinb** [comment]
可以登录了
