### ISSUE TITLE
Linux mint 17.02 中安装会卡死

### ISSUE THREAD

**Issue by 1386studio** [cosven/FeelUOwn#49]
Linux mint 17.02 中安装会咋在
```
sudo apt-get install python3-xlib 
```
这一步。后来把
```
sudo apt-get install python3-pyqt5.qtmultimedia 1>/dev/null 2>&1
sudo apt-get install python3-pyqt5.qtwebkit 1>/dev/null 2>&1
sudo apt-get install libqt5multimedia5-plugins 1>/dev/null 2>&1
```
中的
```
1>/dev/null 2>&1
```

删掉就好了，也不知道为什么。

**Comment by mudongliang** [comment]
1> /dev/null  2>& 1
是不是缺少空格啊？

**Comment by cosven** [comment]
是因为需要输入密码， 我以为这个bug之前已经修复了。。。
@1386studio  @mudongliang

**Comment by mudongliang** [comment]
如果之前那一步输入过密码的话，在十五分钟之内是不需要输入密码的！
另外，这个bug真是好玩，sudo 验证的密码被略过了，好玩。

**Comment by cosven** [comment]
诶，我之前以为是 `sudo apt-get install python3-xlib ` 后面也有 `1>/dev/null  2>&1`，所以才看不到输入密码的文字。

那这么说的话，难道 `sudo apt-get install python3-xlib ` 这条命令运行了 15 分钟以上？

**Comment by wcy95** [comment]
这里的确是有bug，我也遇到过，之后我手动将依赖安装好了
