### ISSUE TITLE
trayicon位置问题

### ISSUE THREAD

**Issue by Shuing** [cosven/FeelUOwn#5]
系统是ubuntu 14.04,trayicon在左上角，遮挡了其他窗口的关闭按钮。
建议集成进系统的tray里，或者可以拖动也行。

**Comment by cosven** [comment]
这个是QT5在Ubuntu中的bug，暂时没找到相关的解决办法，不好意思了

**Comment by Shuing** [comment]
会在Qt 5.5.0修复。

[Qt5 system tray doesn't work on Ubuntu 14.04](https://bugs.launchpad.net/ubuntu/+source/sni-qt/+bug/1330444).

**Comment by dhqdqk** [comment]
为何我没有这个问题？UBUNTU15.04

**Comment by cosven** [comment]
那是 QT5在Ubuntu14.04中的bug，在Ubuntu15.04 可能已经修复了吧
