### ISSUE TITLE
安装成功，也能打开，能登陆，能看到歌单，但是点播放，没声音，进度条停在00:00

### ISSUE THREAD

**Issue by zhaodelong** [cosven/FeelUOwn#52]
安装成功，也能打开，能登陆，能看到歌单，但是点播放，没声音，进度条停在00:00

这可能是什么原因呢？所有requirement都安装了。
是因为这台linux装了 jupypter 的原因吗？没装jupyter之前可以用，装了之后不行了。

**Comment by cosven** [comment]
应该不是jupyter的原因。我也安装了jupyter。

光看你的描述，我也不太能确定问题所在，希望能在命令行中运行，那样可以看到更多debug信息。

**Comment by zhaodelong** [comment]
直接运行 ./app.sh 不行，因为默认python3是jupyter的。
我从/usr/bin/python3 main.py运行可以，但是没有声音。
整个命令行信息如下。多谢

root@lamer:~/FeelUOwn# ./app.sh
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named 'PyQt5'
root@lamer:~/FeelUOwn# cat app.sh 
#! /bin/sh

cd src
python3 main.py
root@lamer:~/FeelUOwn# python3
Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Oct 19 2015, 21:52:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@lamer:~/FeelUOwn# ./app.sh 
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named 'PyQt5'
root@lamer:~/FeelUOwn# ./app.sh
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named 'PyQt5'
root@lamer:~/FeelUOwn# cd src
root@lamer:~/FeelUOwn/src# ^C
root@lamer:~/FeelUOwn/src# python3
Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Oct 19 2015, 21:52:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@lamer:~/FeelUOwn/src# /usr/bin/python3 main.py 
[INFO] [__init__.py line:41] : Using Qt Implementation: PyQt5
[INFO] [__init__.py line:19] : NetEase Plugin init
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [normalize.py line:31] : trying to update a playlist cache
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [api.py line:79] : Save cookies successfully
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [normalize.py line:149] : music id 193473 is available
[INFO] [normalize.py line:42] : playlist: menderr喜欢的音乐 has been cached
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [connectionpool.py line:203] : Starting new HTTP connection (1): music.163.com
[INFO] [normalize.py line:149] : music id 34586075 is available
[INFO] [normalize.py line:42] : playlist: menderr喜欢的音乐 has been cached
root@lamer:~/FeelUOwn/src#

**Comment by cosven** [comment]
看输出的话，问题不是出在程序代码上的。

所以应该是Qt内部的音频库的依赖或者兼容的问题。我也没想到什么好的解决办法。

我有个想法是：
先把Jupyter卸掉，然后用pip来安装jupyter，然后测试下能不能运行。

**Comment by zhaodelong** [comment]
我把jupyter卸载了，然后又试了一次。这次多等了一会出现解码器错误，看来有希望了。
解码器是哪个包？

[ERROR] [player.py line:195] : 播放器出现错误：缺少解码器
Error: "Could not connect: Socket I/O timed out"

**Comment by zhaodelong** [comment]
另一个可能是我人在国外，这两天网易把国外ip给封了？

**Comment by GreatBigWhiteWorld** [comment]
我是linux系统，但一直用的是网页版听，这两天也出现这个问题了。

就是一切正常，除了音乐进度条始终在00：00，有时候过半个小时突然开始播放。

后来我试了试我用wine装的客户端，可以播放。

我试了windows下客户端，可以播放。再用了下windows的网页版，还是不能播放。

在同一个局域网的手机端也可以正常播放。

以上所有测试都播放了本机没有cache过的歌曲。

我的结论是网易开始封锁网页版了？强制使用客户端？

今天才看到这个项目，准备用看到这个issue，在想是不是所有走web的都不能用了？

**Comment by imzf** [comment]
估计是 dns 问题吧

**Comment by GreatBigWhiteWorld** [comment]
好像真的是，我把dns换国内的就可以。为了防dns污染，用的是远程国外的dns。请问，能不能增加几条hosts让网易云音乐正常工作呢？

**Comment by cosven** [comment]
这个领域我还真没研探索过 ....

另外，你们希望有什么新功能么，近期想不到什么好点子，缺乏动力...

**Comment by zhaodelong** [comment]
破案了，我设置了个国内代理服务器，就可以用了，看来是网易把国外ip封了导致的原因。

**Comment by zhaodelong** [comment]
对国外的用户，提供一个临时解决方法，在terminal使用 http_proxy=国内代理ip：端口 ./app.sh可以听歌了。

下面是个例子，
http_proxy=203.195.162.96:80 ./app.sh

**Comment by GreatBigWhiteWorld** [comment]
github搜dnsmasq-china-list，用了个这个非常好，访问国内网站也快了。
