### ISSUE TITLE
首次使用，提的建议

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [cosven/FeelUOwn#53]
首先要说，这个做的界面已经很好看了, 功能也很强了。尤其是那个“相似歌曲”自动播放列表实在太好了！基本做到了电台功能！！下面说点建议：

其实基本都是网页版本来有的吧：
（按照需求优先级排序）

1. 歌词能否给个非滚动的，尤其有的歌滚的也不对。有个直接显示txt的反而最好了。推荐在“播放全部”下面空白处显示。
2. 歌手能否给个“所有专辑”，“艺人介绍”的链接？
3. 右键添加/新建歌单。 
4. 前进，后退功能。
5. 评论系统不知能否加上。（这个倒是不是很重要）
6. 还是关于歌词的，网易上歌词不全的很多，如果能有自动在歌词网站上搜索匹配最好了。这种类似的插件很多，比如https://robwu.nl/lyricshere/ 这个浏览器插件可以自动显示各种音乐网站，youtube播放歌曲的歌词。

是不是有点贪，哈哈。都开发出来那就真的逆天了，比原版还高级。

最后还是要说那个相似歌曲自动播放的电台功能非常好！

**Comment by cosven** [comment]
说起 **艺人介绍**，我倒是很想类似的功能。

我非常想让一首歌配上一段背景故事。
然而并不知道如何去做这件事...

**Comment by GreatBigWhiteWorld** [comment]
那个就用网易里自带的啊，对了，网易里叫“歌手介绍”。

**Comment by xxxifan** [comment]
从知乎看到的，感谢作者给我们带来这款软件

**Comment by cosven** [comment]
因为 ISSUE 有点老了，就关闭了。

针对以上意见：
1. 评论系统不知能否加上。
2. 右键添加/新建歌单。
3. 歌手能否给个“所有专辑”，“艺人介绍”的链接？

三个都会考虑之后加上，在 开发进展 列表中有提到。
