### ISSUE TITLE
ubuntu15.10安装后生成图标但是打不开播放器

### ISSUE THREAD

**Issue by CortYellow** [cosven/FeelUOwn#54]
已经生成图标但运行没有反应。谢谢。

**Comment by cosven** [comment]
目测是一些依赖没有安装好。

可以按照 readme 一个一个把依赖安装好。（把命令复制粘贴运行一下即可）

**Comment by ZHYfeng** [comment]
```
Traceback (most recent call last):
  File "./src/main.py", line 19, in <module>
    from quamash import QEventLoop
ImportError: No module named 'quamash'
```
少了这个，请问这个是什么库？

**Comment by crafteverywhere** [comment]
也遇到这个问题。
同ubuntu15.10。
已经照说明安装了相关依赖。
点击桌面图标无反应。
运行 bash app.sh 后报错和ls一样。
点击 FeelUOwn.desktop 提示 未信任的应用程序启动器，添加权限后运行无反应。

**Comment by cosven** [comment]
在FeelUOwn目录下执行 `pip3 install -r requirements.txt` 应该就可以了把。

`ImportError: No module named 'quamash'` 这个是python的一个库。<https://github.com/harvimt/quamash>

**Comment by cosven** [comment]
这里有临时的解决方案 <https://github.com/cosven/FeelUOwn/wiki>

**Comment by cosven** [comment]
在最新的代码中已经解决了这个问题。大家可以更新一下。

问题出现的原因从这个[wiki](https://github.com/cosven/FeelUOwn/wiki)中可以略知一二 。
