### ISSUE TITLE
Elementary OS 下，点击关闭按钮，歌词和音乐都无法关闭，只能kill

### ISSUE THREAD

**Issue by BruceZhang1993** [cosven/FeelUOwn#56]
![2015-11-23 11 03 35](https://cloud.githubusercontent.com/assets/6873988/11329099/e414da8c-91d1-11e5-8a0e-12b10c277e0a.png)

顺便期待继续更新哦～

**Comment by cosven** [comment]
按ESC键可以退出歌词的，下次加个提示..

**Comment by BruceZhang1993** [comment]
Got it.
