### ISSUE TITLE
Use xdg-xxx in install.sh

### ISSUE THREAD

**Issue by hghwng** [cosven/FeelUOwn#57]
Using `xdg-desktop-menu` and `xdg-desktop-icon` is the preferred method to install shortcuts to user's desktop environment. See xdg-desktop-menu(1) and xdg-desktop-icon(1).

Also, adding package manager support to mainstream Linux distributions is the best solution.

**Comment by cosven** [comment]
Thanks, I'll try sometime.

**Comment by cosven** [comment]
这次新版本发布的时候，考虑了这些工具。

我发现根据现在项目的规模，直接把相应的配置写入 `.desktop` 文件比较方便。这些工具反而显得有些重，所以暂时不考虑使用。
