### ISSUE TITLE
提个建议吧

### ISSUE THREAD

**Issue by ayanamimcy** [cosven/FeelUOwn#58]
可不可以加入每日推荐这个功能呢 我想这个功能应该有很多人用的哦

**Comment by BruceZhang1993** [comment]
网易云音乐的官网上，似乎只有个性化推荐是类似的功能，不过是推荐歌单，不知有没有类似接口

**Comment by ayanamimcy** [comment]
@BruceZhang1993 有个python版的网易云里面有api接口

**Comment by BruceZhang1993** [comment]
@ayanamimcy 有链接吗，我想看看，有接口就更好了

**Comment by cosven** [comment]
https://github.com/darknessomi/musicbox/blob/master/NEMbox/api.py#L267

@BruceZhang1993
