### ISSUE TITLE
deepin 2014.3安装依赖失败

### ISSUE THREAD

**Issue by daishulzd** [cosven/FeelUOwn#6]
deepin 2014.3 下安装时遇到了 
下列软件包有未满足的依赖关系： python3-pyqt5.qtmultimedia : 依赖: python3-pyqt5 (= 5.2.1+dfsg-1ubuntu1) 但是 5.3.1-1 正要被安装 E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。

**Comment by cosven** [comment]
在Deepin 2014.3，这些pyqt库已经预置在系统中，所以**不需要再次安装**了。

出现这个错误的原因是因为：Ubuntu的源的pyqt5的版本 和 deepin 内置的pyqt5版本冲突，Ubuntu的要低些。
