### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by VliuPro** [cosven/FeelUOwn#60]
1. 不能注销。。
2. 不能更新自己的收藏列表。。本来我准备找找注销重新登陆试试的。。

**Comment by cosven** [comment]
**有时间** 就会把列表更新机制加上去。

注销这个功能，也会在 **有时间** 的时候加上 - -

**Comment by cosven** [comment]
多么想找个队友来做 - - - - - - - -

**Comment by BruceZhang1993** [comment]
@cosven 辛苦辣。。

**Comment by VliuPro** [comment]
@cosven 辛苦辛苦，多想帮你一起做，奈何彩笔根本不会。。

**Comment by cosven** [comment]
最新版本：
注销：删除 `~/.FeelUOwn` 文件夹
更新列表：点击头像
