### ISSUE TITLE
音量控制

### ISSUE THREAD

**Issue by cdroad** [cosven/FeelUOwn#63]
大半夜偷偷玩电脑，安装完一进去点了播放，想调低音量，找了半天音量控制差点把母上吵醒，这居然还没有自带的音量控制，这个是不是有点偷懒啊？虽然说可以从系统那里调。。。但我觉得音量控制好歹还是要有的吧，个人介意。

**Comment by cosven** [comment]
q.q  好吧，会考虑加进去的。

**Comment by cdroad** [comment]
:)加油哟～

**Comment by qq316107934** [comment]
五个月了还没解决。。。期待！

**Comment by AutuanLiu** [comment]
ubuntu下启动好卡

**Comment by M-Kepler** [comment]
ubuntu下安装需要好多依赖包，始终麻烦

**Comment by cosven** [comment]
重写 更麻烦，所以  -- -- 还在写,,,
@qq316107934
