### ISSUE TITLE
双击图标后无法启动播放器

### ISSUE THREAD

**Issue by smcdl** [cosven/FeelUOwn#67]
我的系统是Ubuntu15.10，双击桌面图标后，查看/var/log/syslog显示如下：
Dec 15 13:54:20 eric-ThundeRobot gnome-session[2611]: Traceback (most recent call last):
Dec 15 13:54:20 eric-ThundeRobot gnome-session[2611]: File "/home/eric/sources/FeelUOwn/src/main.py", line 19, in <module>
Dec 15 13:54:20 eric-ThundeRobot gnome-session[2611]: from quamash import QEventLoop
Dec 15 13:54:20 eric-ThundeRobot gnome-session[2611]: ImportError: No module named 'quamash'

点击导航里的图标/var/log/syslog显示如下：
Dec 15 13:59:02 eric-ThundeRobot gnome-session[2611]: (clipit:2702): GLib-CRITICAL **: g_variant_new_string: assertion 'g_utf8_validate (string, -1, NULL)' failed
Dec 15 13:59:02 eric-ThundeRobot gnome-session[2611]: (clipit:2702): GLib-CRITICAL **: g_variant_new_string: assertion 'g_utf8_validate (string, -1, NULL)' failed
Dec 15 13:59:59 eric-ThundeRobot com.canonical.Unity.Scope.Home[2518]: (unity-scope-home:8547): Json-CRITICAL **: json_object_get_object_member: assertion 'node != NULL' failed
Dec 15 13:59:59 eric-ThundeRobot com.canonical.Unity.Scope.Home[2518]: message repeated 9 times: [ (unity-scope-home:8547): Json-CRITICAL **: json_object_get_object_member: assertion 'node != NULL' failed]
Dec 15 14:00:00 eric-ThundeRobot com.canonical.Unity.Scope.Home[2518]: (unity-scope-home:8547): libunity-WARNING **: unity-aggregator-scope.vala:145: 在以 D-Bus 线格式用类型字符串“mv”序列化 GVariant 时发生错误

**Comment by smcdl** [comment]
对于第一个问题，显然我是安装了quamash，用pip3 list可以看到。

**Comment by cosven** [comment]
Ubuntu 15.10 有两个 python3 的版本，分别是3.4，3.5。

如果你安装了 quamash, 但是程序还是显示 `ImportError: No module named 'quamash'`, 你可以试试给两个python版本都安装 quamash 这个库。

**Comment by smcdl** [comment]
我只有一个pip3，这个对应3.4还是3.5我也不知道，怎么能分别安装？麻烦请教我一下。

**Comment by cosven** [comment]
**Ubuntu 15.10 默认的 python3 的版本是3.5.**

直接运行 `pip3.4` 和 `pip3.5` 就可以判断哪个安装哪个没有。

运行 `pip3 --version` 可以查看当前的 pip3 是哪个python版本的。

每个 python 版本都会有一个对应的 easy_install. 在 Ubuntu 15.10 当中，python3.4 对应 easy_install3.4, python 3.5 应该对应 easy_isntall3.5 （这个不是很确定）？

`sudo easy_install3.5 pip3` 就可以安装....
所以如果你需要安装 python3.5 的 pip, 就直接运行 `sudo easy_install3 install pip3`

**Comment by cosven** [comment]
我大概知道了这个原因，可以先参考这个 #74
