### ISSUE TITLE
ASCII 解码错误

### ISSUE THREAD

**Issue by pchjia** [cosven/FeelUOwn#68]
在ubuntu 14(刚安装不久的系统, 有中文输入和字体的支持)中安装的时候, 点击图标无法运行.
于是尝试命令行运行, 发现main.py的45行app.setStyleSheet(qssfile.read())会出现ascii解码错误. 

原因是在FeelUOwn/src/themes/default.qss文件中, 作者用了中文注释. 导致python这个脚本解释程序无法转码...  
如果作者有幸看到, 希望能将中文注释改成英文的, 或者删掉.. 这样兼容性会好很多...

**Comment by cosven** [comment]
这样子 0.0

**Comment by cosven** [comment]
但是我也在中文系统中试过呀，应该没问题的 .... 

但是看你的错误描述，貌似的确存在这个问题，好奇怪....

**Comment by pchjia** [comment]
应该是python解释执行的问题. 你在用字符串的时候, 他知道如何解码, 但是在注释里, 就会有问题....
其实中文编码就会有这样的问题, 只能避免使用中文, 最好还是不要用中文注释, 尤其是这种脚本语言...
