### ISSUE TITLE
用VLC播放MV，VLC闪退

### ISSUE THREAD

**Issue by mupengX** [cosven/FeelUOwn#7]
用VLC播放MV，VLC闪退
环境：Ubuntu 14.04   
           VLC  2.1.6

**Comment by cosven** [comment]
我在Ubuntu 14.04 上试了一下，没出现什么问题。我看了下我的VLC的版本是2.2.1 。
我想你一方面可以单独打开vlc播放视频试试，另一方面，你可以试着更新一下VLC。

**Comment by mupengX** [comment]
单独打开vlc再点击播放MV也不行。我的VLC因为包依赖问题暂时升不上去。囧

**Comment by cosven** [comment]
这样子，你试试播放本地的视频有木有问题，如果没有问题的话，麻烦你再试试下面的这条命令，看它有没有错误。麻烦您了 ~

```
vlc http://v2.music.126.net/20150718002010/0023ff20c97483244548dcce09be4b6e/web/cloudmusic/YCQiICAxJiNhZCAwMyBhIA==/mv/==/285033/20140701144913/4442027076216458_720.mp4 -f --play-and-exit
```

**Comment by AkemiHomura** [comment]
ppa:videolan/master-daily
这个ppa可以更新vlc

**Comment by mupengX** [comment]
@cosven 试了有错误，错误如下：
![vlc](https://cloud.githubusercontent.com/assets/6813564/8765609/abf0bdcc-2e46-11e5-815e-9aba732294f9.png)
@AkemiHomura  那个ppa我试过了。更新不了是因为我的环境中存在部分软件包可能存在了循环依赖导致的问题。

**Comment by cosven** [comment]
天啊，我发现上面那个链接，我的也无法播放。不过下面这个我的可以。
```
vlc -f --play-and-exit http://v2.music.126.net/20150720191254/15c31e46b42a3f99694f477cb7b16371/web/cloudmusic/YCQiICAxJiNhZCAwMyBhIA==/mv/==/285033/20140701144913/4442027076216458_720.mp4
```

**Comment by mupengX** [comment]
我用命令行这种方式播放我本地的MP4文件，没有问题。也可能是因为我这的网速不行，播放在线的，在一定时间内缓存不够的话就退出了。报错：
[1]    19555 segmentation fault (core dumped)  vlc

**Comment by AkemiHomura** [comment]
@mupengX 
segmentation fault这个问题我google到2014年debian上出现过，估计是vlc的bug，新版本应该已经修复了。所以估计要么更新vlc要么换个播放器，不知道你依赖是什么问题？
