### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by shirleyghost** [cosven/FeelUOwn#71]
注明的依赖都已经安装了, mv可以看,但是音乐不能播放,进度条不动,没声音. 白新求解TAT

**Comment by cosven** [comment]
出现这种问题时，唯一的办法就是 **从命令行中** 运行。然后把相应的输出贴出来。

不过我猜有两种可能
1. 是不是你用了全局的翻墙？
2. 依赖没装完整 ？这种可能性比较少。

**Comment by shirleyghost** [comment]
[ERROR] [player.py line:234] : 播放器出现错误：缺少解码器
Error: "Cannot connect to destination (m2.music.126.net)"

**Comment by cosven** [comment]
这么说的话，应该是你用了全局的翻墙。
**网易云音乐对海外的IP做了屏蔽的。**
#52 #46 
你可以看看这两个讨论
