### ISSUE TITLE
安装顺利完成 但是提示缺少解码器 

### ISSUE THREAD

**Issue by SinoReimu** [cosven/FeelUOwn#72]
上面的大概都安装了一遍 但是似乎没有用 能打开

**Comment by cosven** [comment]
单凭这些信息，我不能帮助到你的。

你还需要提供：
1. 系统版本
2. 可以尝试从命令行运行程序。`./app.sh`, 然后把输出的信息复制过来。这样肯定可以找出问题。

不过你说 **提示缺少解码器**，这**只**有两种可能
一种：依赖没有安装好，你可以确认下 `install.sh` 运行过程有木有出现错误。
第二种：第二种就是网络问题（只有网络非常差的情况才会出现）。

**Comment by SinoReimu** [comment]
suse 42.1  [ERROR] [player.py line:222] : 播放器出现error, 类型为2
Warning: "\u627E\u4E0D\u5230\u2018audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true\u2019\u7C7B\u578B\u53EF\u7528\u7684\u89E3\u7801\u5668\u3002"
这是提示错误之后点否的输出内容   我用install.sh安装中途提示没有源 然后我直接每个都去下载源码编译了

**Comment by SinoReimu** [comment]
已解决 升级了一下插件

**Comment by SinoReimu** [comment]
还是谢谢作者

**Comment by cosven** [comment]
解决就好 ~
