### ISSUE TITLE
三个小建议

### ISSUE THREAD

**Issue by wfwf1997** [cosven/FeelUOwn#73]
1. 播放顺序问题。  
虽然软件右下角有一个切换顺序播放、单曲循环、随机播放的开关，但是我好像怎么点都是随机播放模式；
2. 增加320K的解析？   
@yanunon 好像已经搞出了歌曲加密算法？
3. 简化请求头？  
我今天拿C# 测试了半天（抱歉，我网络编程只会C#和JS）发现请求头里只留下了`Referer`结果竟然就成功了，不知道为什么。不知道python下怎么样，能不能简化。

**Comment by cosven** [comment]
抱歉不知怎么的，漏了这个 issue.

第一个问题已经解决了。
第二个问题，暂时可能不去弄，万一被查水表了呢.  qwq
第三个问题的话，我也没有试过简化请求的`header`部分。我就照之前写爬虫的经验，头部加上agent等信息更不容易被发现。
