### ISSUE TITLE
bug报告及建议

### ISSUE THREAD

**Issue by llq520** [cosven/FeelUOwn#75]
1、163帐号无法登录 点了没反应（ubuntukylin15.04）
2、歌曲缓存目录在哪，能否提取mp3文件
3、能否加入酷狗网络资源更多
4、能否搜索mv

**Comment by llq520** [comment]
还有一个建议补充，加入about 可以查看软件版本及更新时间

**Comment by cosven** [comment]
##### 163 账户无法登录
我试了下自己的，是可以的。你可以现在网页版试试你那个账户能不能用。

##### 歌曲缓存
目前没有mp3文件的缓存

##### 假如酷狗网络资源
这个在技术和交互上都会造成一些麻烦。（不会考虑加入的）

##### 搜索mv
这个我需要再去研究下，目前还不是很清楚。

##### 加入about
我觉得这个应该完善下。

非常感谢反馈 ~

**Comment by llq520** [comment]
还有设置选项及音效均衡

**Comment by BruceZhang1993** [comment]
关于音效， Linux Desktop 的音效似乎是个很麻烦的事情

**Comment by wjjun** [comment]
ubuntu15.04上打开了歌词面板后鼠标点击过歌词面板就不能在其它地方输入文字了，需要点开播放器界面空白处才能恢复
