### ISSUE TITLE
对于桌面快捷方式的BUG

### ISSUE THREAD

**Issue by InnerAc** [cosven/FeelUOwn#76]
我使用系统为ubuntu15.10 当直接双击桌面程序时会提示

>ImportError: No module named 'quamash'

当我把

>Exec=python3.5 /home/innerac/software/FeelUOwn/feeluown/main.py

改为

>Exec=python3 /home/innerac/software/FeelUOwn/feeluown/main.py

时，便完美运行。

**Comment by cosven** [comment]
难道 Ubuntu 15.10 默认的python3的版本是3.4?

我晕了，Ubuntu 15.04 默认的python3版本是3.5？

**Comment by BruceZhang1993** [comment]
没用过 15.10 ， 看看 python3 --version 版本号是多少

**Comment by cosven** [comment]
我大概知道了这个原因，可以先参考这个 #74

**Comment by cosven** [comment]
#54  #81 
这两个中，有解决办法。

**Comment by InnerAc** [comment]
```
innerac$ python
python             python3.4          python3.5          python3m-config  
python2            python3.4-config   python3.5m                          
python2.7          python3.4m         python3-config                      
python3            python3.4m-config  python3m      
```
应该是3.5吧，其实默认2.7，现在已经解决。
