### ISSUE TITLE
OSX 歌单太多，收藏的歌单点击自动滚动到底部

### ISSUE THREAD

**Issue by LER0ever** [cosven/FeelUOwn#77]
FeelUOwn在Linux下已经相当完美了，但是OS X下根本没法点到我想要的歌单啊
大概情况是这样的，我收藏的歌单超多，显示都不大正常了（不过这不是问题），OS X下随便点击一个收藏的歌单，鼠标刚点下去歌单列表自动滚动到最下面，然后就点到了下面的歌单(描述有点差)
![SCNSHOT](http://i4.tietuku.com/3d843dc9717d0b7b.png)
贴张GIF吧，我可能描述不是很易懂，反正就是刚要点的时候会往下跳。。
![SCNANIM](http://i4.tietuku.com/f0cddd3bbe1dd19d.gif)

**Comment by cosven** [comment]
这样子，目测是歌单太多导致的问题。跟OS X 应该没有关系。这个问题我之后看看？

我自己也是在 OS X 下使用。

看到你的截图，我倒是有个疑问。
为啥你的图标可以正常的显示，我用的 OS X EI Captain, 但是图标一直都是python的图标。而不是专辑的图片。就像这样子：
![image](https://cloud.githubusercontent.com/assets/4962134/12143138/0be10d7e-b4b9-11e5-8f89-d7d1d70019cc.png)

**Comment by LER0ever** [comment]
额，我是Hackintosh 10.10，然后用homebrew装了PyQt5，然后terminal跑app.sh的，图标不知道为啥我这儿正常哈哈。

**Comment by LER0ever** [comment]
不过这个问题Linux下不存在，我歌单一向很多，但是Manjaro和Deepin下都能正常点击进去啊

**Comment by cosven** [comment]
这样子...  这么说看来要研究研究了...

**Comment by cosven** [comment]
理论上新版本已经 fix
