### ISSUE TITLE
切换歌曲时，随机播放

### ISSUE THREAD

**Issue by weizhbob** [cosven/FeelUOwn#78]
在收藏歌单里切歌或是放歌都是随机播放，点击了下面的按钮后依旧是随机播放，系统是ubuntu14.04

**Comment by cosven** [comment]
恩， 这个问题我也发现了。最近比较忙没去修 bug。

- 可以暂时把 单曲循环当做 随机播放。
- 全部循环 当成 单曲循环
- 随机播放 当成 全部循环

**Comment by cosven** [comment]
commit: f70dab5291adf55dedcc44ab5aa23053abc35790
