### ISSUE TITLE
提示“发生了网络错误，或服务器意外地关闭了连接。”

### ISSUE THREAD

**Issue by MingtaoFu** [cosven/FeelUOwn#79]
ArchLinux。
但是可以登录，搜索。直接上网页版的可以听

**Comment by cosven** [comment]
你是怎样安装的？是用的 `yaourt -S feeluown-git` 这条命令安装的么？

**Comment by MingtaoFu** [comment]
这种与git clone都使用了，都不行

**Comment by cosven** [comment]
这个错误是从哪里提示的，能不能截个图。

我在代码中找不到这句话了...

**Comment by cosven** [comment]
不过我猜，你是不是一些依赖没有安装好。

比如说 gstreamer 一系列的包

**Comment by MingtaoFu** [comment]
![2016-01-09 18-36-43](https://cloud.githubusercontent.com/assets/9403555/12215616/f60a0444-b6ff-11e5-9ac4-15f71e5bbde0.png)
直接运行app.sh 时出现的。
gst-plugins-good gst-plugins-bad gst-plugins-ugly都装了
下面的python-quamash-qt5 AUR显示没有，我装了python-quamash

**Comment by cosven** [comment]
看你上面的截图的话：python的依赖肯定都安装好了。
另外你网页版可以播放，说明应该和翻墙等没有关系。

所以最后的问题只可能是在 gstreamer上了，我认为你可以试试安装其他 `gst-*` 相关的包。(实际上，我也没碰到过这种情况，也看不出来为啥会出现这种情况。 ）

从社区这个包的[历史纪录](https://aur.archlinux.org/packages/feeluown-git/)来看, 应该通过 `yaourt -S feeluown-git` 这个命令来安装就可以了。@helinb

**Comment by MingtaoFu** [comment]
还是不行，先谢过

**Comment by dissipator** [comment]
[INFO] [api request 59] : method=POST url=http://music.163.com/weapi/song/enhance/player/url data={'params': 'sBrpJLR32eQCqqXsBRrKmQ2pbJW5s+859KHdqS8FKcwxA37EMA8hlY/O8SA6XCJRgva/enrIPYIuOQHSq0vJbJhxbM6wymaPY8eLswbNCxY45NO4s7hKwfyTsOMTDi2ynxpYgcCAX3x21gG+ITjnkouluwI90NgfRupT+GZqLwvbdv9lpJsgx3EtTveppvon', 'encSecKey': 'd845877286ddfb1caa273f89fbeb2d4fe636af4eac06374d2f14f1138d78c9036b458bbee24b8823b94a5cec50faa6633b9b6c67af386c0d4869f9a888b9cbab44883d5e2d7864183e6eb9957e58094bf4d35bb4a4abba8584a40710f4ec39bc93f04b47721187db8190e4ac683df96ee0ef75b519bbb82d80af82560a34f639'}
[DEBUG] [player _play 157] : start to play song: 413074398, 我是全英雄联盟最骚的骚猪, http://m8.music.126.net/20160612001230/a4c84fd42ef62ab3a63dca6ce3c2c03a/ymusic/cb1e/b94d/dc83/0f8169c29dbf9f815fd08609edbca149.mp3
[DEBUG] [ui update_media_state 699] : current player media state 2
[DEBUG] [ui update_media_state 699] : current player media state 8
[ERROR] [player on_error_occured 240] : 网络出现错误：不能正确解析资源
Error: "无法解析服务器名。"

**Comment by dissipator** [comment]
好像是服务器的原因。

**Comment by cosven** [comment]
这个 ISSUE 貌似比较老了，感觉你们的问题可能不是一样的。@dissipator 
另外， PDD 的这首歌在我这边可以播放的，你的是一直都不能播放么。

**Comment by dissipator** [comment]
今天可以用了

**Comment by cosven** [comment]
最新 commit 已经移除对 gstremer 的依赖
