### ISSUE TITLE
ubuntu15.10安装后启动桌面图标无反应 （附解决办法）

### ISSUE THREAD

**Issue by yyy123zc** [cosven/FeelUOwn#81]
ubuntu15.10按照教程所有的依赖都安装完成，能在终端运行更新，无错误记录，但启动桌面图标无反应。
将feeluown文件夹在终端打开，命令./main.py，能启动运行，但这个终端页面不能关闭。
桌面图标属性显示python3.5 /home/xxx/FeelUOwn/feeluown/main.py，因本ubuntu15.10的python有2.7/3.4/3.53个版本，我将python3.5改为python / python2.7 / python3.4桌面图标还是不能启动。

**Comment by yyy123zc** [comment]
解决了。我第一次安装时使用了sudo命令：sudo ./install.sh，后更改FeelUOwn文件夹属性为让所有用户对FeelUOwn文件具有写权限：chmod a+x FeelUOwn，再将桌面旧的FeelUOwn图标删除，重新运行安装命令：./install.sh，桌面出现新的FeelUOwn图标，选定图标右键属性，将python3.5 /home/xxx/FeelUOwn/feeluown/main.py的python3.5去掉，只留/home/xxx/FeelUOwn/feeluown/main.py，点击桌面图标FeelUOwn正常启动。

**Comment by cosven** [comment]
赞。
可能还需要注意一些小的问题，比如说从dash搜索时不能运行。你可以参见这个 #54。
