### ISSUE TITLE
随机播放的问题

### ISSUE THREAD

**Issue by wfwf1997** [cosven/FeelUOwn#82]
看了一下控制播放的那段代码，发现随机播放的时候获得下一曲时没有若下一首歌和正在播放的歌曲是同一首的时候就重新抽取的机制，导致在列表中歌曲较少的时候容易出现同一首歌重复放的情况。这种情况我昨天自己在实际使用时也遇到了。希望能加入一个while之类的循环，抽取直到抽到不同的歌为止（不过这样的话当播放列表里只有一首歌的时候还要做单独判断，否则就死循环了……）。

**Comment by cosven** [comment]
我认为偶尔重复播放一首也行啊，没有违反**随机播放**的本意。个人感觉可以接受。

不过，也可以加点逻辑，尽量不重复，不过个人觉得不是特别有必要。
