### ISSUE TITLE
增加配置记录

### ISSUE THREAD

**Issue by sbwtw** [cosven/FeelUOwn#84]
是否考虑增加些配置的记录，比如歌词窗口的状态、位置，循环状态，等等。

本来想用qsettings在.config目录下写文件呢，看到你把配置全放到数据库里面了。。

**Comment by cosven** [comment]
恩，如果要继续优化的话，是有必要增加这些人性化的功能。

不过我想想这个东西不久也快要退役了 - -

**Comment by sbwtw** [comment]
😂😂😈
On 12/01/16 17:34, cosven wrote:
>
> 恩，如果要继续优化的话，是有必要增加这些人性化的功能。
>
> 不过我想想这个东西不久也快要退役了 - -
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cosven/FeelUOwn/issues/84#issuecomment-170851614>.
>

-- 
*石博文*

**Comment by cosven** [comment]
已在 TODO 列表中
