### ISSUE TITLE
OS X不能获取http资源

### ISSUE THREAD

**Issue by gera2ld** [cosven/FeelUOwn#85]
先回答个 #77 里的问题：OS X下设置dock图标需要在外层用`app.setWindowIcon(QIcon('...'))`或者`QApplication.setWindowIcon(QIcon('...'))`。

然后问下OS X El Capitan 10.11.2下无法发出请求，提示

    App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure.

你们遇到了吗？怎么解决的？

**Comment by gera2ld** [comment]
再提个意见，既然已经用`asyncio` + `quamash`了，就不要用`requests`这种阻塞的socket来发请求了吧，直接用基于`asyncio`的`aiohttp`来发请求，完全单线程异步，都不需要用signal传信号了，非常省事。

**Comment by cosven** [comment]
没有遇到过这个问题...

你这个是 python 相关的开发么。搜了下，倒是有相关的问题。
<http://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http>

**Comment by cosven** [comment]
soga，`aiohttp`, 有时间去研究研究

**Comment by gera2ld** [comment]
好像不是python相关，似乎是最新的OS X更新了安全策略，据说要改Info.plist，但是我不知道Python+PyQt可以去哪里改Info.plist。。

**Comment by cosven** [comment]
你是在运行这个软件的时候遇到这个问题了么?

我用的是 10.11.1 ， 暂时没这个问题...

**Comment by gera2ld** [comment]
这个问题是在`QMediaContent(QUrl('http://...'))`的时候才出现，我用的是你以前写的版本，现在这个版本还没有尝试。。

**Comment by cosven** [comment]
这样子。我这里有个自己用的 info.plist, 不知道改下这个能不能达到那个效果
[Uploading FeelUOwn.app.zip…]()

**Comment by gera2ld** [comment]
我刚测试了一下你的最新版本，也是到播放音乐这一步就报错，错误信息一样。

**Comment by gera2ld** [comment]
谢谢你给我的那个包，但是似乎不能运行，打开没有反应。。。

**Comment by cosven** [comment]
要改下一个地方

`Contents/MacOS/FeelMusic` 这里面的路劲需要改下。

**Comment by cosven** [comment]
貌似你需要在 FeelUOwn 目录创建一个 `app.command` 文件 app.command 文件的内容和 `app.sh` 一样即可。
然后再修改那个路径为相应的
```
#! /bin/sh
open -a "iterm" ~/code/FeelUOwn/app.command
```

**Comment by cosven** [comment]
不过我觉得我这个方法成功率比较小，因为它最终也是调用终端来启动软件。

**Comment by gera2ld** [comment]
我运行起来了，但是配置http请求权限还是没成功，我再研究一下。。

**Comment by gera2ld** [comment]
我快找到解决方法了，但是解决过程中遇到一个新的问题，似乎`brew install python3`的python找不到`AppKit`，你项目里的`AppKit`是如何访问到的呢？

**Comment by cosven** [comment]
pip3 可以么，我也不是很记得了...

硬是不行就手动指定下 PYTHONPATH ？

**Comment by cosven** [comment]
你想改 `python3.app` 的 info.plist 文件么？

**Comment by gera2ld** [comment]
我搜到另一个项目也有这个问题，他是在运行中通过`AppKit`动态修改权限的，这样就不需要通过Info.plist了。

**Comment by gera2ld** [comment]
终于搞定了，解决方案：
``` python
import AppKit

AppKit.NSBundle.mainBundle().infoDictionary()['NSAppTransportSecurity'] = dict(NSAllowsArbitraryLoads = True)
```

遇到的坑：

1. AppKit

   需要安装pyobjc：`pip install pyobjc`，但是目前的pyobjc v3.0.4不支持Python3.5，所以只好回退到Python3.4。

1. PyQt5

   `brew install pyqt5` 仅支持Python3.5，因此对于Python3.4需要从源码编译，参考<http://blog.justbilt.com/2015/10/17/setup-pyqt5-on-mac/>。

**Comment by cosven** [comment]
赞 , ◕◡◔

这么说，这软件也可以在 10.11.2 上面跑了？

**Comment by gera2ld** [comment]
我在你的旧版基础上修改的版本已经正常了，这个应该也没问题。。
另外如果有需要的话，我可以来帮你把请求部分都换成asyncio。。

**Comment by cosven** [comment]
我有个问题，你在Mac上会主要用这个软件，而不主要用原生的NetEaseMusic么？

据说 Linux 下，不就的将来，也会有一款 *官方版本* 出来呢，所以目前有点犹豫还要不要继续改进 （我这里都积累了许多改进的需求，都还没动手）

**Comment by gera2ld** [comment]
我就是单纯地觉得好玩。。。不过我觉得做一个命令行版更有竞争力，程序员通常都喜欢简单的，甚至可以把内核和界面完全分离，内核可以直接用命令行运行，然后外面可以套不同的壳当界面

**Comment by cosven** [comment]
是啊，命令行版也挺好玩的。这里有个命令行版的，功能也挺赞挺全的 <https://github.com/darknessomi/musicbox>
不过现在貌似没以前那么想玩了..... 想想以前折腾Linux多起劲。
