### ISSUE TITLE
启动的时候出现这样的错误信息

### ISSUE THREAD

**Issue by SinoReimu** [cosven/FeelUOwn#86]
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    app_event_loop = QEventLoop(app)
  File "/usr/lib64/python3.4/site-packages/quamash/__init__.py", line 219, in __init__
    super().__init__()
  File "/usr/lib64/python3.4/site-packages/quamash/_unix.py", line 195, in __init__
    asyncio.SelectorEventLoop.__init__(self, selector)
  File "/usr/lib64/python3.4/asyncio/unix_events.py", line 40, in __init__
    super().__init__(selector)
  File "/usr/lib64/python3.4/asyncio/selector_events.py", line 39, in __init__
    self._make_self_pipe()
  File "/usr/lib64/python3.4/asyncio/selector_events.py", line 81, in _make_self_pipe
    self.add_reader(self._ssock.fileno(), self._read_from_self)
  File "/usr/lib64/python3.4/site-packages/quamash/__init__.py", line 343, in add_reader
    self._check_closed()
AttributeError: 'QEventLoop' object has no attribute '_check_closed'

suse leap  安装完quamash之后

**Comment by cosven** [comment]
这个应该和你的系统和系统版本有关系？之前还一直没遇到过这个问题。

另外，你最好 `pip3 install -r requirements.txt` 这样安装 `quamash` 0.5.3 版本的这个库比较好。

**Comment by SinoReimu** [comment]
应该是quamash版本的问题 是对于更新的quamash有兼容问题么

**Comment by cosven** [comment]
我没试过最新版本的 `quamash`，所以或许是会有问题...

**Comment by SinoReimu** [comment]
还有一个问题 gstreamer全部安装完之后 可以顺利打开 但是时间一直停在00：00 这是缺少了哪个依赖么

**Comment by cosven** [comment]
一个是检查你的网络是否有翻墙，国外的IP不可用。（应该是这个原因）#52
二个就是检查 gstreamer 是否安装完整。

**Comment by SinoReimu** [comment]
实验了在网页版ok 所以要该不是ip的问题 gst的话装了1.4的和0.1的ugly good 和bad   难道是1.4的不行？

**Comment by cosven** [comment]
`gstreamer1.0-libav` 这个你安装了么？如果你是Ubuntu 的话。
另外，终端有啥报错么？

**Comment by cosven** [comment]
开始一直没注意你的系统是 suse leap. 自己没用过，没GET到这个关键词...

**Comment by SinoReimu** [comment]
没有错误 libav是1.6.1-2.1

**Comment by SinoReimu** [comment]
suse我想系统上应该是没什么大问题

**Comment by cosven** [comment]
如果终端也没报错的话，我觉得应该就....应该..没问题了..然而...，我也不是很懂了...

**Comment by SinoReimu** [comment]
有空我看下获取音乐播放这部分的代码 看下能不能解决

**Comment by yutouyes** [comment]
"还有一个问题 gstreamer全部安装完之后 可以顺利打开 但是时间一直停在00：00 "
也遇到了同样的问题。。
tumbleweed-20160130

**Comment by yutouyes** [comment]
因为另一个插件的缘故我安装了gstreamer-0_10-plugins-fluendo_mp3 gstreamer-fluendo-mp3 lame，问题没有解决，不过日志显示
[INFO] [normalize.py line:180] : Read playlist 28556851 info from sqlite
[INFO] [normalize.py line:180] : Read playlist 28556851 info from sqlite
[ERROR] [player.py line:239] : 播放器出现错误：网络连接失败，3秒后尝试播放下一首
Error: "无法建立与音频服务器的连接"
[INFO] [normalize.py line:180] : Read playlist 28556851 info from sqlite
[INFO] [normalize.py line:180] : Read playlist 28556851 info from sqlite
网络连接是正常的

**Comment by cosven** [comment]
由于我自己没用过 suse，我也靠猜测。
首先，排除程序本身的问题。因为在其他大部分系统都没问题。
其次，排除网络问题。因为这里有两个实例。

`Error: "无法建立与音频服务器的连接"` 这个错误提示不是我提示的，而是更底层的东西的提示。我猜应该是 gstreamer.

所以我觉得问题就应该出在 播放器解码器等这些东西上。根据之前对Qt 播放器的研究，它会使用gstreamer作为后端的解码播放器。从而问题应该就是 gstreamer 的，而且这个error提示也确实是gstreamer的，google 第一条就可以看得到。

总结一下：应该是 gstreamer 工作不正常。我搜到两个相关的资料，不知道有没有帮助。
- http://opensuse-guide.org/codecs.php
- https://forums.opensuse.org/showthread.php/502700-Banshee-does-not-play-any-music-format

他们的意思大概是：Packman and the VLC repo 两个源冲突。我想，会不会我们这个问题是类似的。

**Comment by yutouyes** [comment]
现在VLC源里没有gstreamer的包了。但是packman里有些gstreamer的包和oss源重复。
我把所有和gstream有关的包都统一换成packman里的版本，报错是
[ERROR] [player.py line:243] : 播放器出现错误：网络连接失败, 3秒后重试
Error: "发生了网络错误，或服务器意外地关闭了连接。"
应该还是gstreamer的问题
我在https://wu.nerd.moe/?p=1861#comment-115083里同样也出现了缓冲失败的情况，两个的成因应该是一样的
（但是我不知道怎么做。。。

**Comment by cosven** [comment]
gstreamer-0_10-plugins-fluendo_mp3 这个包，你有重新安装一下么。

**Comment by yutouyes** [comment]
gstreamer-0_10-plugins-fluendo-mp3 和gstreamer-fluendo-mp3 都重装了，报错依旧
https://github.com/wu-nerd/dmusic-plugin-NeteaseCloudMusic/issues/20我怀疑和gst版本有关，不知道@tyfulcrum 现在是否可以正常使用

**Comment by hwding** [comment]
Traceback (most recent call last):
File "main.py", line 40, in
app_event_loop = QEventLoop(app)
File "/usr/lib64/python3.4/site-packages/quamash/init.py", line 219, in init
super().init()
File "/usr/lib64/python3.4/site-packages/quamash/unix.py", line 195, in __init_
asyncio.SelectorEventLoop.init(self, selector)
File "/usr/lib64/python3.4/asyncio/unix_events.py", line 40, in init
super().init(selector)
File "/usr/lib64/python3.4/asyncio/selector_events.py", line 39, in init
self.make_self_pipe()
File "/usr/lib64/python3.4/asyncio/selector_events.py", line 81, in make_self_pipe
self.add_reader(self._ssock.fileno(), self._read_from_self)
File "/usr/lib64/python3.4/site-packages/quamash/__init.py", line 343, in add_reader
self._check_closed()
AttributeError: 'QEventLoop' object has no attribute '_check_closed'

[openSuSE]

**Comment by SinoReimu** [comment]
应该是与gst版本相关  因为我以前安装了一个gst(版本不记得了)是可以正常使用的

**Comment by bdbai** [comment]
@SinoReimu 是发行版的问题。你可以到 https://github.com/python/cpython/tree/3.4/Lib/asyncio 把 `base_events.py`、`compat.py` 和 `coroutines.py` 覆盖进 `/usr/lib64/python3.4/asyncio/` 里面，这样就解决了。

**Comment by yhlfh** [comment]
解决方法如下：

```
sudo pip3 install asyncio
```

```
env PYTHONPATH=./:/usr/lib/python3.4/site-packages:/usr/lib64/python3.4:/usr/lib64/python3.4/plat-linux:/usr/lib64/python3.4/lib-dynload:/usr/lib64/python3.4/site-packages feeluown
```

**Comment by SinoReimu** [comment]
这个问题大概是这样解决了，和gst版本其实也是有关系的因为我用gst1.0之后版本都有问题 要不要关掉这个issue？ @cosven
