### ISSUE TITLE
歌单active的样式图标会变小

### ISSUE THREAD

**Issue by williamherry** [cosven/FeelUOwn#9]
<img width="178" alt="qq2015071x" src="https://cloud.githubusercontent.com/assets/1032483/8761494/91e7bc16-2d86-11e5-9a88-186042dd2cc8.png">

点过之后hover的样式左边的border就没有来

我试着修了一下，hover的那个不规则矩形搞不来

不知道是我用虚拟机的原因还是python太慢，经常app颜色变的很深，应该是卡住了

**Comment by cosven** [comment]
app 颜色变深说明是卡住了。
一般来说卡住了是因为网速比较慢，因为程序暂时还没怎么对 网络操作 进行相关优化，基本单线程、进程同步工作，所以可能会卡住。

hover那个的确是个bug，我有时间就去修复它

**Comment by cosven** [comment]
对了，那个不规则形状技术上来说：其实是通过设置border来达到目的的。
```
{
    border-left: 10px solid red;
    border-left: 20px solid backgroundcolor;
}
```
然后看起来就像个三角形或者梯形 等等了

**Comment by cosven** [comment]
hover 的那个已经修改过来了。图标变小这个问题相对比较麻烦，近期可能不会去修复了

<https://github.com/cosven/FeelUOwn/commit/00a34aecb217bd856a1078772b83f6b337c51a47>

**Comment by williamherry** [comment]
:+1:
