### ISSUE TITLE
运行时出现ImportError: No module named asyncio

### ISSUE THREAD

**Issue by wangxian0718** [cosven/FeelUOwn#93]
我是archlinux，运行时出现
Traceback (most recent call last):
  File "/usr/share/feeluown-git/feeluown/main.py", line 7, in <module>
    import asyncio
ImportError: No module named asyncio

我已经装了asyncio3.4，还是报错，这是怎么回事。。。

**Comment by cosven** [comment]
有两个疑问：
1. 你有几个python3 的版本?
你可以手动运行 `pip3 install -r requirements.txt`，确保asyncio安装到了python3版本中。
如果还有问题，就需要麻烦你提供其他的一些信息。

**Comment by wangxian0718** [comment]
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
好像没有这文件，难道没有装到python3中吗？

**Comment by cosven** [comment]
你要先进入到 feeluown-git 那个目录。

```
cd feeluown-git
pip3 install -r requirements.txt
```

**Comment by wangxian0718** [comment]
### Ok thank you!

**Comment by wangxian0718** [comment]
可以了，真心不错！希望可以加些插件选择就好了

**Comment by cosven** [comment]
插件选择： 会考虑在下次大的更新中加入简陋的设置方法
