### ISSUE TITLE
@cosven希望添加播放本地音乐的功能

### ISSUE THREAD

**Issue by wzdnzd** [cosven/FeelUOwn#94]
感觉linux下没有好用一点的音乐播放器，特别是播放列表每次都有重新导入，深度音乐感觉也不好用，之前用了一下FeeIUOwn，发现挺漂亮，挺喜欢的，可是好像没有本地音乐播放功能哎，我的是fedora。。。

**Comment by wzdnzd** [comment]
@cosven

**Comment by cosven** [comment]
正在加入，不过要过年了 ...
这两天在弄这个东西
![image](https://cloud.githubusercontent.com/assets/4962134/12776563/eab67fa0-ca91-11e5-8fb3-675d10df45d2.png)

话说 fedora 下用 dbus 么？

**Comment by cosven** [comment]
问题应该是： fedora 能用 gnome 这个桌面环境么？

**Comment by wzdnzd** [comment]
能啊  我用的就是gnome

**Comment by cosven** [comment]
哦， 那就好，那这个功能应该也能在 fedora 上用 ... 写完这功能，就应该准备写本地音乐 ...

**Comment by wzdnzd** [comment]
哦哦，作者威武，辛苦了

**Comment by wzdnzd** [comment]
![2016-02-03 16-29-55](https://cloud.githubusercontent.com/assets/8565764/12776845/0c556b92-ca94-11e5-8a80-4db35b028be7.png)

**Comment by cosven** [comment]
这 gtk 主题是啥？ 感觉不错

**Comment by wzdnzd** [comment]
![2016-02-03 16-41-26](https://cloud.githubusercontent.com/assets/8565764/12776987/00e33a40-ca95-11e5-8316-f582f7ab017f.png)

**Comment by wzdnzd** [comment]
![2016-02-03 16-43-26](https://cloud.githubusercontent.com/assets/8565764/12777045/44d20402-ca95-11e5-8bbc-3da4547a89ba.png)

**Comment by wzdnzd** [comment]
@cosven 弱弱地问一句，为什么不用docker啊，这样就不用考虑是什么系统了啊

**Comment by cosven** [comment]
我只是听说过 docker，没有具体了解过。
不知道 docker 有木有提供相关的开发包，比如 qt，pyqt ... （我觉得 docker 应该会有一些相应的限制吧）

另外，我一开始的时候，也没考虑这么多问题的，就自己玩玩 ...

**Comment by 1dot75cm** [comment]
@cosven  我刚刚将这个软件添加到 [FZUG](https://github.com/FZUG/repo) 源了，软件看起来很棒。
```
$ dnf install feeluown
```
@wzdnzd  另外，蓝deng社区源里也刚刚添加。

**Comment by wzdnzd** [comment]
不好意思，弱弱地问一句，什么时候会有本地播放功能么

**Comment by cosven** [comment]
=。= 现在有本地播放功能了... 仅限 master 分支...

年旧的 issue，暂时先 close 了。
