### ISSUE TITLE
Mpris 可以处理 Media Keys 事件 所以 Linux 平台不需要单独处理快捷键了

### ISSUE THREAD

**Issue by wenLiangcan** [cosven/FeelUOwn#96]
否则按 media keys 时也会触发 mpris 造成操作被执行了两次。

**Comment by cosven** [comment]
是的，我记得明明把另外一个插件注释掉了....（然而并没有....）

**Comment by cosven** [comment]
505a3c8ba2e6d37424deb8c52ff0a836969afaaf
