### ISSUE TITLE
难道注定不能再用此软件了么

### ISSUE THREAD

**Issue by wzdnzd** [cosven/FeelUOwn#97]
发行版是fedora，一开始用报错，No module named PyQt5,因为fedora下没有PyQt5，只得自己编译安装，不想却报错"致命错误：qgeolocation.h：没有那个文件或目录",新建qgeolocation.h，make install还是报错，然后发现fedora下也没有python3-dbus.mainloop.pyqt5。。。
![2016-02-06 13-01-38](https://cloud.githubusercontent.com/assets/8565764/12864840/1cda86d0-ccd5-11e5-9b99-8f7e2982aced.png)
![2016-02-06 13-07-50](https://cloud.githubusercontent.com/assets/8565764/12864841/25295460-ccd5-11e5-857f-b8a0f2ef4803.png)

**Comment by 1dot75cm** [comment]
：） 等我打个包， 关注 https://github.com/FZUG/repo

**Comment by 1dot75cm** [comment]
可以了， 添加 FZUG 源，然后执行以下命令：
```
$ dnf install feeluown
```

**Comment by cosven** [comment]
刚用的 federa 22测试了下, 添加了 FZUG , 然后安装 feeluown , 她说没这个包。(不知道有没有漏掉什么步骤)
![image](https://cloud.githubusercontent.com/assets/4962134/13417049/071f2c66-dfa3-11e5-8532-386a6c218842.png)
@1dot75cm

**Comment by cosven** [comment]
貌似只有FZUG 源只有federa 23的feeluown 包。

**Comment by 1dot75cm** [comment]
已添加 fc22, fc23 的包 @cosven

**Comment by cosven** [comment]
3q @1dot75cm
