### ISSUE TITLE
求助啊。。。

### ISSUE THREAD

**Issue by wzdnzd** [cosven/FeelUOwn#98]
不能用啊，求帮忙指点一下，谢谢
![2016-02-06 18-33-31](https://cloud.githubusercontent.com/assets/8565764/12866190/5101fb84-cd00-11e5-8e0f-cc39708933dd.png)

**Comment by 1dot75cm** [comment]
@wzdnzd 可以了， 添加 [FZUG](https://github.com/FZUG/repo) 源，然后执行以下命令：
```
$ dnf install feeluown
```

**Comment by cosven** [comment]
这个应该是pip3

另外，非常感谢打包。那样会省不少事

**Comment by wzdnzd** [comment]
昨天自己折腾好了，春节快乐

**Comment by wzdnzd** [comment]
谢谢，不过昨天自己折腾好了    大家春节快乐
@1dot75cm 还要弱弱地说一句，好像dnf install feeluown不能安装，有FZUG源。。。
![2016-02-07 10-06-10](https://cloud.githubusercontent.com/assets/8565764/12870509/2fce1bfe-cd83-11e5-99cd-88ca3ce2873d.png)

**Comment by 1dot75cm** [comment]
清理一下缓存就好了 @wzdnzd 
@cosven 太客气啦，主要是软件活跃开发，而且质量很好。 另外，是否可以加入 setup.py， 以 python3 setup.py build/install 这种方式安装至 `/usr/lib/python3.4/site-packages/feeluown/`。

**Comment by wzdnzd** [comment]
确实是好软件，等有播放本地音乐功能就完美了，100个赞，期待本地播放
@cosven 有个小细节，登录以后能否获取头像幷显示出来，还有，点击一首歌刚播放时破音超级严重是怎么回事啊，不会是我个人的问题吧？

**Comment by cosven** [comment]
主要是这东西依赖 pyqt5，pyqt5不想一般的python库一样，它不能通过 pip 安装。所以我也没把它弄成一个库。@1dot75cm

本地播放的功能，近期尽量加入把。下下个考虑的点应该就是本地播放了。（下个考虑的点是让软件可“配置”）@wzdnzd

破音在我的Linux上貌似也有，但是在Mac上貌似没有... 待研究

**Comment by wzdnzd** [comment]
哦哦，解决了一大票linux上听音乐的问题啊 ，大赞@cosven 
弱弱地问一句，现在README.md 那张图片上的发行版是什么啊，似曾相识的感觉，不是elementaryOS吧？还有那主题，黑色质感，好喜欢，求告知啊，谢谢

**Comment by cosven** [comment]
gnome
使用的 gnome shell 主题是 Vertex。

**Comment by wzdnzd** [comment]
linux发行版是什么啊

**Comment by cosven** [comment]
Ubuntu 15.10 unity. 然后安装 Gnome.
不过这个"看相"和哪个发行版并没有关系啊

**Comment by wzdnzd** [comment]
谢谢，我看到那个横着的像8一样的logo，总觉得以前用过，但不记得，所以就以为是某发行版的logo

**Comment by 1dot75cm** [comment]
> 主要是这东西依赖 pyqt5，pyqt5不像一般的python库一样，它不能通过 pip 安装。所以我也没把它弄成一个库。

使用 pip 可以搜到 PyQt5，不过还是使用发行版打包的更好点。

**Comment by wzdnzd** [comment]
为什么总是提示导入config错误啊
[i-dell@bogon ~]$ cd ./FeelUOwn/feeluown/
[i-dell@bogon feeluown]$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from feeluown import config
ImportError: cannot import name 'config' @cosven

**Comment by cosven** [comment]
你有更新到最新代码么？ @wzdnzd 
你运行一下 `update.sh` 试试

**Comment by wzdnzd** [comment]
更新了啊，后来直接到这下载了源代码也是这样。。。

**Comment by wzdnzd** [comment]
导入问题解决了，可是发现新版的mini模式怎么成这样了？想用旧版的替换新版的，可是不知道替换哪几个文件。。。
![2016-02-19 13-39-54](https://cloud.githubusercontent.com/assets/8565764/13167510/c112922c-d70e-11e5-9b01-ad074af135f6.png)

**Comment by cosven** [comment]
我的天。。

**Comment by cosven** [comment]
更新了 ，需要更改下图片的路径...

**Comment by wzdnzd** [comment]
谢谢，刚才我看到ICON_PATH = '../icons'，以为mask.bmp路径没有问题。。。

**Comment by cosven** [comment]
原来的 `ICON_PATH = '../icons/'`，后来发现这样设计不科学，就去掉了后面的斜杠。

**Comment by wzdnzd** [comment]
以前编译安装PyQt5的时候用的qt是5.5.1，今天把qt升级到5.6.0，然后软件用不了了，弱弱的问一句难道还跟qt有关？
![2016-02-24 20-33-07](https://cloud.githubusercontent.com/assets/8565764/13285520/07925d9c-db36-11e5-9b5c-b929cff4c3c7.png)

**Comment by cosven** [comment]
Removed Modules

With Qt 5.6 the following modules are no longer part of the release packages, but users can still build them from source:
- Qt WebKit
- Qt Declarative (Qt Quick 1)

所以，可能是不能用了...

**Comment by wzdnzd** [comment]
好神奇的是折腾了，现在用root身份能用，一般用户就用不了。。。

**Comment by cosven** [comment]
难道是普通用户不能访问到那些库？

**Comment by wzdnzd** [comment]
![2016-02-24 21-28-35](https://cloud.githubusercontent.com/assets/8565764/13286617/986f5872-db3d-11e5-88b5-8475b17521da.png)   好像一直没变过啊权限。。。

**Comment by cosven** [comment]
这个qt的版本不还是5.5么？
你不妨把权限和owner改一下试试... （我也不知道有用没...）

**Comment by wzdnzd** [comment]
哦哦，我试试，不过权限已经是777了啊。。。

**Comment by wzdnzd** [comment]
还是没用，不过谢谢咯
