### ISSUE TITLE
无法获取歌曲

### ISSUE THREAD

**Issue by yk727228981** [cosven/FeelUOwn#99]
当点开一首歌曲的时候，能获取名称和封面，但是无法播放，命令行模式运行后，发现是
[ERROR] [player.py line:235] : 播放器出现错误：网络连接失败, 3秒后重试
Error: "Forbidden" 
[ERROR] [player.py line:235] : 播放器出现错误：网络连接失败, 3秒后重试
Error: "Forbidden" 
[ERROR] [player.py line:235] : 播放器出现错误：网络连接失败, 3秒后重试
Error: "Forbidden"
是不是网易把api给封了？

**Comment by cosven** [comment]
#52 　国外 IP 不能用。
#86     suse 系统的 gstreamer 库有问题。

**Comment by yk727228981** [comment]
我是在国内啊，ss我也没开，我是用的你的install.sh的安装方式安装的，当时因为外出所以用的cmcc，不会是cmcc的问题吧？

**Comment by yk727228981** [comment]
播放问题解决了，是cmcc的dns的问题，我回家之后连接没问题了，但是专辑图片不显示怎么回事啊

**Comment by yk727228981** [comment]
问题解决了，cmcc的dns的问题，谢谢git主的帮助：）
